* status: 人译到donehere

* 1 Plausible reasoning 合情推理

The actual science of logic is conversant at present only with things either certain, impossible, or entirely doubtful, none of which (fortunately) we have to reason on. Therefore the true logic for this world is the calculus of Probabilities, which takes account of the magnitude of the probability which is, or ought to be, in a reasonable man’s mind. 

James Clerk Maxwell (1850) 

逻辑学只熟知那些确定的/不可能的/完全可疑的事情，幸运的是我们并不在此之上进行推理。 因此这个世界的逻辑其实是计算可能性，即在理性人的思维中是如何考量可能性的大小的。

James Clerk Maxwell (1850) 

Suppose some dark night a policeman walks down a street, apparently deserted. Suddenly he hears a burglar alarm, looks across the street, and sees a jewelry store with a broken window. Then a gentleman wearing a mask comes crawling out through the broken window, carrying a bag which turns out to be full of expensive jewelry. The policeman doesn’t hesitate at all in deciding that this gentleman is dishonest. But by what reasoning process does he arrive at this conclusion? Let us first take a leisurely look at the general nature of such problems. 

设想在一个漆黑的夜晚,一名警察走在空无一人的街道上。 突然，他听到了警铃大作，在街对面，看到一珠宝店的窗户碎了。 然后看见一个戴着面具的男士从破碎的窗户里爬出来，背着一个装满昂贵珠宝的包。 警察毫不迟疑地断定这个男人是个小偷。 但是他通过什么推理过程得出这个结论呢？ 让我们首先从容的看看这种问题的一般本质。

** 1.1 Deductive and plausible reasoning 演绎推理和合情推理

A moment’s thought makes it clear that our policeman’s conclusion was not a logical deduction from the evidence; for there may have been a perfectly innocent explanation for everything. It might be, for example, that this gentleman was the owner of the jewelry store and he was coming home from a masquerade party, and didn’t have the key with him. However, just as he walked by his store, a passing truck threw a stone through the window, and he was only protecting his own property. 
花几秒钟想一下,我们就能知道警察得出结论不是基于对证据的演绎推理, 因为对于任何事情都可以找到一个完美无暇的开脱。 例如，这位先生可能就是这家珠宝店的老板，他刚从一个化妆舞会派对回家并且忘了带钥匙。 当他恰好走过他的珠宝店时，一辆路过的卡车丢出一块石头打破了窗户，于是他不得不保护自己的财产。

Now, while the policeman’s reasoning process was not logical deduction, we will grant that it had a certain degree of validity. The evidence did not make the gentleman’s dishonesty certain, but it did make it extremely plausible. This is an example of a kind of reasoning in which we have all become more or less proficient, necessarily, long before studying mathematical theories. We are hardly able to get through one waking hour without facing some situation (e.g. will it rain or won’t it?) where we do not have enough information to permit deductive reasoning; but still we must decide immediately what to do. 
现在，虽然警察的推理过程并不合乎逻辑演绎，但我们仍然相信这很是合情合理。 证据并不能证明这位先生一定是个小偷,但看起来这是合情合理的推论。 这种推理的例子,在我们学会数学理论之前,就已经或多或少的熟练运用了。 在我们散步看风景的时候,对有些突发问题(是不是要下雨了),我们没有充分的信息来进行演绎推理，但我们仍然必须快速的做出决定。

In spite of its familiarity, the formation of plausible conclusions is a very subtle process. Although history records discussions of it extending over 24 centuries, probably nobody has ever produced an analysis of the process which anyone else finds completely satisfactory. In this work we will be able to report some useful and encouraging new progress, in which conflicting intuitive judgments are replaced by definite theorems, and ad hoc procedures are replaced by rules that are determined uniquely by some very elementary – and nearly inescapable – criteria of rationality. 
尽管这听起来很熟悉，但得出合情结论是一个非常微妙的过程。 尽管对此过程的讨论记载已经延续了24个世纪，看起来还没人能把这个过程分析的让所有人都完全满意。 在本书中，我们将给出一些有用的和令人鼓舞的新进展，其中用明确的定理取代矛盾的直觉，特别是用一些基本的--几乎不可避免的--理性标准来取代特殊解决手法.

All discussions of these questions start by giving examples of the contrast between deductive reasoning and plausible reasoning. As is generally credited to the Organon of Aristotle (fourth century bc) deductive reasoning (apodeixis) can be analyzed ultimately into the repeated application of two strong syllogisms: 
所有关于这些问题的讨论都以演绎推理和合理推理之间的对比开始。 一般认为是亚里士多德（约公元前四世纪）(注1)最先系统的规范了演绎推理（apodeixis）,将其归结为对两种强三段论的反复运用：

如果A为真,则B为真
A为真            (1.1)
----------------------------------------
所以B为真

and its inverse:

及其逆用:

如果A为真,则B为真
B为假                (1.2)
所以A为假

This is the kind of reasoning we would like to use all the time; but, as noted, in almost all the situations confronting us we do not have the right kind of information to allow this kind of reasoning. We fall back on weaker syllogisms (epagoge):

这种推理方式是我们最想使用的; 但是，在几乎所有我们遇到的情况中，我们都找不到合适的信息来进行这种推理。 我们只好求助于弱三段论（epagoge）：

如果A为真,则B为为真
B为真                (1.3)
所以,A为真变得更加合情理

The evidence does not prove that A is true, but verification of one of its consequences does give us more confidence in A. For example, let 

证据不足以证明A为是，但A的一个后果为真确实让我们对A有更多的信心。例如:

A ≡ it will start to rain by 10 am at the latest;
B ≡ the sky will become cloudy before 10 am.

A = 最迟在上午10点开始下雨
B = 上午10点之前天空会变得多云

Observing clouds at 9:45 am does not give us a logical certainty that the rain will follow; nevertheless our common sense, obeying the weak syllogism, may induce us to change our plans and behave as if we believed that it will, if those clouds are sufficiently dark. 

如果上午9:45观察到天空多云,并不能让我们从逻辑上相信一定会下雨。 然而服从弱三段论的常识，会促使我们改变计划仿佛相信雨一定会下的，只要这些云是足够黑暗。

This example shows also that the major premise, ‘if A then B’ expresses B only as a logical consequence of A; and not necessarily a causal physical consequence, which could be effective only at a later time. The rain at 10 am is not the physical cause of the clouds at 9:45 am. Nevertheless, the proper logical connection is not in the uncertain causal direction (clouds =⇒ rain), but rather (rain =⇒ clouds), which is certain, although noncausal. 

这个例子还表明“如果A然后B”这个主要前提,只表示B作为A的逻辑结果,而不一定是一种物理意义上的因果关系,B只有在过一段时间后才会生效。 上午十点下雨不是9点45多云的物理意义上的原因.然而正确的逻辑关系应该是确定的非因果顺序的（雨=>云）,而不是不确定的因果顺序的（云=>雨）。

We emphasize at the outset that we are concerned here with logical connections, because some discussions and applications of inference have fallen into serious error through failure to see the distinction between logical implication and physical causation. The distinction is analyzed in some depth by Simon and Rescher (1966), who note that all attempts to interpret implication as expressing physical causation founder on the lack of contraposition expressed by the second syllogism (1.2). That is, if we tried to interpret the major premise as ‘A is the physical cause of B’, then we would hardly be able to accept that ‘not-B is the physical cause of not-A’. In Chapter 3 we shall see that attempts to interpret plausible inferences in terms of physical causation fare no better. 

我们首先强调的是，我们在这里关心的只是逻辑关系而不是物理因果.由于没有看出逻辑上的蕴涵关系和物理因果之间的区别,导致一些推理发生了严重的错误。 Simon和Rescher（1966）对这一区别进行了深入的分析，他们指出，所有将蕴含解释为是在表达物理因果的努力,都由于缺少强三段论的逆否形式（1.2）而翻了车。 也就是说，如果我们试图把“A是B的物理上的因”解释为大前提，那么我们就无法同时承认“否B也是否A的物理上的因”。 在第三章中我们将看到，试图从物理因果的角度来解释合情推理同样并不灵光。

Another weak syllogism, still using the same major premise, is 

If A is true, then B is true
A is false
(1.4)
therefore, B becomes less plausible.

同样的大前提,另一种弱三段论是

如果A为真,则B为真
A为假       (1.4)
所以,B为看起来更不合情理一些.

In this case, the evidence does not prove that B is false; but one of the possible reasons for its being true has been eliminated, and so we feel less confident about B. The reasoning of a scientist, by which he accepts or rejects his theories, consists almost entirely of syllogisms of the second and third kind. 

在这种情况下，无法证明B是假的;但是B为真的一个前提条件被排除了,因此我们对于B为真的信心就变弱了一些。一个科学家在思考是接受还是拒绝自己的理论时，几乎全部应用的是弱三段论的第二和第三种形式。

Now, the reasoning of our policeman was not even of the above types. It is best described by a still weaker syllogism: 
现在看警察的推理过程并不符合上面的任何一个形式,而是更符合下面的更弱一些的三段论形式:

If A is true, then B becomes more plausible
B is true
(1.5)
therefore, A becomes more plausible.

如果A为真,则B为真的可能性更大
B为真       (1.5)
所以A为真的可能性变的更大了

But in spite of the apparent weakness of this argument, when stated abstractly in terms of A and B, we recognize that the policeman’s conclusion has a very strong convincing power. There is something which makes us believe that, in this particular case, his argument had almost the power of deductive reasoning. 
尽管在用抽象的A和B来表达论证过程时,这种方式的证明力看起来太过薄弱，但我们认识到警察的结论具有很强的说服力。 似乎有什么东西让我们相信，在这个特殊情况下警察的论证几乎具同演绎推理的有同样的可信度。

These examples show that the brain, in doing plausible reasoning, not only decides whether something becomes more plausible or less plausible, but that it evaluates the degree of plausibility in some way. The plausibility for rain by 10 am depends very much on the darkness of those clouds at 9:45. And the brain also makes use of old information as well as the specific new data of the problem; in deciding what to do we try to recall our past experience with clouds and rain, and what the weatherman predicted last night. 
这些例子说明大脑在进行合情推理时，不仅试图判定某事是变得更合情理还是更不合情理，而且以某种方式评估合理的程度。 上午十点有多大可能会下雨很大程度上取决于九点四十五分云层有多黑暗。 在做决定的时候,大脑既使用旧信息也利用新信息,我们试着回忆起我们过去关于云雨相关的经验，还有昨晚的天气预报。

To illustrate that the policeman was also making use of the past experience of policemen in general, we have only to change that experience. Suppose that events like these happened several times every night to every policeman – and that in every case the gentleman turned out to be completely innocent. Very soon, policemen would learn to ignore such trivial things. 

为了说明警察也会利用之前的一般经验，我们只需要改变之前的经历。 假设对于每个警察,这样的事件每晚都发生过几次，而且每次的嫌疑人都是清白无辜的。 那么警察很快就会学会忽略这些微不足道的情况。

Thus, in our reasoning we depend very much on prior information to help us in evaluating the degree of plausibility in a new problem. This reasoning process goes on unconsciously, almost instantaneously, and we conceal how complicated it really is by calling it common sense. 

因此在面对一个新问题时，我们的推理非常依赖于先验信息来帮助我们评估可信度。 这种推理过程在无意识中几乎是瞬间进行，我们通过称之为常识来隐藏其真正的复杂性。

The mathematician George P ́olya (1945, 1954) wrote three books about plausible reasoning, pointing out a wealth of interesting examples and showing that there are definite rules by which we do plausible reasoning (although in his work they remain in qualitative form). The above weak syllogisms appear in his third volume. The reader is strongly urged to consult P ́olya’s exposition, which was the original source of many of the ideas underlying the present work. We show below how P ́olya’s principles may be made quantitative, with resulting useful applications. 

数学家George Polya（1945，1954）写了三本关于合情推理的书，提出了很多有趣的例子，表明我们在做合情推理时应用了确定的一些规则（虽然他的工作仍然是定性的分析）。 上面的弱三段论出现在他的第三卷。 强烈建议读者阅读Polya的阐述，因为它是这本书中许多思想的最初来源。 我们在下面展示了如何将Polya的原理定量化，从而得到有用的应用。

Evidently, the deductive reasoning described above has the property that we can go through long chains of reasoning of the type (1.1) and (1.2) and the conclusions have just as much certainty as the premises. With the other kinds of reasoning, (1.3)–(1.5), the reliability of the conclusion changes as we go through several stages. But in their quantitative form we shall find that in many cases our conclusions can still approach the certainty of deductive reasoning (as the example of the policeman leads us to expect). P ́olya showed that even a pure mathematician actually uses these weaker forms of reasoning most of the time. Of course, on publishing a new theorem, the mathematician will try very hard to invent an argument which uses only the first kind; but the reasoning process which led to the theorem in the first place almost always involves one of the weaker forms (based, for example, on following up conjectures suggested by analogies). The same idea is expressed in a remark of S. Banach (quoted by S. Ulam, 1957): 

Good mathematicians see analogies between theorems; great mathematicians see analogies between analogies. 


显然，在上述的演绎推理中,我们可以把（1.1）和（1.2）串起来形成一个链式的推理过程，并且保证结论和前提具有同样的可靠性。对于(1.3)-(1.5)的推理形式，结论的可靠性随着每一次的应用而发生变化。但是在数量上我们会发现，在许多情况下，我们的结论仍然可以接近演绎推理的可靠性（就像警察的例子中我们预期的那样）。Polya表明，即使是一个纯粹的数学家，大部分时间里实际上也在使用这些较弱的推理形式。当然，在发表一个新发现的定理的时候，数学家会努力去找到一个只用强三段论的论证，但在发现新定理的过程中总是会用到弱三段论来进行推理（例如，用类比的方式来猜测结论）。 S. Banach的评论（S. Ulam，1957）引用了同样的观点：

优秀的数学家看到了理论的相似性;伟大的数学家看到了相似性的相似性.

As a first orientation, then, let us note some very suggestive analogies to another field – which is itself based, in the last analysis, on plausible reasoning.

接下来，让我们观察一下这种相似性,在另一个也是基于合情推理的领域。

注1 Today, several different views are held about the exact nature of Aristotle’s contribution. Such issues are irrelevant to our present purpose, but the interested reader may find an extensive discussion of them in Lukasiewicz (1957).

注1: 今天，关于亚里士多德贡献的确切性质，有几种不同的观点。但和我们目前的目的无关，有兴趣的读者可以参阅Lukasiewicz（1957）的讨论。

** 1.2 Analogies with physical theories 在物理理论中

In physics, we learn quickly that the world is too complicated for us to analyze it all at once. We can make progress only if we dissect it into little pieces and study them separately. Sometimes, we can invent a mathematical model which reproduces several features of one of these pieces, and whenever this happens we feel that progress has been made. These models are called physical theories. As knowledge advances, we are able to invent better and better models, which reproduce more and more features of the real world, more and more accurately. Nobody knows whether there is some natural end to this process, or whether it will go on indefinitely.

在物理领域中，我们很快就认识到现实世界实在是太复杂了，无法一次就解析一切。只有把它分解成小块，再分别研究，才能取得进展。我们先创建一个数学模型，使得它可以体现一部分物理世界的几个特征.这种情况每发生一次，我们就会觉得又取得了一些进展。 我们把这些模型称为物理理论。 随着知识的前进，我们逐步创造出更好的模型，准确地体现现实世界更多的特征。没有人知道这个过程是否会有自然的终点，亦或永无止境的继续下去。

In trying to understand common sense, we shall take a similar course. We won’t try to understand it all at once, but we shall feel that progress has been made if we are able to construct idealized mathematical models which reproduce a few of its features. We expect that any model we are now able to construct will be replaced by more complete ones in the future, and we do not know whether there is any natural end to this process. 

我们以相似的历程来了解常识。 我们不指望一下子理解一切，只要我们能够构建出能够再现其一部分特征的理想数学模型，我们就认为取得了进展。 我们预期,现在任何模型都将在未来被更好的模型所取代，同样我们也不知道这个过程是否会有一个自然的终点。

The analogy with physical theories is deeper than a mere analogy of method. Often, the things which are most familiar to us turn out to be the hardest to understand. Phenomena whose very existence is unknown to the vast majority of the human race (such as the difference in ultraviolet spectra of iron and nickel) can be explained in exhaustive mathematical detail – but all of modern science is practically helpless when faced with the complications of such a commonplace fact as growth of a blade of grass. Accordingly, we must not expect too much of our models; we must be prepared to find that some of the most familiar features of mental activity may be ones for which we have the greatest difficulty in constructing any adequate model. 

比起解决具体问题的方法的相似性,这两者见相似性更加深刻。 常常我们最熟悉的事情是最难理解的。尽管大部分人都未听说过的现象（如铁和镍的紫外光谱的差别）都可以用数学详尽的解释清楚,但是在面对于一片草叶是如何生长的,这个看似常识实则复杂务无比的问题时,所有现代科学都感觉到无能为力。所以不能对目前的模型期望太多,我们必须承认:对人类心理活动的一些特征进行建模竟是极其的困难。

There are many more analogies. In physics we are accustomed to finding that any advance in knowledge leads to consequences of great practical value, but of an unpredictable nature. R ̈ontgen’s discovery of X-rays led to important new possibilities of medical diagnosis; Maxwell’s discovery of one more term in the equation for curl H led to practically instantaneous communication all over the earth.

这种相似性还可以找到很多。 在物理领域中，我们认识到任何新发现都会带来巨大的实际价值，但发现本身却具不可预测。 Rontgen发现了X射线导致了新医学诊断手段的出现; 麦克斯韦在曲线H的等式中的新发现，最终让我们实现了全球范围内的即时通信。

Our mathematical models for common sense also exhibit this feature of practical usefulness. Any successful model, even though it may reproduce only a few features of common sense, will prove to be a powerful extension of common sense in some field of application. Within this field, it enables us to solve problems of inference which are so involved in complicated detail that we would never attempt to solve them without its help. 

我们对常识建立的数学模型也表现出实用性的这一特点。 任何成功的模型，即使只能再现一部分的常识的特征，也将被证明是在某些应用领域中对常识的有力延伸。 在这个领域内，它使我们能够解决推理过程的复杂细节，如果没有这个模型的帮助我们可能都对如何解决这些问题心生畏惧。

** 1.3 The thinking computer 会思考的计算机

Models have practical uses of a quite different type. Many people are fond of saying, ‘They will never make a machine to replace the human mind – it does many things which no machine could ever do.’ A beautiful answer to this was given by J. von Neumann in a talk on computers given in Princeton in 1948, which the writer was privileged to attend. In reply to the canonical question from the audience (‘But of course, a mere machine can’t really think, can it?’), he said: 

不同的模型可能有完全不同的实际用途。 很多人都喜欢说：“他们永远无法用一台机器来替代人的思考,人做的很多事情是机器无法做到的”。冯·诺依曼（J. von Neumann）在一个关于计算机的讨论会(1948年,普林斯顿，作者有幸参加)中给出了一个完美的回答。 在听众提出这个经典问题（显然机器不可能会思考，难道不是吗？”）时,他说：

You insist that there is something a machine cannot do. If you will tell me precisely what it is that a machine cannot do, then I can always make a machine which will do just that! 

你坚持认为有些事情是机器做不到的。但只要你能精确地告诉我机器什么不能做，那我就可以制造一台机器做到它！

In principle, the only operations which a machine cannot perform for us are those which we cannot describe in detail, or which could not be completed in a finite number of steps. Of course, some will conjure up images of G ̈odel incompleteness, undecidability, Turing machines which never stop, etc. But to answer all such doubts we need only point to the existence of the human brain, which does it. Just as von Neumann indicated, the only real limitations on making ‘machines which think’ are our own limitations in not knowing exactly what ‘thinking’ consists of. 

原理上，机器不能为我们执行的唯一操作就是我们无法详细描述所有细节的操作，或者无法在有限次的步骤中完成的操作。 当然，有些人会想到哥德尔不完备定理，图灵机的停机问题等等。但是要回答所有这些怀疑，我们只需要指出能"做到"这些的现实存在--人脑! 就像冯·诺伊曼所指出的那样，制造“思考机器”的唯一限制是我们自己的局限性:我们不知道到底是什么构成了“思维”。

But in our study of common sense we shall be led to some very explicit ideas about the mechanism of thinking. Every time we can construct a mathematical model which reproduces a part of common sense by prescribing a definite set of operations, this shows us how to ‘build a machine’, (i.e. write a computer program) which operates on incomplete information and, by applying quantitative versions of the above weak syllogisms, does plausible reasoning instead of deductive reasoning. 

但是，在我们对常识的研究中，我们可以看出一些关于思考机制的非常显而易见的观点。 每一次我们通过定义一组操作来构建一个数学模型，一个可以再现常识的一个部分的模型.参照这个过程,我们就能“建造一台机器”（例如编写一个计算机程序），它基于不完整的信息上并应用上述弱三段论的量化过程来运行，使用合情推理并不是演绎推理而得出结果。

Indeed, the development of such computer software for certain specialized problems of inference is one of the most active and useful current trends in this field. One kind of problem thus dealt with might be: given a mass of data, comprising 10 000 separate observations, determine in the light of these data and whatever prior information is at hand, the relative plausibilities of 100 different possible hypotheses about the causes at work. 

事实上，针对某些特定的推理问题,开发解决此问题的计算机软件是当前这一领域最活跃和最有用的趋势之一。 这种问题的一个例子可能是：给定大量(包括10 000个独立的观测的)数据，从这些数据和现有的先验信息,来估算可能影响了结果的100种不同原因的相对可信度。

Our unaided common sense might be adequate for deciding between two hypotheses whose consequences are very different; but, in dealing with 100 hypotheses which are not very different, we would be helpless without a computer and a well-developed mathematical theory that shows us how to program it. That is, what determines, in the policeman’s syllogism (1.5), whether the plausibility for A increases by a large amount, raising it almost to certainty; or only a negligibly small amount, making the data B almost irrelevant? The object of the present work is to develop the mathematical theory which answers such questions, in the greatest depth and generality now possible. 

While we expect a mathematical theory to be useful in programming computers, the idea of a thinking computer is also helpful psychologically in developing the mathematical theory. The question of the reasoning process used by actual human brains is charged with emotion and grotesque misunderstandings. It is hardly possible to say anything about this without becoming involved in debates over issues that are not only undecidable in our present state of knowledge, but are irrelevant to our purpose here. 

Obviously, the operation of real human brains is so complicated that we can make no pretense of explaining its mysteries; and in any event we are not trying to explain, much less reproduce, all the aberrations and inconsistencies of human brains. That is an interesting and important subject; but it is not the subject we are studying here. Our topic is the normative principles of logic, and not the principles of psychology or neurophysiology. 

To emphasize this, instead of asking, ‘How can we build a mathematical model of human common sense?’, let us ask, ‘How could we build a machine which would carry out useful plausible reasoning, following clearly defined principles expressing an idealized common sense?’

应用独立的常识我们就足以决定导致不同后果的两个假设之中该如何抉择;但是在面对100个有细微区别的假设时，如果不借助于计算机和指导如何编程的数学理论，我们几乎就是束手无策了。也就是说，在警察的三段论（1.5）中，究竟是A的合理性增加足够多以至于接近于100%肯定,还是由于B的合理性减少的足够小使得B可以忽略不计？本书的目的就是要发展一个数学理论来回答这样的问题，尽可能的使其具有足够的深度和通用性。

虽然我们希望找到一个能够用于计算机编程的数学理论，但会思考的计算机的这个想法,在心理学上也有助于发现这样的数学理论。问题是人脑的真实推理过程中的充满了情感和怪诞的误解。只要谈到这个问题,就无法不涉及一些和我们的目标无关的争论,即我们已经掌握的知识是不是足以解决这个问题?

显然，真正的人类大脑的运作是如此复杂，以至于我们不能解释它的奥秘。在任何情况下，我们都不想解释，更不用说重现人类大脑的所有偏差和不一致。这是一个有趣而重要的课题,但这不是我们在这里研究的课题。我们的话题是正规化的逻辑原理，而不是心理学或神经生理学的原理。

为了强调这一点，我们不要问“如何建立一个人类常识的数学模型？”,而是要问"如何构建一个机器,它遵循具有明确定义的能表述理想化常识的原理,又能进行有意义的合情推理？"

** 1.4 Introducing the robot 机器人

In order to direct attention to constructive things and away from controversial irrelevancies, we shall invent an imaginary being. Its brain is to be designed by us, so that it reasons according to certain definite rules. These rules will be deduced from simple desiderata which, it appears to us, would be desirable in human brains; i.e. we think that a rational person, on discovering that they were violating one of these desiderata, would wish to revise their thinking. 

In principle, we are free to adopt any rules we please; that is our way of defining which robot we shall study. Comparing its reasoning with yours, if you find no resemblance you are in turn free to reject our robot and design a different one more to your liking. But if you find a very strong resemblance, and decide that you want and trust this robot to help you in your own problems of inference, then that will be an accomplishment of the theory, not a premise. 

Our robot is going to reason about propositions. As already indicated above, we shall denote various propositions by italicized capital letters, {A, B, C, etc.}, and for the time being we must require that any proposition used must have, to the robot, an unambiguous meaning and must be of the simple, definite logical type that must be either true or false. That is, until otherwise stated, we shall be concerned only with two-valued logic, or Aristotelian logic. We do not require that the truth or falsity of such an ‘Aristotelian proposition’ be ascertainable by any feasible investigation; indeed, our inability to do this is usually just the reason why we need the robot’s help. For example, the writer personally considers both of the following propositions to be true: 

A ≡ Beethoven and Berlioz never met.
B ≡ Beethoven’s music has a better sustained quality than that of Berlioz, although Berlioz at his best is the equal of anybody.

Proposition B is not a permissible one for our robot to think about at present, whereas proposition A is, although it is unlikely that its truth or falsity could be definitely established today. 2 After our theory is developed, it will be of interest to see whether the present restriction to Aristotelian propositions such as A can be relaxed, so that the robot might help us also with more vague propositions such as B (see Chapter 18 on the A p -distribution). 3 

让我们抛开那些充满争议的无关的事情,把注意力转向建设性的事情,让我构建一个想象出来的东西。我们来设计它的大脑,让它能按照一组确定的规则来进行推理。这组规则是从人脑中简单的必要的本质属性演绎而来。这些属性是如此不可或缺,以至于对一个理性人而言,如果他发觉自己的思路偏离了这些属性时，就会主动自我调整。

原则上,对于这个作为研究对象的机器人，我们想把它设计成什么样就可以设计成什么样子。把我们设计出来的机器人的推理方式和人进行比较,如果你认为两者并不相像的话,你可以重新设计一个,让它更符合你的想法。如果最终，你发现它和人足够相像，相信它能够解决你的推理问题并且愿意让它来帮你解决这些问题，那么这将是我们理论的成功，而不仅仅是我们继续研究的一个前提。

现在我们的机器人已经可以进行命题推理了。如前所述，我们用斜体大写字母{A，B，C等}来表示各种命题，而且我们现在要求所使用的所有命题必须对机器人而言具有明确的意义，简单的意义,即只能是逻辑上的真或假。也就是说，除非另有说明，否则我们只关心二值逻辑或亚里士多德式逻辑。我们并不要求进行任何额外的调查来确定这些“亚里士多德式命题”是真还是假,事实上我们需要机器人的原因正是因为我们并不知道一个命题到底是真还是假。例如，我个人认为以下两个命题是真的：

A≡贝多芬和柏辽兹从未见过面。
B≡贝多芬的音乐比柏辽兹的音乐更耐听，尽管柏辽兹的音乐比任何人都不逊色。

目前,命题B对于我们的机器人目前来说不是不可接受的命题，而命题A是可接受的，虽然今天没人知道他们是不是真的从未见过面(注2)。有趣的是,随着理论的展开，我们可以看看如果对A这种亚里士多德式命题放松一些限制，机器人是不是就能处理像B这样的模糊的命题（参见第18章关于Ap分布）(注3)。 

注2  Their meeting is a chronological possibility, since their lives overlapped by 24 years; my reason for doubting it is the failure of Berlioz to mention any such meeting in his memoirs – on the other hand, neither does he come out and say definitely that they did not meet.

注3 The question of how one is to make a machine in some sense ‘cognizant’ of the conceptual meaning that a proposition like A has to humans, might seem very difficult, and much of the subject of artificial intelligence is devoted to inventing ad hoc devices to deal with this problem. However, we shall find in Chapter 4 that for us the problem is almost nonexistent; our rules for plausible reasoning automatically provide the means to do the mathematical equivalent of this.

注2 从年代上看,他们的会面是可能的，因为他们的有生之年交叠了24年;我怀疑的原因是柏辽兹在回忆录中从没有提到过他们见过面 - 反过来说，他也从未提到他们从未见过面。

注3 从某种意义上说,机器是不是真的能像人理解命题A那样,真正"理解"一个概念的含义?试图证明这个问题是极端困难的,人工智能的许多研究都致力于发明各种奇技淫巧来解决它。但是在第四章我们会看到,合情推理几乎不存在这个问题,合情推理的规则自然而然的具有对此的数学等价性。

** 1.5 Boolean algebra

To state these ideas more formally, we introduce some notation of the usual symbolic logic, or Boolean algebra, so called because George Boole (1854) introduced a notation similar to the following. Of course, the principles of deductive logic itself were well understood centuries before Boole, and, as we shall see, all the results that follow from Boolean al- gebra were contained already as special cases in the rules of plausible inference given by (1812). The symbol

AB,                           (1.6)

called the logical product or the conjunction, denotes the proposition ‘both A and B are true’. Obviously, the order in which we state them does not matter; AB and B A say the same thing. The expression 

A + B,                        (1.7)

called the logical sum or disjunction, stands for ‘at least one of the propositions, A, B is true’ and has the same meaning as B + A. These symbols are only a shorthand way of writing propositions, and do not stand for numerical values. 

为了更正式地陈述这些观点，我们引入常用的符号逻辑或布尔代数，因为乔治·布尔（GeorgeBoole，1854）引入了类似于如下的符号。当然，演绎逻辑本身的原理在布尔之前几个世纪就已经被很好的理解了，而且我们将会看到，布尔代数的所有结果都是都可看成是合情推理规则(1812)一个特例.符号:

AB,                           (1.6)

称为逻辑的积或相交,表示命题"A和B都为真".显然两个命题的顺序无关紧要,AB和BA说的是同一件事.下面的表达式:

A + B,                        (1.7)

称为逻辑的和或并集,表达了"至少有一个命题,A,B为真",其意义和B+A一样.这些符号只是为了方便书写命题的缩写形式,并不表示具体的数值.

Given two propositions A, B, it may happen that one is true if and only if the other is true; we then say that they have the same truth value. This may be only a simple tautology (i.e. A and B are verbal statements which obviously say the same thing), or it may be that only after immense mathematical labor is it finally proved that A is the necessary and sufficient condition for B. From the standpoint of logic it does not matter; once it is established, by any means, that A and B have the same truth value, then they are logically equivalent propositions, in the sense that any evidence concerning the truth of one pertains equally well to the truth of the other, and they have the same implications for any further reasoning. 

Evidently, then, it must be the most primitive axiom of plausible reasoning that two propositions with the same truth value are equally plausible. This might appear almost too trivial to mention, were it not for the fact that Boole himself (Boole, 1854, p. 286) fell into error on this point, by mistakenly identifying two propositions which were in fact different – and then failing to see any contradiction in their different plausibilities. Three years later, Boole (1857) gave a revised theory which supersedes that in his earlier book; for further comments on this incident, see Keynes (1921, pp. 167–168); Jaynes (1976, pp. 240–242). 

In Boolean algebra, the equal sign is used to denote not equal numerical value, but equal truth value: A = B, and the ‘equations’ of Boolean algebra thus consist of assertions that the proposition on the left-hand side has the same truth value as the one on the right-hand side. The symbol ‘≡’ means, as usual, ‘equals by definition’. In denoting complicated propositions we use parentheses in the same way as in ordinary algebra, i.e. to indicate the order in which propositions are to be combined (at times we shall use them also merely for clarity of expression although they are not strictly necessary). In their absence we observe the rules of algebraic hierarchy, familiar to those who use hand calculators: thus AB + C denotes (AB) + C; and not A(B + C). 
* donehere
给定两个命题A，B，当且仅当另一个为真时，可能发生一个是真的;然后我们说他们有相同的真值。这可能只是一个简单的同义反复（即A和B是口头陈述，显然是说同样的事情），也可能是只有经过大量的数学劳动后才能证明A是B的必要和充分的条件。逻辑的立场不重要;一旦以任何方式确定了A和B具有相同的真值，那么它们在逻辑上就是等价的命题，就任何有关一个真理的证据而言，都与另一个的真理同样好，对于任何进一步的推理都有同样的含义。

很明显，那么两个具有相同真值的命题是同样合理的，这一定是最合理的推理原则。这可能显得太琐碎了，如果不是因为布尔本人（布尔，1854年，第286页）在这一点上犯了错误，因为错误地确定了两个事实上是不同的命题，然后看不到任何矛盾在他们不同的可信度。三年后，布尔（1857）提出了一个修正的理论，在他早期的书中取代了这个理论。对这一事件的进一步评论见凯恩斯（1921年，第167-168页）; Jaynes（1976，第240-242页）。

在布尔代数中，等号被用来表示不等于数值，但是等于真值：A = B，因此布尔代数的“等式”由这样的断言组成，即左边的命题具有相同的真值作为右侧的值。像往常一样，符号“≡”的意思是“等于定义”。在表示复杂的命题时，我们使用与普通代数相同的括号，即表示命题合并的顺序（有时候我们也将它们用于表达的清晰度，虽然它们不是绝对必要的）。在他们缺席的情况下，我们观察代数层次的规则，熟悉那些使用手计算器的人：因此AB + C表示（AB）+ C;而不是A（B + C）。

The denial of a proposition is indicated by a bar:
A ≡ A is false.
(1.8)

The relation between A, A is a reciprocal one:
A = A is false,
(1.9)

and it does not matter which proposition we denote by the barred and which by the unbarred letter. Note that some care is needed in the unambiguous use of the bar. For example, according to the above conventions, 

AB = AB is false; (1.10)
A B = both A and B are false. (1.11)

These are quite different propositions; in fact, AB is not the logical product A B, but the logical sum: AB = A + B. 

With these understandings, Boolean algebra is characterized by some rather trivial and obvious basic identities, which express the properties of: 

Idempotence: AA = A
A + A = A
Commutativity: AB = B A
A + B = B + A
Associativity: A(BC) = (AB)C = ABC
A + (B + C) = (A + B) + C = A + B + C
Distributivity: A(B + C) = AB + AC
A + (BC) = (A + B)(A + C)
Duality: If C = AB, then C = A + B
If D = A + B, then D = A B
(1.12)

but by their application one can prove any number of further relations, some highly nontrivial. For example, we shall presently have use for the rather elementary theorem: 

if B = AD then A B = B and B A = A.
(1.13)
Implication

The proposition
A ⇒ B
(1.14)

to be read as ‘A implies B’, does not assert that either A or B is true; it means only that A B is false, or, what is the same thing, (A + B) is true. This can be written also as the logical equation A = AB. That is, given (1.14), if A is true then B must be true; or, if B is false then A must be false. This is just what is stated in the strong syllogisms (1.1) and (1.2).

On the other hand, if A is false, (1.14) says nothing about B: and if B is true, (1.14) says nothing about A. But these are just the cases in which our weak syllogisms (1.3), (1.4) do say something. In one respect, then, the term ‘weak syllogism’ is misleading. The theory of plausible reasoning based on weak syllogisms is not a ‘weakened’ form of logic; it is an extension of logic with new content not present at all in conventional deductive logic. It will become clear in the next chapter (see (2.69) and (2.70)) that our rules include deductive logic as a special case. 
被解读为“A意味着B”，并不认为A或B是真的; 这意味着只有A B是假的，或者说同样的事情（A + B）是真的。 这也可以写成逻辑方程A = AB。 也就是说，如果（1.14），如果A是真的，那么B必须是真的; 或者，如果B是假的，那么A必须是假的。 这就是强三段论（1.1）和（1.2）中所说的。

另一方面，如果A是假的，（1.14）对B没有提及，如果B是真的，（1.14）对A没有提到。但是这些只是我们弱三段论（1.3），（1.4） 不要说点什么 那么，在一个方面，“弱三段论”这个词是误导性的。 基于弱三段论的合理推理理论并不是一种“弱化”的逻辑形式; 它是逻辑的延伸，新的内容在传统的演绎逻辑中根本不存在。 在下一章（见（2.69）和（2.70））中将会清楚，我们的规则包括演绎逻辑作为特例。

A tricky point

Note carefully that in ordinary language one would take ‘A implies B’ to mean that B is logically deducible from A. But, in formal logic, ‘A implies B’ means only that the propositions A and AB have the same truth value. In general, whether B is logically deducible from A does not depend only on the propositions A and B; it depends on the totality of propositions (A, A , A , . . .) that we accept as true and which are therefore available to use in the deduction. Devinatz (1968, p. 3) and Hamilton (1988, p. 5) give the truth table for the implication as a binary operation, illustrating that A ⇒ B is false only if A is true and B is false; in all other cases A ⇒ B is true! 

This may seem startling at first glance; however, note that, indeed, if A and B are both true, then A = AB and so A ⇒ B is true; in formal logic every true statement implies every other true statement. On the other hand, if A is false, then AQ is also false for all Q, thus A = AB and A = AB are both true, so A ⇒ B and A ⇒ B are both true; a false proposition implies all propositions. If we tried to interpret this as logical deducibility (i.e. both B and B are deducible from A), it would follow that every false proposition is logically contradictory. Yet the proposition: ‘Beethoven outlived Berlioz’ is false but hardly logically contradictory (for Beethoven did outlive many people who were the same age as Berlioz). 

Obviously, merely knowing that propositions A and B are both true does not provide enough information to decide whether either is logically deducible from the other, plus some unspecified ‘toolbox’ of other propositions. The question of logical deducibility of one proposition from a set of others arises in a crucial way in the G ̈odel theorem discussed at the end of Chapter 2. This great difference in the meaning of the word ‘implies’ in ordinary language and in formal logic is a tricky point that can lead to serious error if it is not properly understood; it appears to us that ‘implication’ is an unfortunate choice of word, and that this is not sufficiently emphasized in conventional expositions of logic.
请注意，在普通语言中，“A意味着B”意味着B在逻辑上可以从A推导出来。但是，在形式逻辑中，“A意味着B”只意味着命题A和AB具有相同的真值。一般而言，B从逻辑上是否可以从A推导出来，不仅仅取决于命题A和B;它取决于我们所接受的命题（A，A，A，...）的全部，因此可用于扣除。 Devinatz（1968，p。3）和Hamilton（1988，p。5）给出了蕴含作为二元运算的真值表，说明A⇒B只有在A为真且B为假时才为假;在所有其他情况下A⇒B是真实的！

乍一看，这似乎令人吃惊;然而，请注意，如果A和B都是真的，那么A = AB，所以A⇒B是真的;在形式逻辑中，每一个真实的陈述都意味着其他的真实陈述另一方面，如果A是假的，那么AQ对于所有Q也是假的，因此A = AB和A = AB都是真的，所以A⇒B和A⇒B都是真的;一个错误的命题意味着所有的命题。如果我们试图把这个解释为逻辑推导（即B和B都可以从A推导出来），那么每个假命题在逻辑上都是矛盾的。然而，“贝多芬比贝卢奥兹更有活力”这个主张是错误的，但在逻辑上并不矛盾（因为贝多芬比柏辽兹的年龄还要长很多）。

显然，只要知道命题A和B都是真实的，就不能提供足够的信息来决定是否可以从逻辑上推导出另外一个命题，还有一些未指定的其他命题的“工具箱”。一套命题的逻辑推导性问题，在第二章结尾讨论的格罗姆定理中起着至关重要的作用。在普通语言和形式逻辑中，“蕴涵”这个词的意义有很大的不同是一个棘手的问题，如果没有正确理解，会导致严重的错误;在我们看来，“暗示”是一个不幸的词选择，这在传统的逻辑阐述中是不够强调的。

** 1.6 Adequate sets of operations

We note some features of deductive logic which will be needed in the design of our robot. We have defined four operations, or ‘connectives’, by which, starting from two propositions A, B, other propositions may be defined: the logical product or conjunction AB, the logical sum or disjunction A + B, the implication A ⇒ B, and the negation A. By combining these operations repeatedly in every possible way, one can generate any number of new propositions, such as 
我们注意到我们机器人设计中需要的演绎逻辑的一些特征。 我们定义了四个操作，即“连接词”，从两个命题A，B开始，可以定义其他命题：逻辑积或连词AB，逻辑和或分离A + B，蕴涵A→B， 和否定答：通过以各种可能的方式反复地组合这些操作，可以生成任意数量的新命题，例如

C ≡ (A + B)(A + A B) + A B(A + B).
(1.15)

Many questions then occur to us: How large is the class of new propositions thus generated? Is it infinite, or is there a finite set that is closed under these operations? Can every proposition defined from A, B be thus represented, or does this require further connectives beyond the above four? Or are these four already overcomplete so that some might be dispensed with? What is the smallest set of operations that is adequate to generate all such ‘logic functions’ of A and B? If instead of two starting propositions A, B we have an arbitrary number {A 1 , . . . , A n }, is this set of operations still adequate to generate all possible logic functions of {A 1 , . . . , A n }? 

All these questions are answered easily, with results useful for logic, probability theory, and computer design. Broadly speaking, we are asking whether, starting from our present vantage point, we can (1) increase the number of functions, (2) decrease the number of operations. The first query is simplified by noting that two propositions, although they may appear entirely different when written out in the manner (1.15), are not different propositions from the standpoint of logic if they have the same truth value. For example, it is left for the reader to verify that C in (1.15) is logically the same statement as the implication C = (B ⇒ A). 

Since we are, at this stage, restricting our attention to Aristotelian propositions, any logic function C = f (A, B) such as (1.15) has only two possible ‘values’, true and false; and likewise the ‘independent variables’ A and B can take on only those two values. 

At this point, a logician might object to our notation, saying that the symbol A has been defined as standing for some fixed proposition, whose truth cannot change; so if we wish to consider logic functions, then instead of writing C = f (A, B) we should introduce new symbols and write z = f (x, y), where x, y, z, are ‘statement variables’ for which various specific statements A, B, C may be substituted. But if A stands for some fixed but unspecified proposition, then it can still be either true or false. We achieve the same flexibility merely by the understanding that equations like (1.15) which define logic functions are to be true for all ways of defining A, B ; i.e. instead of a statement variable we use a variable statement. 

In relations of the form C = f (A, B), we are concerned with logic functions defined on a discrete ‘space’ S consisting of only 2 2 = 4 points; namely those at which A and B take on the ‘values’ {TT, TF, FT, FF}, respectively; and, at each point, the function f (A, B) can take on independently either of two values {T, F}. There are, therefore, exactly 2 4 = 16 different logic functions f (A, B), and no more. An expression B = f (A 1 , . . . , A n ) involving n propositions is a logic function on a space S of M = 2 n points; and there are exactly 2 M such functions.
那么我们就会有很多问题了：这样产生的新命题有多大？它是无限的，还是在这些操作下有一个有限的集合？ A，B所定义的每一个命题是否都可以这样表示，还是需要进一步的联系？还是这四个已经过度完成了，有些可能会被忽略？什么是足以产生A和B的所有这些“逻辑功能”的最小的一组操作？如果不是两个起始命题A，B，我们有一个任意数{A 1，...，A}。 。 。 ，A n}，这组操作仍然足以生成{A 1，...，A}的所有可能的逻辑函数。 。 。 ，A n}？

所有这些问题都很容易回答，其结果对于逻辑，概率论和计算机设计有用。一般而言，我们正在问，从目前的高度来看，我们可以（1）增加功能的数量，（2）减少操作的数量。第一个查询是简化的，注意到两个命题虽然在以（1.15）的方式写出时可能完全不同，但如果它们具有相同的真值，则从逻辑的角度来看并不是不同的命题。例如，读者可以确认（1.15）中的C在逻辑上与蕴含C =（B⇒A）的语句相同。

因为在这个阶段，我们把注意力集中在亚里士多德命题上，所以任何逻辑函数C = f（A，B）（如（1.15））都只有两个可能的“值”，即真和假;同样，“自变量”A和B也只能取这两个值。

在这一点上，一个逻辑学家可能反对我们的符号，说符号A被定义为一个固定的命题，其真理不能改变;所以如果我们想考虑逻辑函数，那么我们不应该写C = f（A，B），而应该引入新的符号，并写成z = f（x，y），其中x，y，z是'语句变量'各种具体的陈述A，B，C可以被替代。但是，如果A代表一些固定但未明确的命题，那么它仍然可以是真或假。我们仅仅通过这样的理解就可以达到同样的灵活性：定义逻辑函数的方程（1.15）对于定义A，B的所有方法都是真实的;即我们使用一个变量语句而不是一个语句变量。

在C = f（A，B）形式的关系中，我们关注的是在离散的“空间”S上定义的逻辑函数，它由只有2 2 = 4个点组成;即A和B分别取“价值”{TT，TF，FT，FF}并且在每个点上，函数f（A，B）可以独立地取两个值{T，F}中的任一个。因此，正好有2 4 = 16个不同的逻辑函数f（A，B），而不再有。涉及n个命题的表达式B = f（A 1，...，A n）是M = 2 n个点的空间S上的逻辑函数;而且正好有2 M这样的功能。

In the case n = 1, there are four logic functions { f 1 (A), . . . , f 4 (A)}, which we can define by enumeration, listing all their possible values in a truth table:

A T F
f 1 (A)
f 2 (A)
f 3 (A)
f 4 (A) T
T
F
F T
F
T
F

But it is obvious by inspection that these are just

f 1 (A) =
f 2 (A) =
f 3 (A) =
f 4 (A) =
A + A
A
A
A A,
(1.16)

so we prove by enumeration that the three operations: conjunction, disjunction, and negation are adequate to generate all logic functions of a single proposition.

For the case of general n, consider first the special functions, each of which is true at one and only one point of S. For n = 2 there are 2 n = 4 such functions,

A, B TT TF FT FF
f 1 (A, B)
f 2 (A, B)
f 3 (A, B)
f 4 (A, B) T
F
F
F F
T
F
F F
F
T
F F
F
F
T

It is clear by inspection that these are just the four basic conjunctions,

f 1 (A, B) =
f 2 (A, B) =
f 3 (A, B) =
f 4 (A, B) =
A
A
A
A
B
B
B
B.
(1.17)

Consider now any logic function which is true on certain specified points of S; for example, f 5 (A, B) and f 6 (A, B), defined by 

A, B TT TF FT FF
f 5 (A, B)
f 6 (A, B) F
T T
F F
T T
T

We assert that each of these functions is the logical sum of the conjunctions (1.17) that are true on the same points (this is not trivial; the reader should verify it in detail). Thus, 

f 5 (A, B) = f 2 (A, B) + f 4 (A, B)
= A B + A B
= (A + A) B
= B,
(1.18)

and, likewise,

f 6 (A, B) =
=
=
=
f 1 (A, B) + f 3 (A, B) + f 4 (A, B)
AB + A B + A B
B + A B
A + B.
(1.19)

That is, f 6 (A, B) is the implication f 6 (A, B) = (A ⇒ B), with the truth table discussed above. Any logic function f (A, B) that is true on at least one point of S can be constructed in this way as a logical sum of the basic conjunctions (1.17). There are 2 4 − 1 = 15 such functions. For the remaining function, which is always false, it suffices to take the contradiction, f 16 (A, B) ≡ A A. 

This method (called ‘reduction to disjunctive normal form’ in logic textbooks) will work for any n. For example, in the case n = 5 there are 2 5 = 32 basic conjunctions, 

{ABC D E, ABC D E, ABC D E, . . . , A B C D E},
(1.20)

and 2 32 = 4 294 967 296 different logic functions f i (A, B, C, D, E); of which 4 294 967 295 can be written as logical sums of the basic conjunctions, leaving only the contradiction 

f 4294967296 (A, B, C, D, E) = A A.
(1.21)

Thus one can verify by ‘construction in thought’ that the three operations

{conjunction, disjunction, negation},
i.e.
{AND, OR, NOT},
(1.22)

suffice to generate all possible logic functions; or, more concisely, they form an adequate set. 

The duality property (1.12) shows that a smaller set will suffice; for disjunction of A, B is the same as denying that they are both false: 

A + B = (A B).
(1.23)

Therefore, the two operations (AND, NOT) already constitute an adequate set for deductive logic. 4 This fact will be essential in determining when we have an adequate set of rules for plausible reasoning; see Chapter 2.
注4 For you to ponder: Does it follow that these two commands are the only ones needed to write any computer program?

It is clear that we cannot now strike out either of these operations, leaving only the other; i.e. the operation ‘AND’ cannot be reduced to negations; and negation cannot be accomplished by any number of ‘AND’ operations. But this still leaves open the possibility that both conjunction and negation might be reducible to some third operation, not yet introduced, so that a single logic operation would constitute an adequate set. 

It comes as a pleasant surprise to find that there is not only one but two such operations. The operation ‘NAND’ is defined as the negation of ‘AND’: 
因此，这两个操作（AND，NOT）已经构成了演绎逻辑的一个适当的集合。 4这一事实对于确定何时我们有合理的推理规则是必不可少的; 见第2章。
注4为了您的思考：是否遵循这两个命令是唯一需要编写任何计算机程序？

很明显，我们现在不能罢工，只有另一个， 即操作'AND'不能被减少为否定; 否定不能通过任何数量的“与”操作来完成。 但是，这仍然使得联合和否定可能被还原为第三种操作的可能性还没有被引入，这样一个单一的逻辑操作就构成了一个适当的集合。

惊喜地发现，不仅有一个，而且有两个这样的行动。 “NAND”操作被定义为“AND”的否定：

A ↑ B ≡ AB = A + B
(1.24)

which we can read as ‘A NAND B’. But then we have at once

A = A ↑ A
AB = (A ↑ B) ↑ (A ↑ B)
A + B = (A ↑ A) ↑ (B ↑ B).
(1.25)

Therefore, every logic function can be constructed with NAND alone. Likewise, the operation NOR defined by 

A ↓ B ≡ A + B = A B
(1.26)

is also powerful enough to generate all logic functions:

A = A ↓ A
A + B = (A ↓ B) ↓ (A ↓ B)
AB = (A ↓ A) ↓ (B ↓ B).
(1.27)

One can take advantage of this in designing computer and logic circuits. A ‘logic gate’ is a circuit having, besides a common ground, two input terminals and one output. The voltage relative to ground at any of these terminals can take on only two values; say +3 volts, or ‘up’, representing ‘true’; and 0 volts or ‘down’, representing ‘false’. A NAND gate is thus one whose output is up if and only if at least one of the inputs is down; or, what is the same thing, down if and only if both inputs are up; while for a NOR gate the output is up if and only if both inputs are down. 

One of the standard components of logic circuits is the ‘quad NAND gate’, an integrated circuit containing four independent NAND gates on one semiconductor chip. Given a sufficient number of these and no other circuit components, it is possible to generate any required logic function by interconnecting them in various ways. 

This short excursion into deductive logic is as far as we need go for our purposes. Further developments are given in many textbooks; for example, a modern treatment of Aristotelian logic is given by Copi (1994). For non-Aristotelian forms with special emphasis on G ̈odel incompleteness, computability, decidability, Turing machines, etc., see Hamilton (1988). 

We turn now to our extension of logic, which is to follow from the conditions discussed next. We call them ‘desiderata’ rather than ‘axioms’ because they do not assert that anything is ‘true’ but only state what appear to be desirable goals. Whether these goals are attainable without contradictions, and whether they determine any unique extension of logic, are matters of mathematical analysis, given in Chapter 2. 
在设计计算机和逻辑电路方面可以利用这一点。 “逻辑门”是除了公共地之外还具有两个输入端子和一个输出的电路。任何这些端子的相对于地面的电压只能取两个值;说+3伏，或“上”，代表“真”;和0伏或“下”，代表“假”。因此，当且仅当输入端中的至少一个输入端处于关断状态时，与非门才是输出端;或者同样的事情，当且仅当这两个投入都到了;而对于一个或非门来说，当且仅当两个输入都关闭时，输出才有效。

逻辑电路的标准组件之一是“四与非门”，一个在一个半导体芯片上包含四个独立“与非”门的集成电路。给定足够数量的这些电路元件，并且不需要其他电路元件，就可以通过各种方式将它们互连起来而产生任何所需的逻辑功能。

演绎逻辑的这种短暂的游览只要我们需要去为我们的目的。许多教科书都有进一步的发展。例如，Copi（1994）给出了亚里士多德逻辑的现代处理。对于非亚里士多德的形式，特别强调的是不完整性，可计算性，可判定性，图灵机等，见Hamilton（1988）。

现在我们转向我们对逻辑的扩展，这是从下面讨论的条件开始的。我们把他们称为“需要”而不是“公理”，因为他们并不断言任何事情都是“真实的”，而只是说明似乎是理想的目标。这些目标是否可以无矛盾地获得，以及它们是否确定了逻辑的任何独特的延伸，都是第二章给出的数学分析的问题。

** 1.7 The basic desiderata
To each proposition about which it reasons, our robot must assign some degree of plausibility, based on the evidence we have given it; and whenever it receives new evidence it must revise these assignments to take that new evidence into account. In order that these plausibility assignments can be stored and modified in the circuits of its brain, they must be associated with some definite physical quantity, such as voltage or pulse duration or a binary coded number, etc. – however our engineers want to design the details. For present purposes, this means that there will have to be some kind of association between degrees of plausibility and real numbers: 

(I) Degrees of plausibility are represented by real numbers. (1.28)

Desideratum (I) is practically forced on us by the requirement that the robot’s brain must operate by the carrying out of some definite physical process. However, it will appear (Appendix A) that it is also required theoretically; we do not see the possibility of any consistent theory without a property that is equivalent functionally to desideratum (I). 

We adopt a natural but nonessential convention: that a greater plausibility shall correspond to a greater number. It will also be convenient to assume a continuity property, which is hard to state precisely at this stage; to say it intuitively: an infinitesimally greater plausibility ought to correspond only to an infinitesimally greater number. 

The plausibility that the robot assigns to some proposition A will, in general, depend on whether we told it that some other proposition B is true. Following the notation of Keynes (1921) and Cox (1961), we indicate this by the symbol 
根据我们提供的证据，我们的机器人必须根据每个关于它的原因的命题来赋予某种程度的合理性;每当它收到新的证据时，都必须修改这些作业来考虑新的证据。为了使这些合理性分配能够在其大脑的电路中被存储和修改，它们必须与某个确定的物理量相关联，例如电压或脉冲持续时间或二进制编码数等等。但是，我们的工程师想要设计细节。就目前而言，这意味着在可信程度和实际数量之间必须有某种联系：

（I）真实度用实数表示。 （1.28）

Desideratum（I）实际上是强迫我们的要求，机器人的大脑必须进行一定的物理过程。然而，它会出现（附录A），这在理论上也是必需的;如果没有一个与希望（I）功能相当的财产，我们就不会看到任何一致理论的可能性。

我们采用一种自然但不重要的惯例：更大的合理性应该对应更多的合理性。假定一个连续性属性也很方便，这个属性在现阶段很难精确地陈述;直觉地说：一个无限大的可信度应该只对应一个无限小的数字。

机器人指定给某个命题A的合理性一般取决于我们是否告诉它另一个命题B是真实的。在凯恩斯（1921）和考克斯（1961）的符号之后，我们用符号来表示这个符号

A|B,
(1.29)

which we may call ‘the conditional plausibility that A is true, given that B is true’ or just ‘A given B’. It stands for some real number. Thus, for example,

A|BC
(1.30)

(which we may read as ‘A given BC’) represents the plausibility that A is true, given that both B and C are true. Or, 

A + B|C D
(1.31)

represents the plausibility that at least one of the propositions A and B is true, given that both C and D are true; and so on. We have decided to represent a greater plausibility by a greater number, so 

(A|B) > (C|B)
(1.32)

says that, given B, A is more plausible than C. In this notation, while the symbol for plausibility is just of the form A|B without parentheses, we often add parentheses for clarity of expression. Thus, (1.32) says the same thing as 

A|B > C|B,
(1.33)

but its meaning is clearer to the eye. 

In the interest of avoiding impossible problems, we are not going to ask our robot to undergo the agony of reasoning from impossible or mutually contradictory premises; there could be no ‘correct’ answer. Thus, we make no attempt to define A|BC when B and C are mutually contradictory. Whenever such a symbol appears, it is understood that B and C are compatible propositions. 

Also, we do not want this robot to think in a way that is directly opposed to the way you and I think. So we shall design it to reason in a way that is at least qualitatively like the way humans try to reason, as described by the above weak syllogisms and a number of other similar ones. 
为了避免不可能的问题，我们不会要求我们的机器人经历从不可能的或相互矛盾的前提推理的痛苦; 可能没有“正确的”答案。 因此，当B和C相互矛盾时，我们不试图定义A | BC。 只要出现这样的符号，就可以理解B和C是相容的命题。

另外，我们不希望这个机器人以一种与你和我想象的方式直接相反的方式思考。 因此，我们将其设计成至少在性质上类似于人类试图推理的方式进行推理，正如上述弱三段论和其他一些类似推理所描述的那样。

Thus, if it has old information C which gets updated to C in such a way that the plausibility for A is increased: 

(A|C ) > (A|C);
(1.34)

but the plausibility for B given A is not changed:

(B|AC ) = (B|AC).
(1.35)

This can, of course, produce only an increase, never a decrease, in the plausibility that both A and B are true: 

(AB|C ) ≥ (AB|C);
(1.36)

and it must produce a decrease in the plausibility that A is false:

(A|C ) < (A|C).
(1.37)

This qualitative requirement simply gives the ‘sense of direction’ in which the robot’s reasoning is to go; it says nothing about how much the plausibilities change, except that our continuity assumption (which is also a condition for qualitative correspondence with common sense) now requires that if A|C changes only infinitesimally, it can induce only an infinitesimal change in AB|C and A|C. The specific ways in which we use these qualitative requirements will be given in the next chapter, at the point where it is seen why we need them. For the present we summarize them simply as: 

(II) Qualitative correspondence with common sense.
(1.38)

Finally, we want to give our robot another desirable property for which honest people strive without always attaining: that it always reasons consistently. By this we mean just the three common colloquial meanings of the word ‘consistent’: 

(IIIa) If a conclusion can be reasoned out in more than one way, then
every possible way must lead to the same result. (1.39a)

(IIIb) The robot always takes into account all of the evidence it has
relevant to a question. It does not arbitrarily ignore some of
the information, basing its conclusions only on what remains.
In other words, the robot is completely nonideological. (1.39b)

(IIIc) The robot always represents equivalent states of knowledge by
equivalent plausibility assignments. That is, if in two problems
the robot’s state of knowledge is the same (except perhaps for
the labeling of the propositions), then it must assign the same
plausibilities in both. (1.39c)
（二）与常识的定性对应。
（1.38）

最后，我们想给我们的机器人另外一个理想的人物，而不是总能获得理想的财产。 通过这个，我们指的是“一致”这个词的三种常见的口语意义：

（IIIa）如果一个结论可以以不止一种方式被推断出来，那么
一切可能的方式必须导致相同的结果。（1.39A）

（IIIb）机器人总是考虑到所有的证据
与一个问题有关。 它不会随意忽略一些
这些信息只是基于剩下的结论。
换句话说，机器人是完全没有意义的。（1.39b）

（IIIc）机器人总是代表等同的知识状态
等同似是而非的分配。 也就是说，如果有两个问题
机器人的知识状态是相同的（也许除外）
命题的标签），那么它必须分配相同的
两者的合理性。（1.39c）

Desiderata (I), (II), and (IIIa) are the basic ‘structural’ requirements on the inner workings of our robot’s brain, while (IIIb) and (IIIc) are ‘interface’ conditions which show how the robot’s behavior should relate to the outer world.

At this point, most students are surprised to learn that our search for desiderata is at an end. The above conditions, it turns out, uniquely determine the rules by which our robot must reason; i.e. there is only one set of mathematical operations for manipulating plausibilities which has all these properties. These rules are deduced in Chapter 2. 
(At the end of most chapters, we insert a section of informal Comments in which are collected various side remarks, background material, etc. The reader may skip them without losing the main thread of the argument.) 
Desiderata（I），（II）和（IIIa）是我们机器人大脑内部工作的基本“结构”要求，而（IIIb）和（IIIc）是表示机器人行为应该如何关联的“接口” 到外面的世界。

在这一点上，大多数学生惊讶地发现，我们对于寻求意愿的搜寻已经结束了。 事实证明，上述情况唯一地决定了我们的机器人必须推理的规则; 即只有一组用于操纵具有所有这些性质的合理性的数学运算。 这些规则在第2章中推导出来。
（在大多数章节的最后，我们插入一段非正式的评论，其中收集了各种各样的旁白，背景材料等等。读者可以跳过它们，而不会失去论证的主线。）
** 1.8 Comments

As politicians, advertisers, salesmen, and propagandists for various political, economic, moral, religious, psychic, environmental, dietary, and artistic doctrinaire positions know only too well, fallible human minds are easily tricked, by clever verbiage, into committing violations of the above desiderata. We shall try to ensure that they do not succeed with our robot. 

We emphasize another contrast between the robot and a human brain. By Desideratum I, the robot’s mental state about any proposition is to be represented by a real number. Now, it is clear that our attitude toward any given proposition may have more than one ‘coordinate’. You and I form simultaneous judgments about a proposition not only as to whether it is plausible, but also whether it is desirable, whether it is important, whether it is useful, whether it is interesting, whether it is amusing, whether it is morally right, etc. If we assume that each of these judgments might be represented by a number, then a fully adequate description of a human state of mind would be represented by a vector in a space of a rather large number of dimensions. 

Not all propositions require this. For example, the proposition ‘The refractive index of water is less than 1.3’ generates no emotions; consequently the state of mind which it produces has very few coordinates. On the other hand, the proposition, ‘Your mother-in-law just wrecked your new car’ generates a state of mind with many coordinates. Quite generally, the situations of everyday life are those involving many coordinates. It is just for this reason, we suggest, that the most familiar examples of mental activity are often the most difficult to reproduce by a model. Perhaps we have here the reason why science and mathematics are the most successful of human activities: they deal with propositions which produce the simplest of all mental states. Such states would be the ones least perturbed by a given amount of imperfection in the human mind. 

Of course, for many purposes we would not want our robot to adopt any of these more ‘human’ features arising from the other coordinates. It is just the fact that computers do not get confused by emotional factors, do not get bored with a lengthy problem, do not pursue hidden motives opposed to ours, that makes them safer agents than men for carrying out certain tasks. 
作为政治家，各种政治，经济，道德，宗教，心理，环境，饮食和艺术教条的立场的广告商，推销员和宣传家都知道得太好，易犯错的人的头脑很容易被巧妙的言辞所欺骗，以上。我们将尽力确保他们不会与我们的机器人成功。

我们强调机器人和人脑之间的另一个对比。根据Desideratum I，机器人关于任何命题的心理状态都是用一个实数表示的。现在很明显，我们对任何一个命题的态度可能不止一个“协调”。你和我对一个命题做出同时的判断，不仅关于这个命题是否合理，而且关于这个命题是否合乎要求，是否重要，是否有用，是否有趣，是否有趣，是否合乎道德等等。如果我们假定这些判断中的每一个都可以用一个数字来表示，那么对一个人类精神状态的充分描述将会在一个相当大数量的空间中被一个向量所代表。

并不是所有的命题都需要这个。例如，“水的折射率小于1.3”这个命题不会产生任何情绪，因此它所产生的精神状态具有很少的坐标。另一方面，“你婆婆刚破坏你的新车”这个主张产生了许多坐标的心态。一般来说，日常生活的情况是涉及很多坐标的情况。正是由于这个原因，我们建议，心理活动最熟悉的例子往往是一个模型最难以复制的。也许在这里，科学和数学是人类活动中最成功的原因：它们处理产生所有精神状态中最简单的命题。这种状态将会是人类头脑中一定数量的不完善所扰动的状态。

当然，为了多种目的，我们不希望我们的机器人采用从其他坐标中产生的更多“人”特征。电脑不会因为情感因素而感到困惑，不会因为一个长长的问题而感到厌倦，也不会追求与我们相反的隐藏动机，这使得它们在执行某些任务时比男性更安全。

These remarks are interjected to point out that there is a large unexplored area of possible generalizations and extensions of the theory to be developed here; perhaps this may inspire others to try their hand at developing ‘multidimensional theories’ of mental activity, which would more and more resemble the behavior of actual human brains – not all of which is undesirable. Such a theory, if successful, might have an importance beyond our present ability to imagine. 5 

For the present, however, we shall have to be content with a much more modest undertaking. Is it possible to develop a consistent ‘one-dimensional’ model of plausible reasoning? Evidently, our problem will be simplest if we can manage to represent a degree of plausibility uniquely by a single real number, and ignore the other ‘coordinates’ just mentioned. We stress that we are in no way asserting that degrees of plausibility in actual human minds have a unique numerical measure. Our job is not to postulate – or indeed to conjecture about – any such thing; it is to investigate whether it is possible, in our robot, to set up such a correspondence without contradictions. 

But to some it may appear that we have already assumed more than is necessary, thereby putting gratuitous restrictions on the generality of our theory. Why must we represent degrees of plausibility by real numbers? Would not a ‘comparative’ theory based on a system of qualitative ordering relations such as (A|C) > (B|C) suffice? This point is discussed further in Appendix A, where we describe other approaches to probability theory and note that some attempts have been made to develop comparative theories which it was thought would be logically simpler, or more general. But this turned out not to be the case; so, although it is quite possible to develop the foundations in other ways than ours, the final results will not be different.

注5 Indeed, some psychologists think that as few as five dimensions might suffice to characterize a human personality; that is, that we all differ only in having different mixes of five basic personality traits which may be genetically determined. But it seems to us that this must be grossly oversimplified; identifiable chemical factors continuously varying in both space and time (such as the distribution of glucose metabolism in the brain) affect mental activity but cannot be represented faithfully in a space of only five dimensions. Yet it may be that five numbers can capture enough of the truth to be useful for many purposes.21
这些言论是插话指出，有一个可能的概括和扩大的理论在这里发展的一个很大的未探讨的领域;也许这可能会激励他人尝试开发心理活动的“多维理论”，这种理论越来越类似于人类的实际行为 - 并非所有这些都是不可取的。这样一个理论，如果成功的话，可能会超出我们现在的想象能力。五

但是，现在我们不得不满足于一个更为温和的承诺。是否有可能建立一个一致的“一维”的合理推理模型？显然，如果我们能够用一个单一的实数来唯一地表示一定程度的合理性，而忽略刚才提到的其他“坐标”，我们的问题就会变得最简单。我们强调，我们决不是断言在实际的人类头脑中的合理程度有一个独特的数值方法。我们的工作不是假设 - 或者甚至是猜测 - 任何这样的事情;在我们的机器人中调查是否有可能建立这样的通信而没有矛盾。

但对某些人来说，似乎我们已经承担了超过必要的义务，从而对我们的理论的普遍性进行无限制的限制。为什么我们必须用真实数字来表示可信度？基于（A | C）>（B | C）这样的定性排序关系体系的“比较”理论是否足够？这一点在附录A中进一步讨论，在这里我们描述了其他的概率论方法，并且指出了一些尝试来发展比较理论，认为这些理论在逻辑上会更简单，或者更一般。但事实并非如此;所以，虽然我们可以用其他方式来发展基础，但最后的结果不会有什么不同。

注5事实上，一些心理学家认为只要五个维度就足以描述人的个性;也就是说，我们所有人的差异只在于五种基本人格特质的不同组合，而这五种特质可能是基因决定的。但在我们看来，这必须严格过分简化。在空间和时间上不断变化的可识别的化学因素（例如脑中葡萄糖代谢的分布）影响心理活动，但不能仅仅在五维空间中忠实地表示。然而，也许有五个数字能够捕捉到足够的真理，以便用于多种目的

** 1.8.1 Common language vs. formal logic

We should note the distinction between the statements of formal logic and those of ordinary language. It might be thought that the latter is only a less precise form of expression; but on examination of details the relation appears different. It appears to us that ordinary language, carefully used, need not be less precise than formal logic; but ordinary language is more complicated in its rules and has consequently richer possibilities of expression than we allow ourselves in formal logic. 

In particular, common language, being in constant use for other purposes than logic, has developed subtle nuances – means of implying something without actually stating it – that are lost on formal logic. Mr A, to affirm his objectivity, says, ‘I believe what I see.’ Mr B retorts: ‘He doesn’t see what he doesn’t believe.’ From the standpoint of formal logic, it appears that they have said the same thing; yet from the standpoint of common language, those statements had the intent and effect of conveying opposite meanings. 

Here is a less trivial example, taken from a mathematics textbook. Let L be a straight line in a plane, and S an infinite set of points in that plane, each of which is projected onto L. Now consider the following statements: 
我们应该注意形式逻辑和普通语言之间的区别。可以认为后者只是一种不那么确切的表达形式;但是在细节的考察中，关系显得不一样。在我们看来，认真使用的普通语言不一定比形式逻辑不那么精确;但是普通的语言在规则上更加复杂，因此表达的可能性比我们在形式逻辑上所允许的要多。

特别是，除了逻辑以外，常用于其他目的的共同语言，已经形成了细微的细微差别 - 暗含某种东西而没有真正说明它的方式 - 在形式逻辑上丢失了。 A先生肯定他的客观性，说：“我相信我所看到的。”B先生反驳道：“他不明白他不相信什么。”从形式逻辑的角度来看，他们似乎已经说了一样;但从共同语言的角度来看，这些言论具有传达相反意思的意图和效果。

这是一个不太重要的例子，取自数学教科书。设L是平面上的一条直线，S是该平面上的无限点集合，每个点都投影到L上。现在考虑以下语句：

(I) The projection of the limit is the limit of the projections. 

(II) The limit of the projections is the projection of the limit. 

These have the grammatical structures ‘A is B’ and ‘B is A’, and so they might appear logically equivalent. Yet in that textbook, (I) was held to be true, and (II) not true in general, on the grounds that the limit of the projections may exist when the limit of the set does not. 

As we see from this, in common language – even in mathematics textbooks – we have learned to read subtle nuances of meaning into the exact phrasing, probably without realizing it until an example like this is pointed out. We interpret ‘A is B’ as asserting first of all, as a kind of major premise, that A exists; and the rest of the statement is understood to be conditional on that premise. Put differently, in common grammar the verb ‘is’ implies a distinction between subject and object, which the symbol ‘=’ does not have in formal logic or in conventional mathematics. (However, in computer languages we encounter such statements as ‘J = J + 1’, which everybody seems to understand, but in which the ‘=’ sign has now acquired that implied distinction after all.) 

Another amusing example is the old adage ‘knowledge is power’, which is a very cogent truth, both in human relations and in thermodynamics. An ad writer for a chemical trade journal 6 fouled this up into ‘power is knowledge’, an absurd – indeed, obscene – falsity. 

These examples remind us that the verb ‘is’ has, like any other verb, a subject and a predicate; but it is seldom noted that this verb has two entirely different meanings. A person whose native language is English may require some effort to see the different meanings in the statements: ‘The room is noisy’ and ‘There is noise in the room’. But in Turkish these meanings are rendered by different words, which makes the distinction so clear that a visitor 
正如我们所看到的，用通用的语言 - 甚至在数学教科书中 - 我们已经学会了把意思的细微差别读入到确切的语句中，直到这样的例子被指出为止。我们把“A是B”解释为首先是A存在的一个大前提，其余的声明被理解为以这个前提为条件。换句话说，在普通语法中，动词“是”意味着主体和客体之间的区分，符号“=”在形式逻辑或传统数学中不具有。 （然而，在计算机语言中，我们遇到类似'J = J + 1'这样的陈述，每个人似乎都明白这一点，但是'='符号现在已经获得了这种暗示的区分。

另一个有趣的例子是古老的格言“知识就是力量”，这是一个非常有说服力的事实，无论是在人际关系还是热力学方面。一位化学商业杂志的广告作者6把这个问题搞得“权力就是知识”，这是一个荒谬的事情，确实是淫秽的。

这些例子提醒我们，动词“是”和其他任何动词一样，有一个主语和一个谓语;但很少注意到这个动词有两个完全不同的含义。一个母语是英语的人可能需要付出一些努力才能看到​​陈述中的不同含义：“房间很吵”和“房间里有噪音”。但在土耳其语中，这些意思是用不同的词语表达的，这使得这种区分如此清晰以至于访客

注6 LC-CG Magazine, March 1988, p. 211.

who uses the wrong word will not be understood. The latter statement is ontological, assert- ing the physical existence of something, while the former is epistemological, expressing only the speaker’s personal perception. 

Common language – or, at least, the English language – has an almost universal tendency to disguise epistemological statements by putting them into a grammatical form which suggests to the unwary an ontological statement. A major source of error in current probability theory arises from an unthinking failure to perceive this. To interpret the first kind of statement in the ontological sense is to assert that one’s own private thoughts and sensations are realities existing externally in Nature. We call this the ‘mind projection fallacy’, and note the trouble it causes many times in what follows. But this trouble is hardly confined to prob- ability theory; as soon as it is pointed out, it becomes evident that much of the discourse of philosophers and Gestalt psychologists, and the attempts of physicists to explain quantum theory, are reduced to nonsense by the author falling repeatedly into the mind projection fallacy. 

These examples illustrate the care that is needed when we try to translate the complex statements of common language into the simpler statements of formal logic. Of course, common language is often less precise than we should want in formal logic. But everybody expects this and is on the lookout for it, so it is less dangerous.
谁使用错误的词将不被理解。后一种说法是本体论的，主张某物的物理存在，而前者是认识论的，只表达说话者的个人认知。

通用的语言 - 或者至少是英语 - 几乎具有普遍的倾向，通过将认识论的言语置于一种语言形式中来掩盖认识论的陈述，这种形式暗示了一种本意的陈述。当前概率论中的一个主要误差来源于不可思议的失败。解释本体论意义上的第一种说法就是断言自己的私人思想和感受是自然界存在的外在现实。我们称之为“思维预测谬误”，并注意其后面多次引起的麻烦。但是这个问题并不局限于概率论，一旦被指出，很明显，哲学家和格式塔心理学家的许多话语以及物理学家解释量子理论的尝试，都被作者一再堕入思维预测的谬误而沦为废话。

这些例子说明了当我们试图将通用语言的复杂语句翻译成形式逻辑的简单陈述时所需要的谨慎。当然，在形式逻辑中，通用语言往往不如我们想要的那么精确。但是大家都期待这一点，并且正在寻找它，所以它不那么危险。

It is too much to expect that our robot will grasp all the subtle nuances of common language, which a human spends perhaps 20 years acquiring. In this respect, our robot will remain like a small child – it interprets all statements literally and blurts out the truth without thought of whom this may offend. 

It is unclear to the writer how difficult – and even less clear how desirable – it would be to design a newer model robot with the ability to recognize these finer shades of meaning. Of course, the question of principle is disposed of at once by the existence of the human brain, which does this. But, in practice, von Neumann’s principle applies; a robot designed by us cannot do it until someone develops a theory of ‘nuance recognition’, which reduces the process to a definitely prescribed set of operations. This we gladly leave to others. 

In any event, our present model robot is quite literally real, because today it is almost universally true that any nontrivial probability evaluation is performed by a computer. The person who programmed that computer was necessarily, whether or not they thought of it that way, designing part of the brain of a robot according to some preconceived notion of how the robot should behave. But very few of the computer programs now in use satisfy all our desiderata; indeed, most are intuitive ad hoc procedures that were not chosen with any well-defined desiderata at all in mind. 

Any such adhockery is presumably usable within some special area of application – that was the criterion for choosing it – but as the proofs of Chapter 2 will show, any adhockery which conflicts with the rules of probability theory must generate demonstrable inconsistencies when we try to apply it beyond some restricted area. Our aim is to avoid this by developing the general principles of inference once and for all, directly from the requirement of consistency, and in a form applicable to any problem of plausible inference that is formulated in a sufficiently unambiguous way.
期望我们的机器人能够掌握所有人们花费20年时间获得的共同语言的细微差别，实在太多了。在这方面，我们的机器人将保持像一个小孩 - 它从字面上解释所有的陈述，脱口而出，而不会想到这可能会冒犯谁。

作者不清楚有多么困难 - 甚至不太清楚多么合意 - 设计一个能够识别这些更精细的意义的新型模型机器人将是多么的不可思议。当然，原则问题是由人脑的存在立即处理的，这是这样做的。但是，在实践中，冯·诺依曼的原则是适用的;一个由我们设计的机器人，直到有人形成“细微差别识别”的理论才能做到，这个理论将过程简化为一个明确规定的操作。我们很乐意留给别人。

无论如何，我们现在的模型机器人是完全真实的，因为今天几乎所有的计算机都会进行非平凡的概率评估。对这台计算机进行编程的人，无论他们是否这样想，都必须根据机器人应该如何表现的一些先入为主的概念来设计机器人的大脑的一部分。但现在正在使用的电脑程序中很少有满足我们所有的需求;事实上，大多数是直觉的特设程序，没有任何明确的要求被选中。

任何这样的暗示都可以用在某个特定的应用领域 - 这是选择它的标准 - 但是正如第2章的证明所显示的那样，任何与概率论的规则相冲突的东西，当我们尝试应用时，必然会产生明显的不一致它超出了一些禁区。我们的目的是通过直接从一致性的要求和适用于以足够明确的方式制定的任何可信的推论问题的形式，一劳永逸地发展一般推理原则来避免这种情况。

** 1.8.2 Nitpicking
As is apparent from the above, in the present work we use the term ‘Boolean algebra’ in its long-established meaning as referring to two-valued logic in which symbols like ‘A’ stand for propositions. A compulsive nitpicker has complained to us that some mathematicians have used the term in a slightly different meaning, in which ‘A’ could refer to a class of propositions. But the two usages are not in conflict; we recognize the broader meaning, but just find no reason to avail ourselves of it. 

The set of rules and symbols that we have called ‘Boolean algebra’ is sometimes called ‘the propositional calculus’. The term seems to be used only for the purpose of adding that we need also another set of rules and symbols called ‘the predicate calculus’. However, these new symbols prove to be only abbreviations for short and familiar phrases. The ‘universal quantifier’ is only an abbreviation for ‘for all’; the ‘existential quantifier’ is an abbreviation for ‘there is a’. If we merely write our statements in plain English, we are using automatically all of the predicate calculus that we need for our purposes, and doing it more intelligibly. 

The validity of the second strong syllogism (in two-valued logic) is sometimes questioned. However, it appears that in current mathematics it is still considered valid reasoning to say that a supposed theorem is disproved by exhibiting a counterexample, that a set of statements is considered inconsistent if we can derive a contradiction from them, and that a proposition can be established by reductio ad absurdum, deriving a contradiction from its denial. This is enough for us; we are quite content to follow this long tradition. Our feeling of security in this stance comes from the conviction that, while logic may move forward in the future, it can hardly move backward. A new logic might lead to new results about which Aristotelian logic has nothing to say; indeed, that is just what we are trying to create here. But surely, if a new logic was found to conflict with Aristotelian logic in an area where Aristotelian logic is applicable, we would consider that a fatal objection to the new logic. 
从上面可以明显看出，在目前的工作中，我们使用术语“布尔代数”作为指称“A”这样的符号代表命题的二值逻辑。强迫性的挑剔者向我们抱怨说，一些数学家用这个术语的含义略有不同，其中'A'可以指一类命题。但两种用法并不冲突，我们承认更广泛的含义，但没有理由利用它。

我们称之为“布尔代数”的一套规则和符号有时被称为“命题演算”。这个词似乎只是为了补充说，我们还需要另一套叫做“谓词演算”的规则和符号。但是，这些新的符号被证明只是简短和熟悉的短语的缩写。 “通用量词”只是“所有”的缩写。 “存在量词”是“有一个”的缩写。如果我们仅仅用简单的英语来写我们的陈述，那么我们就会自动使用我们所需要的所有谓词演算，并且更加可理解地去做。

第二个强三段论（二值逻辑）的有效性有时受到质疑。然而，在目前的数学中，似乎仍然认为通过展示一个反例证明了一个假定的定理是错误的，如果我们能够从它们中推导出一个矛盾，那么一组陈述被认为是不一致的，而且一个命题可以是通过简化荒诞而成立，从否定中产生矛盾。这对我们来说已经足够了。我们很满足于遵循这个悠久的传统。我们这种立场的安全感来源于这样的信念，即虽然逻辑可能在未来前进，但它不能倒退。一个新的逻辑可能会导致关于哪个亚里士多德逻辑无话可说的新结果;事实上，这正是我们正在努力创造的。但是，当然，如果在亚里士多德逻辑适用的领域发现新的逻辑与亚里士多德逻辑相冲突，那么我们就会认为这是对新逻辑的一个致命的反对。

Therefore, to those who feel confined by two-valued deductive logic, we can say only: ‘By all means, investigate other possibilities if you wish to; and please let us know about it as soon as you have found a new result that was not contained in two-valued logic or our extension of it, and is useful in scientific inference.’ Actually, there are many different and mutually inconsistent multiple-valued logics already in the literature. But in Appendix A we adduce arguments which suggest that they can have no useful content that is not already in two-valued logic; that is, that an n-valued logic applied to one set of propositions is either equivalent to a two-valued logic applied to an enlarged set, or else it contains internal inconsistencies. 

Our experience is consistent with this conjecture; in practice, multiple-valued logics seem to be used not to find new useful results, but rather in attempts to remove supposed difficulties with two-valued logic, particularly in quantum theory, fuzzy sets, and artificial intelligence. But on closer study, all such difficulties known to us have proved to be only examples of the mind projection fallacy, calling for direct revision of the concepts rather than a new logic. 
因此，对那些被二值演绎逻辑限制的人来说，我们只能说：“如果你愿意的话，一定要调查其他的可能性;只要你找到一个没有包含在二值逻辑中的新结果或者我们的扩展，并且对科学推理有用，请告诉我们“实际上，存在着许多不同的，相互矛盾的多元逻辑，价值逻辑已经在文献中。但是在附录A中，我们提出了一些论点，认为它们没有有用的内容，而这些内容还不是双值逻辑;也就是说，应用于一组命题的n值逻辑要么等同于应用于扩大集的二值逻辑，要么包含内部不一致。

我们的经验是符合这个猜想的;在实践中，多值逻辑似乎不是用来找到新的有用结果，而是试图用二值逻辑消除所谓的困难，特别是在量子理论，模糊集合和人工智能方面。但仔细研究一下，我们所知道的所有这些困难，已经被证明只是心灵预测谬误的一个例子，要求直接修改概念，而不是一个新的逻辑。
