* 5 概率理论的怪用

I.J.Good (1950)展示了我们能怎样用概率理论倒推我们自己对命题的相信程度。比如，我们对超能力感知的相信程度如何？

** 5.1特异功能

你会分配给史密斯先生拥有完善的超感官的假设概率是什么
知觉？更具体来说，他能够正确的哪个号码每次都猜
写下来。如果说零是太教条。根据我们的理论，这意味着我们
永远不会让机器人的心灵受到任何证据量来改变，
我们真的不希望出现这种情况。但是，在我们的信仰的力量像一个命题
这个？

我们的大脑工作得太多这种机器人的工作方式，但我们有一个直观的感受
对于合理性，只有当它不是在0 dB太远。我们得到相当德无限感情
东西极有可能是这样或小于可能是让更多的。因此，关键是想象
一个实验。需要多少证据带上你的信仰状态最长的地方
在那里你觉得很困惑和不确定呢？不，你相信的地方
它 - 这将冲过关口，并再次我们会失去我们的分辨能力。多少
证据将其带上你刚起来的地步，你开始考虑
可能严重？
因此，我们认为史密斯先生，谁说，他有超感知觉（ESP），以及我们将
从一一些数字写下来到十的一张纸，让他猜哪
数字我们已经写了下来。我们将采取通常的预防措施，以确保对其他
网络连接方式nding出来。如果他正确地猜测的第一个号码，当然我们都会说'你
一个很幸运的人，但我不相信你有ESP“。如果他猜对两个号码
正确的话，我们还是会说'你是一个很幸运的人，但我还是不相信你有ESP“

** 5.2

** 5.3趋于一致和产生分歧的观点

假设有A先生和B先生两个人，他们对于同一问题有两种不同的观点（源于他们有不同的先验信息），发表对某个具有争议命题S真假的看法。现在我们给他们两个一些新的信息（或数据），用表示。这些信息一些支持命题S，一些却不支持。当n逐渐增大时，他们的总信息会变得几乎相同，所以我们可能会期望他们关于命题S的意见会趋于一致。确实，一些学者认为这个结果太明显以致于认为其没必要进行精确的描述，然而，Howson & Urbach (1989, p.290)强调其应该被描述清楚。

尽管如此，让我们看一下概率理论能否让次现象重现。令、分别表示两人的先验信息，同时让A先生在初始时为一个相信者，而B先生为一个怀疑者：
，
在得到消息D之后，他们的后验概率变为


如果D支持命题S，则A先生总是会认为命题S几乎为真，我们得到，同时得到：

信息D不会对A先生的意见产生任何明显的影响。但现在个人会认为如果B先生非常理智，他必然会认为，同时得到

B先生的意见会向A先生的意见方向改变。同理，如果D对命题S不利，个人会认为如果B先生的意见几乎不被其改变，而A先生的意见会向B先生的意见方向发生改变。从这一点来说，我们可以得出：不管新信息D是什么性质的，其会使得持不同意见的人们趋于一致，其存在的条件是：

虽然此结论在特殊情况下可以被证实，但在一般情况下是不正确的。

是否存在一些其他诸如的“意见接近程度”的测度，针对发生分歧的意见可被证明来作为一般的定理?不仅这个是可能的；概率理论给出预期结果的失败告诉我们意见趋于一致并不是一个普通的现象。对于代理人和人类来说，谁的推理与第一章中一致性愿景相一致，一些更细致精巧的东西需要用上。

确实，在实践中我们发现这种趋于一致的意见常常是发生在小孩子们中；对于成人这也会发生但不总是发生。例如，新的实验证据会使得科学家们对现象的解释趋于一致并达成共识。

然后，也许人们会这样想，公共问题的公开讨论会给他们带来一个一般性的共识。于此相反，我们反复发现，当一些有争议的问题被讨论之后许多年，社会会被分化为两种观点截然相反的阵营；几乎不可能找到任何一个可以保持中立的人。折磨法国人民20年的法国德雷福斯案件（Dreyfus affair）是最值得书写的案例之一(Bredin, 1986)。今天，诸如核能源、堕胎和罪犯公众等问题也会遇到同样的境况。新信息被同时提供给不同的人群可能会导致意见的趋同；但它也可能会导致意见的分歧。

在可控条件相对较好的心理学实验中，这种分歧现象也被观察到。一些学者得出结论认为人们推理方式的本质不理性；个人偏见可能会被具有相反作用的新消息所强化。Kahneman & Tversky (1972)从心理学实验中得到相反的结论，并认为这些结论和贝叶斯方法相悖。

但是现在，上面提到的超感应能力例子中，概率理论是否也可以对分歧做出解释，而且表明人们也许是贝叶斯理性思考的（也就是说，以一种与他们先验信息和后验信念相一致的方式）。超感应能力例子的关键是我们新信息不是

有些超感应能力研究者宣称命题S是真的。但是如果我们对命题S的先验概率低于我们被骗的先验概率，当听到如此声明之后，会对我们的现有信念与宣称者的本意产生反方向的作用。

对于科学和政治同样会出现此类情形；一个科学家得到的新信息，并不是实验者足够消除误差，所真正获得的结果。而只是，他的一些同仁所宣称他做到了那一点。我们从电视晚间新闻所获得的信息并不是确定的事件以非常确定的方式真实发生的；它们只是一些新闻报道者宣称事情确实发生了1。

科学家们能够很快达成意见统一，原因是我们相信做实验的同仁具有很高的诚信和对误差很敏锐的排除。同时，这个观点是可以被事实所支持的，因为，成百上千的新实验在一个月被报道，但是十年也就有一次实验报道后来被证明是错误的。所以，科学家们关于欺骗的先验概率是很低的；就像相信小孩子不会骗人一样，我们相信实验者们所告诉我们的。

政治上，我们面对一个很不同的环境。不仅是我们会怀疑政治家的承诺，而且很少人会相信新闻报道者会将经济、社会和政治话题报道的真实和客观。事实表明所有的新闻都是人为选择或扭曲了的，不仅不去报道事实，却灌输我们报道者的社会政治观点。同时这个观点是可以被报道者自己产品的内部证据的大量事实所支持，如每一个词句的选择和声调的变化都一成不变的偏向一个方向。

不仅是对政治演说和新闻报道，对于所有我们能够寻求政治方面事情的地方，我们都会碰到同样的墙壁；我们不能信任任何对我们说是真的人，因为我们觉察到，所有想谈论它的不是出于自私的驱使就是出于理想主义。对于政治类事件，不管信息的来源是什么，我们对于欺骗的先验信息都是很高的。这个是否够足以阻止我们的意见达成一致，然而，这并不明显的。

带着这个思考，我们来重新审视一下概率理论的方程。为了比较A先生和B先生的推理过程，我们将(5.17)的贝叶斯定理写成对数形式

上式可被写做简单标识符的形式

需要注意，(5.22)与第四章中的对数几率方程并不同，后者也可以用同样的标识符来书写。在第四章，我们在给定相同的先验信息下比较不同的假设，同时一些因素被忽略了。这里我们考虑的是一个复合的假设S，在不同的先验信息下，那些因素不可以被忽略了，所以，项是不同的。

在上面分析中，我们假设A先生是一个相信者，所以。然后，基于对数量纲，明显的有，A先生和B先生的观点会趋于预期，(5.22)式左边会单调的趋于0（也就是说，A先生仍然是一个比B先生相信的相信者）如果满足

他们意见会单调的分歧，如果满足

但是，他们反转得达成一致（B先生变得比A先生更相信），如果满足

他们意见会向发生分歧反转，如果满足

所以，概率理论原则上是允许新信息D对两人之间的相对信念产生各种可能的影响。
	但是，或许还有其他没有提到的限制条件，会是的那些结果不能实现；我们能否给出所有四种行为的特定的和实际的例子？让我们通过以下的情形，只是考察单调趋于一致和产生分歧，反转的清醒的类似分析留给读者去作为练习。

	新信息D：“N先生在电视节目上宣称一种普通的药物是不安全的”，还有三个观众A先生、B先生和C先生看到该信息。他们的先验概率为药物安全的概率，分别是；起初，A先生和C先生都是相信药物是安全的，而B先生是不相信的。

	然而，三人对新信息D的解读并不相同，因为他们对于N先生的可靠性持有不同的看法。他们都同意，如果药物确实证明是不安全的，N先生就会出来喊说。也就是说，他们三人的概率是。然而，A先生相信他是诚实的，但C先生不相信。如果药物是安全的，N先生会说药物是不安全的概率分别是。

	应用贝叶斯定理，然后应用积法则和和法则将分子展开，我们得到他们认为药物安全的后验概率分别是。将他们推理的过程通俗得描述如下：

A
B
C

A先生与B先生观点的趋于一致的方式是(5.20)中的推理方式，因为二人都会相信N先生在一定程度上是诚实的。但是，A先生与C先生观点的分歧时因为他们对欺骗的先验概率是截然不同的。所以，产生分歧的一个原因并不仅仅是很大的欺骗先验概率，而是他们对于不同的人而表现出很大的不同。
	然而，这并不是唯一产生分歧的原因。为了说明这一点，我们给出X先生与Y先生，他们都同意N先生的判断：
，
如果，则他们会认为N先生更可能会说实话。但是，二人对于药物安全的先验概率是不同的：
，
则他们的后验概率是：
，
我们从上式不仅可以看出，他们的观点会一直朝同一个方向变化，而且变化的量也都是以同样的证据量变化：


这也就意味着，基于概率量，他们既可以趋于一致也可以产生分歧，见练习5.2。这些方程和第四章里的有序楔子检验相近，但这里却有不同的含义。如果，则二人会认为N先生没有说服力，且二人的观点不会被他的说辞所左右；如果，二人不相信N先生说的，以致于二人的观点会朝着他观点的反方向走。的确，如果，则；二人会认为他肯定在说谎，所以二人都会完全相信药物是安全的：，并于二人的先验概率相互独立。

我们看到观点的分歧可以被概率理论的逻辑来解释，同时当人们有不同的先验概率时，其也是可以被预期到的。但是，是什么地方让我们进行(5.20)那样的推理呢？我们犯了一种不易察觉的主观谬误，认为‘D支持S’的关系是D和S的性质。我们需要认识到他的相对性；D是否支持S取决于我们的先验信息。同样的D，对于某个人可能支持S，对于另一个人也可能反对S。当我们认识到这一点时，我们也就不会再期望像(5.20)那样的作为一般情形了。错误是普遍的；我们将要看到5.7部分中它的另一个例子。
	Kahneman & Tversky (1972)宣称我们并不是贝叶斯的，因为在心理学测验中人们的行为往往与贝叶斯定理相左。然而，这个说法与刚刚我们强调的那些观点是不同的。我们认为，人们的推理遵循一种更为复杂的贝叶斯推理，而不是他们二人所想的那样。
	类似的情形即使在逻辑推理中也可以找到，进一步加强了该个结论的正确性。Wason & Johnson-Laird (1972)报告的心理学实验中主体犯的系统性错误，其在简单测试中倾向于用单一的演绎推理。看起来就像，当被问及测试‘A意味着B’，他们较强的倾向的认为其等同于‘B意味着A’而不是‘非B意味着非A’。即使对于专业的逻辑学家也可能以这样的形式出错2。
	足够奇怪的是，此错误的本质意味着将趋向于贝叶斯学派，而反对Kahneman–Tversky的结论。所以，如果对于某些X情形下，A支持B，，则贝叶斯定理表明B支持A在同样的情形下：。但是它也表明，与论断相符。在极限中，贝叶斯定理没有给出，但是给出了，与在第二章中提到的论断是不违背的。
	分阶段心理学测试中的犯错，可能仅仅意味着主体和心理学家在达到不同的目的；实验主体们看到测试是低级愚蠢的，而且不想话费一点心思来回答问题，或者甚至会想心理学家们应该会很乐意看到他们给出错误的回答。主体们处在逻辑上相当的条件，此时的条件与他们的利益有较强关联（比如，避免较严重的事故伤害），他们可能会比较认真的对待。实际上，有个更坚实的基础-达尔文的自然选择-是的我们以贝叶斯的方式来推理。

** 5.4 视觉感知-进化为贝叶斯形态?

另一类心理的实验和这个话题非常契合。20世纪早期，Adelbert Ames Jr是达特茅斯学院的生理光学教授。他发明了一个精巧的实验，该实验骗人‘看到’一些和现实很不同的事物-人们对事物的大小、形状和距离做出错误判断。一些人将此作为无聊的视觉幻像，但也有一些人-比较有名的包括Alfred North Whitehead 和 Albert Einstein-他们看到这些展示，看到了现象的重要本性揭示了让人吃惊的视觉感知原理3。普林斯顿大学的Hadley Cantril教授继续了他的研究，并对那些现象进行了讨论并给出了影像展示(Cantril, 1950)。

大脑关于世界的确定前提，是在婴儿期的发展的，并建立在所有获得感知基础之上的。比如，距离越近的物体看起来越大，有更大的视差角度，同时阻挡了在同一条视线上的物体；一条直线从任何方向来看都是直的，等等。这些前提假设被融入到艺术家的透镜原理和三维电脑图形设计中去。我们固守那些，是因为他们已经比较成功的将多种经验关了起来。我们不会摒弃那些一直很好用的成功假设；唯一可以让我们改变那些假设的方式是，让我们处在一种那些假设都不起作用的情景。比如，在那间艾姆斯小屋中，我们所感知的大小和距离的比例发生了错误关联，使得一个儿童从屋子内走过时的身高放大了两倍。

从那些实验中我们得到的一般结论是，相对于我们这一代的“绝对主义者”，下一代的人会有所发现而不再会那么惊讶。看到的并不直接就是事实，就像我们经常会伪装自己那样。恰恰相反:看到的是不完全信息的一种推测，与我们现在此刻学习中的推测本质上是一样的。我们通过眼睛所得到的信息不足以让我们确定眼前有‘真的东西’在那。Ames 和 Cantrell的实验所揭示的视觉感知错误并不是眼睛的水晶体、视网膜或视觉神经出现了问题；而是大脑中之后推理过程的反应，此时接受的新信息与先验信息不不一致了。那是到了我们不得不去考虑其他可能假设的时候了；哦，那才是我们看到的啊。我们期望，这些例子的细节分析可以表明贝叶斯推理很好的一致性，就像在我们的超能力感知和意见分歧的例子中的一样。

视觉感知的积极研究还在继续，同时大量的新知识会逐渐积累，但是我们几乎还是不明确这些在神经层面是如何完成的。工作者们指出其中似乎没有任何组织原则；我们设想贝叶斯推理原则是否可以作为一个开始。我们并不期望达尔文主义的自然进化选择可以得到如此的结果；毕竟，任何与贝叶斯推理想矛盾的推理形式都会使得生物处于生存劣势。事实上，就像我们很早之前提到的(Jaynes, 1957b)，基于考克斯定理的视角，否定我们以贝叶斯式的方式推理就是断言我们推理是刻意不一致的方式；我们发现这是难以让人相信的。大体上可以推测，基于同样的推理，人类和动物感知的许多其他例子会被找到，来作为推理的高级组织原则来遵循贝叶斯推理方式。带着这个思考，我们来看一个历史上非常有名的例子。
