* 序
本书是给那些已经对应用数学比较熟悉的读者，包括高年级大学生水平或者是更高水平的读者，和一些领域的的读者，诸如物理学、化学、生物学、地理学、医学、经济学、社会学、工程学、运筹学等等需要推理的领域(注1)。没有必要对概率与统计有个提前的熟悉；实际上，在此领域的一些无知可能会更好些，因为这样可以会更容易‘抹掉’那部分知识。

我们关注的是概率理论和涉及概率的传统数学，但是，现在看来已经超出了标准教程的内容范围。每一章节的第一部分会有一个‘新’的结果（即以前没有发表的结果），我们认为该结果可能会被发现是有趣和有用的。我们的许多应用超出了作为教程的传统概率理论。但是我们认为那些应用结果会不言自明，同时和本书所阐释的的理论一样，会在未来变成的传统概率理论。

注1:  所谓‘推理’简单的理解是：当手上掌握足够的信息时，应用演绎推理；归纳或合情推理是在必要信息不足以得到时用到-实际遇到的问题反而常常是这一种。但是，如果问题能够用演绎推理解决，那么概率理论就不需要了；也就是说，我们的主题是信息不完全下的最优处置。
** 历史

本书现在的形式是多年来不断演变的结果。我对概率理论的兴趣是被Harold Jeffreys (1939)的作品所激发的，同时通过对其作品的阅读意识到，他的观点使得所有理论物理里的问题表现出一种非常不同的视角。但是之后，很快且陆续的发现了R. T. Cox (1946)、Shannon (1948) 和P olya (1954)的著作，打开了一个全新的思路，并一直在我脑海里占据了差不多40年。在这个更大很多和永恒的广义理性思维世界里，理论物理现有的问题看起来仅仅是短期利益的细节。

本书写作的真正开始是作为1956年在斯坦福大学几场讲座的记录，其阐述了George P´olya新颖而令人兴奋的著作‘数学与合情推理’。他将我们直觉‘常识’剖析为一组基础的定性愿景，同时提到数学奖们早已用他们来指导早期的发现，这还需要进一步找到严格的证明。结果很像是James Bernoulli的《推理艺术》中的，后来在18世纪被Laplace进一步分析；但是P´olya认为这些很像的地方只是定性的。

然而，P´olya将这些定性的部分用完整和完备的细节来描述，像是在建议到一定还有更多的相同之处。幸运的是，R. T. Cox的一致性定理足以弥补；当有人将P´olya的定性条件加上时，结果就是一个证明：如果合情度可以用实数来表示，则有唯一确定的一组定性准则来用作行为推段。也就是说，任何其他的准则只要其结果与其冲突，就势必会违背基本的（同时几乎难以摆脱）理性或一致性的愿景。

但是最终的结果只是概率理论的一般准则，切早已被Daniel Bernoulli 和 Laplace给出；那为什么还这么大惊小怪呢？重要的新特点是那些准则现在被看作广义逻辑里的独一无二的正确准则，使得‘几率’和‘随机变量’无容身之地；所以，他们将比20世纪早期发展的所谓传统概率理论的应用范围广很多。结果，概率理论和统计推断之间被想象的区别消失了，同时得到的结果不仅逻辑统一而简单，而且在应用上也更灵活而强大的多。

在作者的演讲中强调的是P´olya观点的定量形式，所以它可以被用于科学推理的一般问题，几乎所有的科学推理都是源于不完全信息，而不是‘随机’。有关George Polya的一些个人缅怀和那些作品的涉及会在第五章见到。

应用的工作一旦开展，Harold Jeffreys的著作重新变成了关注的中心。Harold Jeffreys靠直觉看的很远而且似乎预见了我所遇到的所有问题。我欠他的，也只能部分的用这本书来为他的记忆作为弥补。关于他作品的进一步讨论和其对我个人的影响，分散在书中的好几个章节。

在1957至1970年间，在许多其他高校和研究所(注2)反复做了这个演讲报告，内容也随着稳步得增加。在此过程中，变得越来越明显地的是，传统的统计推断中突出的难题被容易理解和克服。但是，现在替代他们的准则变为非常精细得概念化，同时需要一些更深层次的思考来看看如何将他们准确应用。过去曾经导致反对Laplace工作的难题，后来看上去不过是错误应用，原因是错误的定义问题或青睐琐碎而不着边际信息的说服力，一旦意识到这一点也就很容纠正了。我们的‘延伸的逻辑’方法和常用的‘随机变量’方法之间的种种关系，以许多不同的形式几乎出现在所有章节。

最终，内容积累到简短的几个演讲报告远远不能将其呈现，同时书也超出了教学的范围；伴随着旧问题的不断解决，我们发现自己已经掌握了一个对付新问题的强有力的工具。自1970年以来，内容增加的速度与其同步，但是增加的确实作者和同事们的研究工作。我们期望最终的结果可以保持原始混合体的状态，既可以作为教科书也可以作为参考文献；事实上，好几代的学生已经将早期的版本携上并教给他们自己的学生了。

回顾以上部分，我们反复说Charles Darwin在他《物种起源》的前言写的一句话：‘我希望加入这些个人信息的我可以被原谅，因为我给他们证明了我没有草率的决定’。但是，可能有人这么想，30年前的作品到了今天将被废弃。庆幸的是，Jeffreys、P´olya和Cox的著作是基础而永恒的，他们的真理不会改变而且会随时间而壮大。他们对推理本质的感知，也仅仅是30年前的好奇而已，其在现如今半数的科学领域将是非常重要的；同时，它在其后100年内的所有领域将变得格外重要。

注2: 前面章节里的一些材料，在1958年通过Socony-Mobil石油公司，作为其一系列的在理论和应用科学讨论会上的四号作品。

** 根基

许多年经验中成百上千实际问题的应用，使我们对概率理论根基的看法变得比较复杂，其不是用‘支持这个’和‘反对那个’的简单术语就可以描述的。比如，这里的概率系统和Kolmogorov的并没有太多的不同，不仅体现在哲学意义上还是目的上。我们所考虑的半个概率理论是现如今应用所需要的-通过对不完全信息的逻辑分析而赋予概率的准则-其并没有出现在Kolmogorov的系统。

还有，结果我们惊讶得发现我们是同意Kolmogorov的，同时在几乎所有的技术性问题上，我们是反对其批评者的。就如在附录A中所提到的，他的每一个定理基于实际应用的目的，都被证明是可以从一致性和合理性的P´olya–Cox愿景得到的。简言之，我们认为我们的概率系统与Kolmogorov的不冲突；更确切的说，我们在寻找一个更深的逻辑基础，使得其延伸方向上可以满足现有应用的需要。对此的努力使许多问题得到解决，而且即使那些依然未解决的问题看上去也是可以被预见到的：正在开辟新的领域。

另一个例子，似乎对于所有人第一眼看到我们的系统，会认为和de Finetti的概率系统非常接近。确实，笔者也曾经相信这一点。然而，结果我们发现，令我们自己惊讶的是只有很少的一点哲学上的苟同；许多技术层面的我们是有很多不同的。我们觉得他处理无限集合的方式打开了潘多拉的宝盒，是无用而显得不必要的矛盾；第15章中的不可积和有限可加是其例子。

	无限集合的悖论依然变为今天正在散布的一种病态感染，其威胁到了概率理论的生命，而正需要一个直接的外科移除手术。在我们的系统里，诸如此类的悖论是被自动免疫的；他们不会从我们基本准则的正确应用里跑出来，因为那些准则只允许有限集合和从有限集合极限里得来的无限集合，这些集合满足被定义良好与表现良好。这些悖论是源于：一，还没有为定义性质而详细说明取极限的过程，就直接跳到无限集合；二是所问到问题的答案是基于取极限的方式。

	举个例子，问题“一个整数是偶数的概率为？”在(0,1)之间可能会有任意的答案，这取决于用于定义整数集合的取极限过程（就像条件收敛序列可以收敛到任何我们想要的数，取决于我们组织各项的顺序）。

	在我们看来，无穷集合不能被说成是处理任何存在和数学性质的-至少在概率上不能-除非我们能搞清楚从有限集合所得出的极限过程。换句话说，我们在Gauss、Kronecker和Poincar´e的旗帜下航行，而不是在Cantor、Hilbert和Bourbaki的旗帜下。我们希望那些被此所促动的读者可以研究下数学家Morris Kline (1980)对Bourbaki追随者的控诉，同时能够坚持与我们并肩去发现我们方法的好处。这样的例子几乎出现在每一个章节。

** 对比

许多年来，频率学派和贝叶斯学派的推理方法之间有着争议，笔者自己也曾经作为贝叶斯学派一方的明确支持者。早期的一本书中(Jaynes, 1983)对1981年前的此类事情作了记录。在过去的工作中，两方都有太倾向于在哲学和意识形态上争执。我们现在可以让自己些许的避开那些了，因为我们不再需要进行那样的争论了，这些得益于最近的研究工作。我们现在已经掌握了被证明的定理和大量数字例子的解决。于是，贝叶斯方法的优越性在一百分不同的领域被事实所证明着。某些人可以用哲学来争辩；却很难用计算输出结果来争辩，因为这些结果会对我们说：不管你的哲学观，这就是事实中的表现。不管是在什么时候，最终结果中只要是有本质的不同，我们都会将其细节指出来。结果是，我们继续为贝叶斯学派的方法力争；但是，请读者注意的是，我们的争辩不是声明一个哲学上或意识上的观点，而是引用大量的事实。

然而，既不是贝叶斯学派也不是频率学派是普遍适用的，所以在目前和更一般性的研究工作中，我们是从一个更广的视角来看的。我们的主题很简单：概率理论作为延伸的逻辑。认识中增加了新的认知：概率理论的数学准则不仅仅是计算随机变量频率的规则，而且也是进行任何类型推理的独一无二的一致性准则，同时更广义得，我们将它们一直用到最后。

实际上，所有的贝叶斯学派的计算被自动得囊括为我们准则的一种特例，而且所有的‘频率学派’的计算也一样。不仅如此，我们的基本准则比他们任意一个都要面广，而且在某些应用中我们的计算不能归到其中任何一个类型。

为了解释我们如今看到的这些情形：传统的频率学派的方法，只用了样本分布在一些简单而理想的抽样中，其是可用和管用的。然而，他们给出了最不可用的概率特例，因为给出的先验条件是很难在实际问题中遇到的。这类方法对于当下的科学是很不需要的。

不仅如此，‘频率学派’的方法没有提供需要的均值来消掉恼人参数，也没有将先验信息考虑进来，在必要和充分条件不存在情况下更没有办法用数据里的所有信息。他们缺失必要的理论准则，不得不使得一些人凭直觉来选择统计方法，而不是从概率理论中来。还没完的是，发明一些概率理论所不容的主观临时特定的工具（如无偏估计、可信区间和尾部面积的显著性检验）。每一个都是在很窄的范围内可用，但是如考克斯定理所保证的，这些临时特定的工具在一些极端情况被应用时，难免会产生不一致性和荒诞的结果，很多这样的例子我们在下面可以看到。

贝叶斯方法的使用纠正了上面的那些缺陷，足以称得上是定义良好的推理。就如Harold Jeffreys所描述的那样，它们具有优越的处理工具，能够不菲吹灰之力的解决频率学派所不能解决的问题。贝叶斯方法从容的设定最优参数和算法，同时考虑先验信息和给恼人参数留出余地。确切的说是，他们不是在极端情况下将其打掉，而是继续得到合理的结果。所以，贝叶斯方法是我们解决比用频率术语所能讨论的更复杂深渊的问题。我们的一个主要目的是给出，早已蕴藏在概率理论的简单和准则与积准则里的能量，是如何被揭示为延伸的逻辑，其不需要且没余地给任何的主观临时特定的工具。

在贝叶斯方法被使用之前，一个问题的研究超过‘探索阶段’之后就该由足够的结构来决定所有需要的工具了（模型、样本空间、假设空间、先验概率和样本分布）。超过原始探索阶段的几乎所有科学问题都需要推理，但是频率学派的前提是将其忽略的，而贝叶斯工具却没有。实际上，他们中的一些不会超出那些探索阶段。这个层面的问题需要从我们的不完全信息中直接获取更为原始意义的概率赋值。

为了达到这个目的，最大熵原理是至今最为合理的理论，他用于贝叶斯工具一样强大而丰富的分析工具，成为最为成熟的计算工具。为了应用最大熵原理，我们必须定义一个样本空间，但不需要任何模型或样本分布。最大熵帮我们从数据中创造了一个模型，该模型可通过许多不同的准则(注3)证明是最优的，以至于很难想象的出，会有人不用此来解决没有模型而只有样本空间的问题。

贝叶斯方法和最大熵原理在另一面也有所不同。两个过程都从进到里面的信息获得最优推段，但是我们可能挑其中一个模型来进行贝叶斯分析；这相当于表达一些关于所观察现象的先验知识，或者说是一些假设。通常，一些假设会超出数据里可直接察觉的，那时的我们就应该说那样的贝叶斯方法是（至少应该是）投机取巧的。如果额外的假设是真的，则期望贝叶斯的加过会改善最大熵；如果是错的，贝叶斯推断也就可能是错的。

另一方面，最大熵是一个非投机取巧的过程，意义上他并没有借助于获得的数据中的证据和样本空间以外的假设。于是，它只是预测观察到的事实（过去和现在观察的函数），而不是那些可能仅仅存在于我们想象中的参数值。理由可能是，当我们对粗糙数据之外的信息了解很少时，最大熵是合适的（最安全的）工具。最大熵是我们免于不基于数据就妄下结论。但是，当信息极端模糊时，可能很难给定合适的样本空间，同时个人可能会王是否可能存在其他比最大熵更一般的准则。这里有空间留给那些创新性思维。

目前，有许多重要且不可忽视的应用需要最大熵作为唯一的工具。书中的第二部分有对他们的详细介绍；通常，这些部分比第一部分的需要更多相关领域更多的专业知识，第一部分中的应用更基础一些。现今所知的所有统计力学都囊括在此了，比如，现今用到的很成功的最大熵谱分析和图像重构算法。然而，我们认为未来而这都会演化为贝叶斯相位，就像我们明白了使我们加入更多先验信息的合适模型和假设空间。

我们意识到有太多的理论点来解释，以致于我们不能够给出许多应用的数值例子。庆幸的是，《贝叶斯分析和参数估计》(Bretthorst, 1988)、《最大熵实践》(Buck and Macaulay, 1991)和《数据分析-贝叶斯手册》(Sivia, 1996)这三本新近的书，可以极大的弥补这些不足，同时也可以作为现有工作的补充。三本书的写作视角和本书的基本相同，给出了丰富的问题及相应的数值解决。当然，这些作品没有包括本书中所涉及的理论解释。同样，自1981年以来，每年MAXENT工作组的出版卷也包括很多各类不同的应用。

注3: 那些关系到有效信息的掌控：如，(1) 建立的模型是最简洁的，能偶捕捉到限制条件下所有的信息（第11章）；(2) 唯一的限制条件做为统计必要充分条件的模型（第8章）；(3) 如果被看做为了从新数据中进行后续的贝叶斯推理而构建的样本分布，后续推理用到的数据中测量误差的唯一性质，是那些关于包括先验分布的样本分布（第7章）。于是，形式主义自然将所有的信息考虑在内，但是却忽视了那些我们没有的信息。这和传统的方法截然相反，没有考虑信息方面的术语罢了，同时也与二者的愿景相背。

** 心理活动

有人可能早已从的例子中预见到，概率理论作为延伸逻辑重塑了许多人类心里活动的许多方面，有时令人惊讶，甚至有令人不安的细节。在第5章我们发现，我们的方程将说一个人真话且不被相信的的现象展示出来，甚至包括不信任者推理一致的现象。这些理论解释了为什么和在什么情况下这些现象会发生。

方程也重新解释了一个更复杂的现象，即观点的分歧现象。可能有人会认为公开讨论公共问题可能会使意见达成一致。相反的是，我们反复观察到，当某些有争议的问题被讨论之后的一些年之后，社会上的人会分化为两个观点截然相反的阵营；几乎不可能的发现任何人会保持中立态度。概率理论作为逻辑给出了两个人是如何在信息相同的条件下，逻辑会使得两人的观点想相反的方向发展，这些是一定要避免发生的。

在如上的一些方面，概率理论明确得告诉我们，当我们对那些我们还没有意识到但形成意识判断时，我们大脑是如何运作的。一些人可能对这些内容的揭示感到不舒服；其他一些人可能会看到他们将是心理学、社会学或道德研究的有用工具。

** 什么是‘安全的’？

我们在这里并不是只关心那些抽象的数学和逻辑问题。本书中一个主要的实用信息是，个人需要从给定数据中发掘先验信息对结论的巨大影响。近期许多被讨论的问题，诸如环境污染或食品添加剂的毒性，如果某人只是看到眼下的数据而忽视科学家给出的先验信息，其是很难做出理性判断的。这些会使得人们高估或低估危害程度。

一个常见的错误是，当判断无线电的影响或一些物质的毒性时，假设的是没有门限的线性反应明星（即量的比例低于不致病的水平）。假设对于重金属那样的有毒物（如水银，铅）没有门限效应，如果可以被移除，其被移除的速度将非常慢。但是对于所以人造的有机物（如糖精或甜味剂），有限速率的新陈代谢的存在意味着必然有一个有限的门限剂量，低于此剂量物质可以被分解、排除或很快的化学作用使得其不能致病。如果这不是真的，从我们在吃地所有东西的视角看，人类将不能存活至今。

确实的，我和你每一口的食物摄入，包括数十亿种复杂分子，他们的结构和物理作用未曾被确定，而且其中数百万的物质可能在大剂量时是有毒的。我们不能怀疑我们每天所摄入的数千物质是远比糖精要危险的，但是在剂量上市安全的，因为他们远低于各种毒性的门限。当今，除了普通的药物之外，只有很少的一部分物质，我们是知道其确切门限剂量的。

所以，此领域的推断应用应该不仅要估计反应曲线的斜率，还要去看是有没有门限存在的证据；如果有，去估计其剂量（安全的最大剂量）。例如，告诉我们糖的剂量超出平时剂量1000倍会导致癌症，此话不会影响我们食用它；实际上，必须达到公斤剂量才会检测到是够有致病作用，这个结论性的证据不是说不安全，而是说物质测试结果是安全的。类似过量的糖可能会更加危险，不仅会被检测到有危害的作用，而是肯定会使糖尿病患者直接死亡；然而没有一个人提议要去禁止食物中使用糖。

公斤剂量的作用无关紧要，是因为我们根本就不会摄入公斤剂量；在糖的替代品的例子中，一个重要的问题是：糖替代品毒性的门限是多少，还有对于糖来说，其相对的正常剂量是多少？如果糖替代品的很高，那么理性的结论可能是替代品实际上比糖作为食品添加剂要安全的多。为了用模型术语来分析某个数据，该模型不允许门限作用的可能，即使数据是好的，该预先判断问题的这种方式会导致错误的结果。如果我希望觉察此现象，必须用至少应该允许可能性存在的模型。

我之所以在序里强调这些，是因为此类错误的产生如今不仅会导致大量的经济浪费，而且还会对公众的健康和安全产生不必要的危害。社会只有有限的资源来解决此类问题，所以任何对想象危害的努力付出都意味着真的危害在悄无声息的逼近。甚至可能更糟糕的是，错误没有被当下可用的的数据分析过程所纠正；错误的前提被放入模型，不会再被怀疑且不能被任何新的数据所剔除。使用那些正确反应科学家的先验信息，且是关于此类机制有效的模型，能够减少此类蠢事在未来的发生。

如此的考量不仅是因为先验信息在推断中是重要的；科学本身的进步也是有风险的。为了看到这一点，点出下句的结果：我们坚持分析旧观点（也就是说，旧模型没有被质疑）的新数据不会是的我们跳出旧思维。然而，我们记录和分析很多数据，有可能只是反复同样的错误，错过了一些关键而重要的东西，这些东西是实验可以发现的。这就是忽略先验信息对我们所做的；没有用随机模型考虑硬币投掷的数据，才可能让我们去发现牛顿机械定律，而牛顿定律自己决定了那些数据。

当旧数据用心的思想观点来看时，会给我们一个完全不同的现象洞察；我们有一个令人印象深刻的例子，在核磁共振数据的贝叶斯谱分析中，数据使我们得到现象的准确定量测定，而这些用傅里叶变换分析数据是难以观察到的。当数据集合通过错误的假设被肢解处理后（或者，用常用的委婉语说叫过滤），其中重要的信息可能被不可逆的破坏了。就如一些人所认识到的那样，这些常常出现于经济计量学里传统方法的去趋势或季节调整。然而，如果旧的前提被完好无损的保留，旧数据集合可能在先验信息跟进时，会在有生之年有所绽放。

** 表达方式

第一部分，对原理和基础应用进行了阐述，大部分章节用一些篇幅对问题本质进行文字讨论来作为开头。这里我们尝试去解释看问题的有益方式，和解释过去错误的逻辑陷阱。我们才会转向数学，解决为此量身定做的一些问题，在那里读者可以直接用数学将其推广。在第二部分，对更多的应用进行了阐述，从开始就放在了数学上。

笔者从实践中习得，开始就必须重点强调问题的逻辑而不是数学，是非常有必要的。对于现在的学生来说，数学是简单的部分；一旦问题被简略为确定数学练习，大多数学生能轻易的将其解决和不停的拓展，而且不需要老师和教科书的帮助。概念相关的东西，即如何将现实问题和抽象数学建立最初的练习，使得他们迷惑如何和不确定如何去处理。

近代历史中描述了那些有足够勇气的人把自己的作品描述为‘严谨的’，却走向了衰落。所以，我们应该声明我们并没有心照不宣得给出错误论证。我们也是有意写给多数和各类型的读者，写给那些多数认为意义的清晰要比狭隘数学理解中的严谨更为重要。

将逻辑和清晰作为最重要的来强调，还有两个更为重要的原因。第一，任何争辩都不会比前提更有力。正如Harold Jeffreys所点到的，那些给数学严谨性施加最大压力的人只是那些对现实世界缺乏肯定理解的人，他们将自己的论证和非现实的假设练习起来，也将他们的关联给毁掉了。Jeffreys把这比作，通过将钢筋柱打进塑料来努力加固建筑。能给出为什么结果是正确的且使辩证直觉上清晰的辩证，比那些努力宣扬数学严谨而不能让人明白的辩证，是更可信的而且是更能在科学上站稳位置的。

第二，我们需要承认，在拥抱了无限集合理论的数学中，严谨并没有真正让人信服的标准。Morris Kline (1980, p. 351)的观点和Jeffreys的比喻类似：‘谁能够用包括无限集合或选择公理的理论设计一座大桥？而不会使得大桥塌掉？’。今天我们所具有的真正严谨是，有限整数的有限集合上基本算术的运算，只有将此牢记，我们的大桥才是最安全的。

当然，遵循有限集合的原则是重要的，不管什么时候它对关系到我们的结果。但是我们不会变得对它痴迷。特别的，计算和近似的技巧在不同层面上与他们的基本原理有更多不同。所以，一旦有个结果从严谨的准则应用得到，我们会用评价和近似的传统分析方法（比如，用积分替换求和），而不需要顾虑去说明如何产生作为有限极限的不可数集合。

我们将自己强加概率理论的数学准则中，其比传统的统计文献中所表现的更为严格。传统的文献中，作者反复得给出一些上述提到的主观临时特定工具，任意而不够好得去做概率理论准则能够做到产生唯一而最优的结果。正式基于严格的遵循，使得我们能够避免出现人造的悖论和传统统计中的矛盾，这些在第15章和第17章有描述。

同样重要的是，该原则常常将计算简化为两种方式：(1) 决定统计样本分布的问题消失了，而数据的证据全部被呈现在似然方程里，该方程可以被很快的写出来；(2)可以在一开始就将恼人参数处理掉，进而减少搜寻算法的维数。如果问题中有一堆参数，这也就是说计算中等级减少的排序，需要用到最小二乘法或最大似然算法。Bretthorst (1988)的贝叶斯程序将这些优点展现的很不错，从数据中提取信息的能力有了较大的改进，比前人用到的方法要好。但是，这些只是成熟的贝叶斯模型所能做到的九牛一毛而已。我们在近期此领域会有一个较大的发展。

一个学会如何用概率理论直接作为延伸逻辑的科学家，比那些只是学到许多无关临时特定工具的科学家，在能力和创造性上有更大的优势。当问题变得更为复杂时，这种相对优势越明显。所以，我们认为在将来，所有定量科学领域的工作者会乐于使用概率理论，并以此类方式来作为实用的必须。从计量经济学到天文学，再到核磁响应光谱分析等许多领域，这种趋势已经形成；但是，在新领域取得进展，对使得整个20世纪科学倒退的传统和权威，必须有一个健康而不敬的发展方式。

最后，需要警告部分读者，不要去查找那些原本不存在背后细节的意义。当然，我们应该解释和用所有标准的概率统计的技术术语-因为这是我们的主题。但是，即使涉及逻辑推理的本质会使我们讨论许多同样的问题，我们的语言与逻辑学家和哲学家生硬的术语是不同的。这里没有文字游戏，也没有官样文字，只有直白的英语。我们认为，这样能将我们的信息足够清楚的传递给那些非常想懂它的人。对于任何事情，我们确定的是，不通过起初所走的那几个台阶很难真正搞得清楚，即无限的退回并从‘“存在”是什么意思？’的问题开始。

** 致谢

不仅是从Jeffreys、Cox、P´olya、和Shannon的作品中我得到了灵感，我从接触到的300左右名学生那里也收获颇多，学生们曾经孜孜不倦的发现我的错误并促使我更认真的思考许多问题。还有，许多年来，我的思考也受同事间的讨论所影响着。这里列出一些（按某些人喜欢的字顺反向排列）：Arnold Zellner，Eugene Wigner，George Uhlenbeck，John Tukey，William Sudderth，Stephen Stigler，Ray Smith，John Skilling，Jimmie Savage，Carlos Rodriguez，Lincoln Moses，Elliott Montroll，Paul Meier，Dennis Lindley，David Lane，Mark Kac，Harold Jeffreys，Bruce Hill，Mike Hardy，Stephen Gull，Tom Grandy，Jack Good，Seymour Geisser，Anthony Garrett，Fritz Fr¨ohner，Willy Feller，Anthony Edwards，Morrie de Groot，Phil Dawid，Jerome Cornﬁeld，John Parker Burg，David Blackwell和George Barnard。虽然我并不同意他们所告知的那些所有各类的东西，但是却被这样或那样的方式在下文中被考虑。即使当我们最后在某些问题上没有达成一致，但我相信我坦诚而私人的讨论是我不至于错误描述了他们的立场观点，同时也使我的思路清晰。我对他们的耐心表示感谢。

E. T. Jaynes

1996年7月
