* 3 基本的抽样理论
在此，我们可用的数学材料包括积准则与和准则
                (3.1)

1                            (3.2)
从上式中我们可以得到拓展的和准则
                     (3.3)
并且还有愿景（Ⅲc）的一致性，无差异原则：如果以信息B为背景，假设是相互独立和可穷尽的，并且对于信息B中的任一信息不亚于任何其他信息，则
                   (3.4)
之后从(3.3)和(3.4)我们得到伯努利瓮准则：如果信息B限定了信息A，使得A在假设的M集合上为真，而在其余的（N-M）上为假，则：
                                  (3.5)
	重要的是要认识到，概率理论的多少可以从不超过此基础而得出。             

事实上，目前所教的基本上所有的传统概率论，加上往往被认为是超出了概率理论领域的许多重要结果，都可以由上述的基础推导得出。我们将在接下来的几章中详细说明这一点，然后在第11章中，我们将重新讨论机器人大脑的基础研究，以更好地了解哪些额外的原则需要进一步的被应用。

在本章中所给出理论的首次应用，与那些我们在以后所希望实现的严谨科学推理相比较，实质上是很简单的、很初级的。然而，我们对他们细节之处考虑的解释，并不是纯粹的教学形式。未能理解这些最简单应用的逻辑，已成为几十年来阻止科学推理（因此科学本身也是）进步的主要因素之一。因此，我们敦促读者，即使是已经熟悉基本抽样理论的人，在对更复杂的问题深入之前，要仔细消化本章的内容。

** 3.1 不放回抽样

让我们通过定义以下命题来使得伯努利情景稍微特别一些。

一个瓮里面有N个球，这些球被数字（1,2,…,N）标记，其中的M个为红色，剩下的（N-M）个为白色。除此之外，这些球没有任何的不同。我们蒙着眼睛从瓮中抓取一个球，观察并记录其颜色，放一边。之后，重复此过程直到n个球被抓取来为止，。
。
。

因为，基于信息B，只有红色或白色可抓取，我们有
1,                    (3.6)
这就等于说，在B信息所创造的“逻辑环境”中，命题与否定有关：
，                           (3.7)

而且，对于第一次抓取，(3.5)变为
                               (3.8)
                             (3.9)
让我们清楚地了解这意味着什么。概率赋值（3.8）和（3.9）不是对瓮或其内容的任何物理性质的断言；它们是在球被抓取之前对机器人知识状态的描述。事实上，如果机器人的知识状态与定义的B信息不同（例如，如果它知道红色和白色球在瓮中的实际位置，或者如果它不知道N和M的真实值），则和的概率赋值会有所不同；但瓮的真实性质是不变的。

因此，对瓮进行“验证”（3.8）的实验是不合乎逻辑的。这就像对男孩的狗进行实验来试图验证一个男孩对狗儿的爱。在这个阶段，我们关注的是对不完全信息的逻辑推理，而不是对物理事实（从瓮中可以拿到什么）的断言。

最终，我们的机器人将能够做出一些非常自信的物理预测方法，但（除了在退化的情况下）没有达到逻辑演绎的必然性；但是，在我们说什么量可以很好的预测和此处需要什么样的信息之前，理论需要进一步发展。

不同的是，不同知识状态的机器人赋予的概率与在实验中观察到的事实之间的关系，是不得任意假定的；我们只是使用那些可以从概率论规则推导出来的关系，就如我们现在要做的那样。

当我们问到第二次抓取对应的概率时，机器人的知识状态出现变化。例如，机器人前两次抓取为红色的概率是多少？由积规则，得到
                         (3.10)
在最后一项中，机器人必须考虑到一个红球已经在第一次抓取之时被移除了，所以还有（N-1）个球且其中的（M-1）个球是红色的。所以
                               (3.11)
同理，前r次抓取为红色的概率是
 ,              (3.12)
如果我们明白我们通过伽马方程关系来定义阶乘，约束条件就不是必须的了，则负数的阶乘是无限的，同时当 时(3.12)自动为零。

类似的，只需要将M替换为（N-M），前w次抓取为白色的概率是：
                     (3.13)
则，给定我们前r次抓取为红色的情况下，第（r+1, r+1, …,r+w）次抓取为白色的概率为，给定(3.13)，考虑将N和M分别替换为（N-r）和（M-r），
                 (3.14)
则，由(3.12)和(3.14)通过积准则得到，n次抓取得到w=n-r个白球和r个红球的概率为
               (3.15)
这一项被约去了。
	虽然该结果是
虽然这个结果是由拿出红球和白球的一个特定顺序所得出的，但在任何特定的顺序n次抓取中得到r个红球的概率是相同的。要看到这一点，用下面的方法将表达式（3.15）写的更详细
                     (3.16)
对于表达式（3.15）中其他的阶乘的比例是类似的。式子右手边变为
                 (3.17)
现在假设在任何其他顺序下，r个红球和个白球被抓到。这时的概率是n个因子的乘积；每次抓到红球，都会有一个因子（瓮中红球数）/（总数的球），对于抓到的白球也是类似的。每次抓取都会使得瓮中的球减一；因此，无论以前抓到的是什么颜色的球，对于第K次抓取，（N−K + 1）都会出现在分母。

	就在第K个红球被拿出之前，不管时发生在第K次抓取或是发生在之后的哪一次，总是会有（M−K + 1）个红球在瓮中；因而，抓取第k个球使得分子中有一因式（M-k +1）。就在第k个白色球被抓取之前，瓮内有（N-M -k + 1）个白色球；因而，不管这是发生在第k次抓取还是后来抓取，使得分子中有一因式（N-M-k +1）。因此，在所有n个球被抓取的时候，其中r个球是红色，我们已经在分子和分母中积累了与（3.17）中完全相同的项。抓取它们顺序的不同，只会使得分子中的因式排列顺序不同。因此，（3.15）给出了在n次抓取中以任何指定的顺序得到r个红球的概率。

请注意，在此结果中，积准则以特定的方式进行了扩展，向我们展示了如何将计算变成因素的乘积。给定了所有以前的抓取结果，每一个因素是在一个具体抓取中的一个概率。但是，积准则也可能会以许多其他方式扩展，这将会给出以前的抓取信息以外其他信息之上的一些因素。事实上，所有这些计算必须导致相同最终结果是一个非常重要的一致性属性，也是第2章的推导力求确保的结果。

接下来，我们问：无论顺序如何，机器人在n次抓取中恰好得到r个红色球的概率是多少？红色和白球的不同出现顺序在概率上是相互排斥的，所以，我们必须将所有这些可能性加总；但是，由于每个项都等于（3.15），所以我们只是以二项系数来相乘
                               (3.18)
该式表示在n次抓取中抓到r个红球的可能顺序的数量，或者就如我们所称呼他为，事件r的多项式。比如，为了在三次抓取中得到三个红球，只能发生仅
                                (3.19)
次，叫做；事件r=3有一个相重数。但是为了在三次抓取中得到两个红球，则有
                                (3.20)
种方式，命名为，，，所以，事件r=2有三个相重数。

将（3.15）和（3.18）相乘，许多因素可以被重新组织为三个伯努利系数。定义 ‘以任意顺序在n次抓取中得到r个红球’，并且方程
                            (3.21)
我们有
                           (3.22)
此式我们将简记为h(r)。通过约定，当或或时，它会自动化为零。

我们在这里做一些标记的技术说明，原因在附录B中有解释。原因在于，在我们的概率符号P（A|B）中有大写字母P，参数A、B总是代表命题，可能是相当复杂的口头陈述。如果我们希望使用普通数字作为参数，那么为了一致性，我们应该定义新的功能符号，如h（r|N，M,n）。为了尝试使用像P（r|NMn）这样从而忽略了在A和B中包含定性规定的符号，导致了对方程式误解（例如稍后讨论的边缘化悖论）的严重错误。然而，如第2章所述，我们使用p（A|B）或p（r|n）形式的概率符号中的小写字母p来跟随大多数当代著作中的习俗，其中我们允许论点是命题或代数变量；在这种情况下，必须从上下文判断意义。

基本结果（3.22）被称为超几何分布，因为它是与高斯超几何方程的幂级数表示的系数相关
                    (3.23)
如果a或b是负整数，则序列终止，且这是一个多项式。很容易验证生成函数
                    (3.24)
等于
                       (3.25)
其中c=N−M−n+1。由(3.24)得到明显的关系G(1)=1，这表示超几何分布被准确归一化。由于（3.25），G(t)满足二阶超几何微分方程，并在计算中有许多其他属性的用处。

虽然超几何分布h（r）看起来很复杂，但它具有一些令人惊讶的简单性质。通过和求解，发现r的最可能值在单位一内。我们得到
                       (3.26)
如果是一个整数，则和是最可能的值。如果不是一个整数，则会有个最可能的值
=INT()                            (3.27)
也就是，小于的下一个整数。

因此，如预期的那样，抓取的样品中红球的最可能分数f=r/n几乎等于原来在瓮中的分数F=M/N。这是我们物理预测的第一个粗例子：我们信息中指定的数量F与物理实验中可测量的数量f之间的关系，从该理论中衍生出来。

h(r)分布的宽度给出了机器人可预测r准确度的标示。通过计算确定R或更少红球的累积概率分布来回答许多这样的问题。如果R是整数， 
                          (3.28)

这是概率分布的中位数，如h(r)，被定义为给命题（r<m）和（r>m）赋予的等价概率中的数字m。严格来讲，根据这一定义，离散分布一般没有中位数。如果对于H（R-1）=1-H（R）和H（R）>H（R-1）有一个整数R的话，那么R是唯一的中位数。如果对于H（R）=1/2存在整数R的话，则（Rr<R'）中的任何r是中位数，其中R'是h(r)的下一个更高的跳点；否则没有。

但是出于最多的意图，我们可能会采取更放松的态度，约束严格的定义。如果n相当大，那么将H（R）最接近1/2的R值称为“中值”是合理的。在同样放松约束的情况下，H（R）最接近1/4、3/4的R可以分别称为“下四分位数”和“上四分位数”。同时，如果n10，我们可以称为H（R）最接近k/10的R值为'第k个十分位数'，等等。随着n→∞，这些松散的定义用严格的一个来达到统一。

通常，H（R）的细节不重要，同时为了我们的目的，它足以知道中位数和四分位数。于是，（中位数）±（四分位距离）将会提供一个足够好的机器人预测及其概率准确性的想法。即，对于给予机器人的信息，r的真值在区间内与在区间外是一样的。同样，机器人赋予r位于第一和第六位之间（5/6）-（1/6）=2/3的概率（换句话说，2：1的几率），被第一和第九个十分位数括起来（8：2=4：1的几率），等等。

虽然，可以为这些分布开发出相当复杂的近似公式，这在过去被广泛使用，但是今天更容易通过电脑计算确切的分布。例如W. H. Press et al. (1986)列出了计算a、b和c的任何值的广义复数超几何分布的两个例程。表3.1和3.2分别给出N=100，M=50，n=10和N=100 M=10，n=50的超几何分布。在后一种情况下，抓取十个以上的红色球是不可能的，所以r>10的条目都是h（r）=0、H（r）=1，而不是列表中的。有人会很快被h（r）的条目是相同的事实所镇住；在M和n的交换下，超几何分布具有对称性

h（r|N，M，n）=h（r|N，n，M）                      (3.29)
不管我们是从包含50个红色的瓮中抓取十个球，还是从包含十个红色的瓮中抓取五十个，以同样抓取方式抓取r个红色的概率是一样的。仔细检查（3.22），从超几何函数（3.23）可以看出a、b的对称性，就可以很容易地验证。

3.1和3.2表格所示的另一个对称性是关于其峰值分布h（r|100,50,10）=h（10-r|100,50,10）的对称性。然而，这不是一般的情况；将N变为99会导致略微不对称的峰值，如表3.3所示。表3.1中的对称峰值出现如下：如果我们交换M和（N-M），与此同时交换r和（n-r），我们实际上只互换了'红'和'白'，所以分布式是不变的：

但是当M=N/2,这将简化为对称式

在表格3.1所观察到的。通过(3.29)得到，当n=N/2时，峰值必须是对称的。

在（3.22）中更直观甚至可见，超几何分布具有两个以上的对称性。让我们询问机器人在第二次抓取为红色时的概率。这与（3.8）的计算不一样，因为机器人知道，就在第二次抓取之前，瓮内只有（N-1）个球，而不是N个。但是，在第一次抓取中什么颜色的球被去除是不知道的，所以，不知道现在瓮中红球数量是M还是（M-1）。那么，伯努利瓮结果（3.5）的基础就会丢失，而且这个问题似乎是不确定的。

但毕竟是相当确定的；以下是我们在概率计算中有用技术之一的第一个例子，它是从第1章和第2章所讨论的，将命题分解的更简单。机器人知道R1或W1是真的，因此我们使用布尔代数，有

我们应用和准则和积准则得到

但是

而且

消掉复杂部分之后，我们在第一和第二次抽签中的红色概率相同。让我们看看这是否继续下去。 对于我们第三次抓取，我们有

并且有

所有的复杂部分再次消除。如果机器人不知道任何其他抓取的结果，在任何一次抓取红色球的概率总是与伯努利瓮结果（3.5）相同。这是第一个非显而易见的对称性。我们不会在这里以普遍的方式证明这一点，因为它被作为一个更为一般结果的特殊情况；见下文公式（3.118）。

（3.32）和（3.36）所描述的计算方法如下：将概率所求得的数解析为相互排斥的子命题，然后应用和规则与积规则。如果子命题被很好地选择（即如果它们在上下文中的问题具有一些简单的含义），则它们的概率通常是可计算的。如果他们没有被很好的选择（如在第二章末尾的企鹅例子中），那么当然这个程序不能帮助我们。

** 3.2 逻辑vs.癖性

第3.1节的结果给我们带来了一个新的问题。在找到第k次抓取中确定为红色的概率时，知道前期抓取中发现是什么颜色显然是相关的，因为较早的抓取会影响第k次抓取时的瓮中红色球的数量Mk。知道稍后抓取的颜色是否相关？第一眼看来，似乎不可能，因为稍后抓取的结果不会影响Mk的值。例如，一个众所周知的统计力学博士（Penrose，1979）将其作为一个基本的公理，即当前的概率只能取决于之前发生的事情，而不是后来发生的事情。作者认为这是“因果关系”的必要物理条件。

因此，我们再次强调，正如我们在第1章中所做的那样，推理涉及逻辑关系，这可能或可能不对应于物理因果关系。为了说明为什么后期事件的知识与早期事件的概率相关，考虑一个已知的（背景信息B）只包含一个红色和一个白色球的翁：N=2，M=1。只给定这个信息，首次抓取到红色球的概率是P（R1|B）=1/2。但是，如果机器人得知红色球发生在第二次抓取上，那就变成了在第一次抓取中不会发生：
 
更一般的，积准则告诉我们

但是，我们仅仅看到所以

概率理论告诉我们，后期抓取的结果与早期的结果一样具有完全相同的相关性！即使执行后面的抓取也不是在物理上影响第k次抓取时瓮中红球的数量Mk，就如前期的信息一样，关于后来抓取结果的信息，与在第k次抓取时我们的知识状态，有相同的影响。这是我们的第二个非显而易见的对称性。

这个结果对于一些思考“概率的意义”的学派将是非常令人不安的。虽然普遍认为逻辑因果物理上的因果关系不一样，然而，仍有人试图将概率P（A|B）解释为B在A上的某种因果关系影响，并强烈的倾向坚持这种想法。这不仅在Penrose的上述工作中显而易见，而且更让人惊诧的是也出现在了哲学家Karl Popper1阐述的“倾向性”概率的理论中。

在我们看来，如（3.40）这样的一个关系从倾向性角度来说将是非常莫名的，虽然简单例子（3.38）使逻辑上的必要性显而易见。在任何事实上，从Penrose和Popper所设想的物理因果论中，我们在这里发展的逻辑推理理论在前景和结果中有根本的不同。显然，逻辑推理可以应用于物理因果关系假设是没有意义时的许多问题。

这并不意味着我们被禁止引入“倾向性”的概念或物理因果关系，关键是逻辑推理是适用和有用的，或不存在倾向性。如果这样的概念（即存在一些这样的倾向性）作为一个明确的假说被制定出来，我们的概率论形式可以分析其影响。我们将在下面的3.10节中进行分析。此外，我们可以根据证据来对假设与备择假设进行测试，正如我们可以测试任何明确的假设一样。其实，概率论最常见和最重要的应用之一是决定是否存在影响因果的证据：是一种新药更有效或新的工程设计更可靠？一个新的法律是否减少了犯罪的发生？我们从第4章开始学习假设检验。

在所有科学中，逻辑推理更普遍适用。我们赞同物理影响会随时间流逝只能向前传播；但逻辑推论在任何一个方向是均匀传播的。考古学家发现了一种改变他几千年前的事件信息的文物；否则，考古学、地质学和古生物学是不可能存在的。福尔摩斯的推理也是针对根据目前现有的证据，对过去有哪些事件发生进行推断。从600米远的行军乐队到达你耳朵的声音，改变了你关于在两秒钟前播放乐队的知识状态。听贝多芬交响乐团的Toscanini录音，改变了你关于多年前从他的管弦乐队获得声音Toscanini的知识状态。

正如我们将会验证的那样，也正如我们以后所说的那样，一个非平衡现象的完全充分理论，如声音传播，虽然他们不表示物理原因，也要求后向逻辑推论的认可和使用。关键是，无论是物理学、生物学、经济学或任何其他领域，无论如何这种信息的时间早于还是晚于现象本身，我们可以对任何现象做出的最好推论必须考虑到我们拥有的所有相关信息；这个应该被认为是老生常谈的，而不是悖论。在本章末尾（练习3.6），读者将有机会通过计算一个反向推论（考虑到正向的因果关系）来直接证明这一点。

更一般地，考虑概率分布p(x1...xn|B)，其中xi表示第i次的试验，并不只是两个值（红色或白色），但是说，值xi=（1,2，...，k）标记k个不同的颜色。如果任何排列xi下的概率是不变的，那么它只取决于样本号（n1 ... nk），其表示结果xi = 1发生的次数、xi = 2发生的次数，等等。此类分布被称为可交换的；正如我们将在以后发现的那样，可交换的分布具有许多有趣的数学属性和重要的应用。


回到我们的瓮问题，显而易见事实的是，不管时间顺序如何，不管他们队列的顺序是近或远，超几何分布是可交换的，每个抽签必须与每个抽签具有相同的相关性的。

但，这不限于超几何分布；这对于任何可交换的分布都是一样的，即不管任何时候，事件序列的概率独立于他们的顺序）。所以，再多想一想，从物理因果的角度来说，这些对称性是莫名其妙，然而作为逻辑的命题时，变得显而易见。

让我们定量地来计算这个效应。假设j<k，在布尔代数中，命题RjRk（在第j和k次抓取中为红色）为

我们可以用(3.36)的方式将其变为

个命题逻辑和的形式，每个都制定一个全序列，比如k个

的结果。概率P（RjRk|B）是其所有概率之和。但是我们知道，给定B，任何一个序列的概率与红色和白色出现的顺序无关。因此，我们可以将Rj移动到第一个位置，将Rk移动到第二个位置，来排列每个序列。也就是说，我们可以用（R1 ... Wj ...）等式来替换序列（W1 ... R j ...），等等。重新组合它们，我们抽签的每个可能的结果（3，4，...，k），然后有（R1R2）。 换句话说，RjRk的概率与

是相同的。同时我们有

类似的有

通过积准则，则

和

对于所有的j<k。通过(3.40)，结果(3.47)和(3.48)对于多有是真的。

既然这个结论对许多人来说是诧异的，那么我们用另一个不同的话来解释这个问题。机器人知道这个瓮最初含有M个红色球和（N-M）个白色球。然后，得知一个早期的抓取是红色的，它知道少一个红色球可用于后期抓取。这个问题就好像我们从其中（M -1）是红色的（N-1）个球开始；（3.47）只适用于适应这个不同问题的解决方案（3.37）。

但是为什么知道后来抓取的结果同样令人信服呢？因为，如果机器人知道红色将在以后的时间被抓取，那么实际上，瓮中的一个红色球必须“搁置”才能使其成为可能。由于有了这些信息，可以在早期的抽奖中获得红球的数量减少了一个。上面的例子（3.38）是一个极端特殊的例子，其结论特别明显。

** 3.3 不够精确信息的推理

现在让我们尝试把这个理解应用到一个比较复杂的问题上。假设机器人知道红色将在后面的抓取中至少发现一次，但不知在哪次抓取或哪几次抓取中发生。也就是说，新信息作为布尔代数的一个命题，

这个信息将第k次抓取的红色数量减少了至少一个，但是，Rlater是否与Rn具有完全相同的含义，并不明显。为了调查这一点，我们再次呼吁积规则的对称性：

其给出

同时，等式右手边所有的量将会容易求解。
	看到(3.49)，有人可能会尝试去推理得到下式

但是这是不正确的，因为除非M =1，事件Rj不是互斥的，正如我们从（2.82）看到的，还需要更多的术语。这种计算方法将是非常冗长乏味的。

请注意，为了更好地组织计算，Rlater的逆被陈述为所有后来抓取的为白色球：

所以，在所有后来抽签的白色概率，不管在较早期发生什么（即当机器人不知道在早期的情况发生了什么）。通过可交换性，不管后来发生什么事情，这与（n-k）次抓取中第一次得到白球的概率相同；由（3.13），

类似的，与（N-1）个球中（M-1）个红球的情况下有相同的结果：

现在(3.51)变为

作为一个检查，请注意，如果n =k+1，则应该简化为（M-1）/（N-1）。
但是，目前我们对（3.56）的兴趣并不在数值上，而是理解结果的逻辑。所以，让我们专注于最简单的情况，其并不完全是微不足道的。假设我们从含有N=4个球的瓮中抓取n =3次，其中M=2个是白色的，并且询问在第二次和第三次抓取中至少出现一次红球的信息是如何影响首次抓取时红色的概率。这是由（3.56）给出的，其中N = 4，M = 2，n = 3，k = 1：

对应（3.51）的最后一个形式。与以前计算的概率进行比较：

看起来让人吃惊的是

多数人首先会猜测不平等的符号应该是相反的；即知道在后面的抓取中红色至少发生一次，首先抓取为红色的几率信息应该比信息R2减少的更多。但在这种情况下，数字很小，我们可以直接检查计算（3.51）。为了通过扩展和规则（2.82）找到P（Rlater|B），现在只需要一个额外的项：

我们可以将Rlate很好的变为相互独立的命题并计算

（3.57）中的分母（1-1/6）现在已经以三种不同的方式计算得到相同的结果。如果三个结果不一样，我们将发现我们的准则存在不一致性，我们试图通过Cox在第2章中的方程论证来防止这种情况的发生。这是一个“一致性”在实践中意味着什么的很好例子，而且如果我们的准则没有，我们将会遇到麻烦。同样，我们可以通过独立的计算来检查（3.51）的分子：
结果（3.57）得到确认。所以我们别无选择，只能接受不平等（3.59），并尝试直观地了解它。让我们推理如下。信息R2减少了第一次抓取时一个可用红色球的数量，并且减少了可用于第一次抓取时瓮中的球数一个，得到P（R1|R2B）=（M-1）/（N-1）=1/3。信息Rlater减少了第一次抓取时可用的“有效红球数量”多余一个，但是它减少了第一次抓取中可用的瓮球数量两个（由于它确保机器人有两个以后被抓取，即两个将被去除）。所以，让我们暂时尝试将结果（3.57）解释为

虽然我们不太清楚这是什么意思。给定Rater，可以肯定的是，至少有一个红球被移除和两个被移除的可能性，由积规则得：

因为R2R3意味着Rlater；即布尔代数的关系为（R2R3Rlater = R2R3）。

直观地，给定Rlater，有两个红球被移除的概率为1/5，所以一出的有效数字是1+（1/5）=6/5。 剩余的“有效”数字是4/5。的确，则（3.63）变为

与我们更好的动机相符，但计算（3.57）不太直观。

** 3.4 期望

用另一种方式来查看这一结果，更加强烈地吸引了我们的直觉，并且将远远超出现在的问题概括了。我们难以想象，读者还不熟悉期望的想法，但这是目前第一次出现，所以我们停下来对其进行定义。如果可变量X可以在n个相互排斥和可穷尽的情况下取特定值（x1，...，xn），并且机器人给它们赋予相应的概率（p1，p2，...，pn），则数量

被称为X的期望（在较旧文献中，数学期望值或期望值）。根据其概率加权，它是可能值的加权平均值。统计学家和数学家通常使用符号E（X）；但是，物理学家已经预先利用E来代替能量和电场，使用<X>表示期望？我们在这里两个符号都会使用；他们有同样的意思，但有时候一个比另一个更容易阅读。

像久远的大多数标准术语一样，“期望”一词似乎对我们来说是不合适的；因为这几乎从来不是任何人都希望发现的值。事实上，通常被认为是不可能的价值。但是我们坚持这一点，因为几个世纪的先例。

给定Rlater，抓取一个球时瓮中红球数量的期望是多少？与Rlater兼容的有三种相互排斥的可能性：

M分别为（1,1,0），概率如（3.64）和（3.65）所示：

所以

因此，我们直观地称之为（3.63）中M的“有效”值实际上是M的期望值。

现在我们可以用更有说服力的方式来表述（3.63）：当红色球的分数F=M/N是已知的时候，则应用伯努利瓮准则，P（R1|B）=F。当F未知时，红色的概率是F的期望值：

一个在数值上等于一个分数期望的概率将被证明是普遍的准则，在数千个更复杂的情况下也是如此，为物理预测提供了最有用和最常用的准则之一。我们把它留给读者作为一个练习，来表明更通用的结果（3.56），也可以按照（3.72）建议的方式来计算。

** 3.5 其他形式与拓展

超几何分布（3.22）可以用各种方式来书写。九个阶乘可以被组织成为二项式系数，如下所示：

但M和n交换下的对称性仍然不明显；为了看到它，我们必须写出（3.22）或（3.73），显示所有的各个阶乘。

我们还可以以更对称的形式重写（3.22）作为对记忆的帮助：包含R红色和W白色的瓮中，在n=r+w次抓取中得到r个红色球和w个白色球的概率是

在这种形式下，它很容易被一般化。假设，不是只有两种颜色，在瓮中有k种不同颜色的球，颜色1的N1个，颜色2的N2个，...，颜色k的Nk个。在次抓取中，得到颜色1的r1个球，颜色2的r1个球，...，的颜色k的rk个。正如读者可以验证的，广义超几何分布：

** 3.6 作为数学工具的概率

从结果（3.75）可以得到遵循二项式系数所的多个数字。例如，我们可以决定不区分颜色1和2；即任何颜色的球被宣布为具有“a”的颜色。那么，从（3.75）开始，我们必须有一方面，

其中

但是，对于满足（3.77）的r1、r2的任何值，事件ra可能发生，所以另一方面，我们必须有

然后，比较（3.76）和（3.78），我们有

继续通过这种方式，我们可以得出遵循二项式系数的许多更复杂的形式。例如，

在许多情况下，概率推理是推导纯数学结果的有力工具；Feller（1950，第2和3章）以及本工作的后续章节给出了更多的例子。

** 3.7 伯努利分布

虽然数学上有点复杂，但是超几何分布是由概念上非常明确和简单的问题产生的。只有有限数量的可能性和所有上述结果，对于所述的问题是精确的。作为对数学上更简单的问题介绍，但在概念上更加困难，我们研究了超几何分布的有限形式。

超几何分布的复杂性的产生是因为它正在考虑到瓮里的变化；知道任何抓取的结果会改变任何其他得到红色的概率。但是，如果瓮中的球数N与抓取数（N》n）相比非常大，那么这个概率变化很小，而在极限N→∞中，我们应该有一个更简单的结果，没有这样的依赖性。为了验证这一点，我们将超几何分布（3.22）写为

第一项为

而且在极限N→∞，M→∞，M/N→f，我们有

类似的有

原则上，我们当然应该取（3.81）中积的极限，而不是极限的积。但在（3.81）中，我们定义了都有自己独立极限的因素，所以结果是相同的。超几何分布变为

被称为二项分布，因为生成函数（3.24）的值现在化简为

牛顿二项定理的一个例子。


图3.1比较了N = 15,30,100、M / N = 0.4，n= 10与n= 10，f = 0.4的二项分布三个超几何分布。他们在r = 4处都有峰值，所有的分布具有相同的一阶矩< r >= E< r >= 4，但二项分布更宽。

对于r = 0和r> 6，N= 15的超几何分布为零，因为从仅包含六个红色和九个白色的瓮中抓取十个球，所以不可能获得少于一个或六个以上的红色球。当N> 100的超几何分布与二项式非常一致时，对于大多数的目的，我们使用哪种方法并不重要。二项分布的分析属性在第7章中有所收集。我们发现在第9章中，与显著性检验相关联，在有限样本空间中二项分布对于纯组合原理是精确的，等式（9.46）。

我们可以对广义超几何分布（3.75）取类似的极限过程。这被留作练习来表明，在取极限过程中，以所有的Ni→∞这样的方式，分数

趋于常数，（3.75）变为多项分布

此处。并且，如（3.87）所示，我们可以从证明（3.89）正确归一化，来定义（k-1）变量的生成函数，并得出许多其他有用的结果。

** 3.8 可放回抽样

到目前为止，我们只考虑了我们在没有更换的情况下进行采样的情况；这显然适用于许多实际情况。例如，在质量控制应用中，我们所说的简单的“抓取一个球”可能包括一个制造品如电灯泡，从灯泡的纸箱中抓取，并对其进行破坏性检验。在化学实验中，它可能包括称量一种未知蛋白质样品，然后将其溶解在热硫酸中以测量其氮含量。在任何一种情况下，再也不会有“抓取同一个球”的想法。

但是，现在假设，我们从瓮里抓取球的破坏性较小，且在记录每个“颜色”（即相关属性）之后，在抓取下一个球之前将其在瓮内进行替换。这种采用替换的抓取方法在概念上是非常复杂的，但是通常做出一些假设，不需要更换最终比数学上更简单。让我们回到连续抓取两个红球的概率。用B’表示与以前相同的背景信息，除了增加球要被替换的假设，我们依然有一个类似（3.9）的等式：

第一个项显然依然是（M/N）；但是第二项呢？

一般来说，回答这一点将是一个非常困难的问题，如果背景信息B’包含一些我们都有的简单而高度相关的常识信息，则需要进行更多的分析。那么，我们将那个红球放回瓮中会发生什么变化？如果我们只是把它放进瓮里，立即抓取另一个球，那么它就被放置在其他球（或者是顶层的球）之上，所以更有可能比在瓮中其他任何一个在特定位置的未知球被抓取。但是，这破坏了我们计算的整个基础，因为抓取任何特定球（第i个球）的概率不再由得出（3.11）的伯努利瓮规则给出。

** 3.8.1 题外话：模型VS.对现实的布道

我们在这里遇到的困难是许多与对称性无关的事情，只要机器人的知识状态在球的任何排列下是不变的，突然变得相关。而且，由我们愿景之一的理性，机器人必须采取考虑到它拥有的所有相关信息。但得到任何特定球的概率现在依赖于这样的细节，如：瓮的确切尺寸和形状，球的大小，第一个被抛回的确切方式，球和瓮的弹性性质，球与球之间、球与瓮之间的摩擦系数，您抓取第二个球的确切方式，等等。在对称的情况下，所有这些细节都是无关紧要的。

即使所有这些相关数据都在手上，我们也不认为，这可以由世界上最好科学家和数学家的一个团队，并由世界各地的计算设备所支持的，能够解决问题；或者甚至都不知道如何开始。不过，不能够说这个问题原则上是无法解决的，只有这么复杂的问题不值得任何人花时间去考虑。那么我们该怎么办？

在概率理论中，有一个处理非常困难问题的一个非常聪明的技巧。我们只是通过如下方式来解决它：

（1）使它变得更难；

（2）通过“解决”重新定义我们的意思，使它成为我们能做的事情；

（3）发明一个有尊严和技术性的词来形容这个过程，其具有隐藏我们所做事情本质的心理效应，同时使它看起来可畏可敬。

在采用可放回抽样的情况下，我们应用此策略如下。

（1）假设在抛球后，我们摇摇瓮。不管最初的问题是多么复杂，现在变得很多数量级更复杂，因为现在的解决方案取决于除了以上所提到的所有因素，我们摇动它精确方式的每一个细节。

（2）我们现在断言，摇晃使所有这些细节变得无关紧要，使得问题回到伯努利瓮规则所适用的简单规则。

（3）我们发明了高大上的词语“随机化”来描述我们所做的事情。这个术语显然是一个委婉语，其真正含义是：当我们处理的问题太复杂时，故意扔掉相关信息。

我们以简洁的术语描述了这个过程，因为，对于一些作者创造的概念对概率论附上了一种神秘的印象，需要一种解毒剂。对于某些人来说，宣称某个问题是“随机化”是一个咒语，与驱魔者驱散邪灵所说的话具有同样的目的和作用；即它清除了他们随后的计算，并使他们免于批评。不可知论者经常羡慕真正的信徒，因为真正的信徒们就这么容易地获得永远被拒绝的安全感。

然而，为了防止这个过程，我们不得不承认，它通常会导致对正确解决方案的有用近似；即复杂的细节，尽管在原则上不可否认地相关性，可能对某些特别简单问题的答案几乎没有数量上的影响，例如：在n足够小时，在n次试验中抓取r个红球的概率。但是，从原则的角度来看，模糊的因素在这一点上必然要进入；因为，虽然我们可以直观地感觉到这导致了很好的近似，但我们没有证据证明这一点，更不用说可靠的估计精度，这种近似值可能随着更多的摇动而改善。

模棱两可的是，很明显存在这样的事实，就是不同的人对于步骤（2）中翁需要摇多少次，持有不同的观点。见证几年前围绕美国政府赞助和由全国电视播放的概率游戏节目的青年轰动，当有人反对从洗碗机中抓取数字的程序来确定年轻男子为军人服务的顺序，是“不公平的”，因为无论如何，碗没有摇的足以使得抓取“真的随机”。然而，如果有人向反对者提出问题：“对谁来说是不公平的？”他不能给出任何答案‘除了那些数字在上面的人，我不知道他们是谁’。但经过任何数量的进一步摇动，这仍然是真的！那么什么使得摇动结束呢？

摇晃不会使结果“随机”，因为作为现实世界的属性该术语基本上是无意义的；它在现实世界中没有明确的规定。认为“随机性”是自然界中存在的某种不动属性的信念，是思维投射谬误的一种形式，实际上，“我不知道详细的原因-因此-大自然不会知道他们”摇晃充分是非常不同的。它不会以任何方式影响大自然的运作；它只能确保没有人能够对结果施加任何故意的影响。因此，没有人可以因“固定”的结果被指控。

在这一点上，你可能会指责我们，因为你知道在所有这些讲道之后，我们会继续并只是像其他人一样去使用随机化的解决方案。但是请注意，我们的反对意见不是程序本身，只要我们诚实地承认我们正在做什么；即代替解决真正的问题，我们正在做一个实际的妥协，并且必须有一个近似的解决方案。这是我们在应用数学的各个领域必须做的事情，且没有理由期望概率论有任何的不同。

我们反对的是，认为以某种随机化的方式使我们的后续方程精确；确切地说，我们可以将我们的解决方案应用于各种极端条件，并相信将其应用于现实世界时的结果。这种信念产生的最严重和最常见的错误是极限定理的推导（即在可放回取样时，没有任何东西阻止我们趋向于极限n→∞并获得通常的大数定律）。如果我们没有认识到我们的起始方程的近似性质，我们欺骗自己相信已经证明了事实（如概率和极限频率的确认），这恰恰在实际的重复实验中是不正确的。

这里的危险特别大，因为数学家通常将这些极限定理视为概率论最重要和尖端的成果，并且有使用语言倾向于表明它们证明了现实世界的属性。

我们的观点是，这些定理是定义和分析的抽象数学模型的有效属性。问题是：该模型在多大程度上与现实世界接近？可以说，没有极限定理直接适用于现实世界，只是因为没有数学模型捕捉到与现实世界相关的每一种情况。相信所证明有关现实世界东西的任何人，是思维投射谬误的受害者。

让我们回到方程式。我们现在可以给出方程式（3.91）所提问题的答案是？在第二次抓取时得到一个红球的概率P（R2 | R1B’）明显不仅取决于N和M，还取决于红色已经被抓取和替换的事实。但后一种依赖是如此复杂，以致我们在现实生活中不能考虑到这一点；所以我们摇动瓮以'随机化'这个问题，然后声明R1是无关紧要的：P（R2|R1B2）=P（R2| B2）=M/N。在抓取和更换第二个球之后，我们再次摇动瓮，声明其为“随机化”，并设置P（R3 | R2 R1 B’）= P（R3| B’）=M/N等。这个近似中，在任何抓取中得到一个红球的概率是M/N。

这不仅仅是我们在（3.37）中所学东西的重复；这里新的地方是，现在的结果是机器人可能拥有对其他抓取时发生事情的任何信息。不管顺序如何，这导致我们写出在n次抓取中完全得到r个红球的概率

这只是二项分布（3.86）。从一个具有有限N个球的瓮中可放回的随机取样，与通过N→∞而没有放回的结果大致相同。

显然，对于小n，这个近似值会相当好；但是对于大的n，这些小错误（取决于我们如何摇动瓮等）可以积累到（3.92）所误导的地步。让我们用一个简单而现实问题的延伸来展现这一点。

** 3.9 矫正的矫正

假设，从复杂的逻辑分析中，抓取和替换一个红色球将增加在下一次抓取时一个红色的一个很小的概率值，而抓取和替换一个白色球的概率会降低在下一次抓取时一个红色的一个很小的概率（可能相等）值δ> 0；并且前一次抓取时对后一次抓取时的影响（分别对应的ε或δ）是不可忽略的。如果你喜欢，你可以称之为很小的‘倾向’；至少它表达了一个只能在时间上正向的物理因果关系。然后，让C代表所有上述的背景信息，包括刚才关于相关性的陈述和我们抓取n个球的信息，我们有

其中p≡M/ N。由此可以很容易地看到以任何特定顺序得到r个红色球和（n-r）个白色球的概率为

如果第一次抓取的是红色球，而如果第一次是白色的，则（3.94）中的第一项应该是（1 -p）。 在这里，c是红色球前面是红色球的个数，c’是红色球前面是白色球的个数，w是白色球前面为白色球的个数，w’是白色球前面是红色球的个数。显然，

分别是第一次抓取为红色或白色时的上和下的情况。
当r和（n -r）小时，和（3.94）中的ε和δ的表现几乎没有差异，且为了所有实际目的方程式简化为

如二项分布（3.92）。但是，随着这些数的增大，我们可以使用形式关系

且(3.94)变为

得到r个红色和（n-r）个白球的概率现在取决于所出现的红球和白球的顺序。而且，对于给定的ε，与（3.92）相比，当数字c，c’，w，w’变得足够大，概率变得任意大（或小）。如果我们假设N = 2M，p = 1/2，我们看到这个效果最明显，在这种情况下，我们肯定会有ε=δ。（3.98）的指数因子然后简化为

这表明（i）当抓取数n趋于无穷，与'随机化'近似的结果相比较，包含“长运行”（即，连续的红色（或白色）球的长串）的概率变得任意大；（ii）当数字（(εc)等成为秩序一致时，这个效果变得明显。因此，如果n<，只要n <100，随机化近似值就可以得到很好的信任。除此之外，我们可通过使用它来欺骗自己。实际上，实际重复实验中，在每次试验中条件似乎相同是臭名昭着的，这种运行-尽管在随机近似方面极不可能-仍然不会被观察到发生。

现在让我们注意（3.93）表达的相关性如何影响我们以前的一些计算。第一次抽签的概率当然与（3.8）相同；我们现在使用符号

但是对于第二次抓取，我们取而代之（3.35）

并且对于第三次抓取

我们看到P（Rk|C）不再独立于k；相关概率分布不再可交换。但是，P（Rk|C）在k→∞时接近一些极限。
按照（3.101）和（3.102）中的方法进一步推测，通过归纳来猜测一般的P（Rk|C）是几乎不可能的。对于这个计算，我们需要一个更强大的方法。如果我们把第k个试验的概率写成一个向量，

那么（3.93）可以以矩阵形式表示：

其中

这定义了一个马尔可夫链概率，M称为转移矩阵。现在，（3.101）和（3.102）慢归纳的过程将立即推广到我们想要的任何情形：

所以，为了有一般的解决方案，我们只需要找出M的特征向量和特征值。特征多项式为

所以C（λ）= 0的根是特征值

现在，对于矩阵

其中λ为特征值，对应的（非归一化）右特征向量是

我们立即有Mx =λx。因此，我们的特征向量是

这些不是正交的，因为M不是对称矩阵。然而，如果我们使用（3.111）定义转换矩阵

我们发现它的逆是

我们可以通过直接矩阵乘法来验证

此处的为对角线矩阵。那么，我们有，对于任意的r，正、负或复数：

或者

并且因为

寻求的一般解决方案（3.106）是

我们可以检查这是否与（3.100）、（3.101）和（3.102）符合。从（3.118）来看，很明显看出为什么几乎不可能通过归纳来猜测通用公式。当ε=δ= 0时，这简化为P（Rk|C）= p，在等式（3.37）之后提供了期待的证据。
虽然我们通过假设ε和δ是小的和正的来开始这个讨论，但实际上我们没有使用这个假设，所以无论其值是什么，结果（3.118）对于我们定义的抽象模型是精确的。这使我们能够囊括两个有趣的极端情况。如果不小，ε和δ必须至少是有界的，因为（3.93）中的所有数量必须是概率（即在[0,1]之间）。这就要求

或

但从（3.119），ε+δ=1当且仅当ε=q，δ= p，在这种情况下，转移矩阵简化为单位矩阵

并且没有'转换'。这是一种退化的情况，其中正相关性如此强烈，以至于无论第一次抓取的是什么颜色，所有后续的都将被确定：

同样，如果ε+δ= -1，则转移矩阵必须为

我们只是转换；即负相关性如此强烈，使得第一次抓取后的颜色必然会交替：

这种情况是不切实际的，因为很强的直觉告诉我们ε和δ应为正数；当然，无论使用什么逻辑分析来赋予数值，在顶层留下一个红球，必须增加而不是减少下一次抓取红色的概率。但如果ε和δ不能为负数，则（3.120）中的下限确实为零，这仅当ε=δ= 0时才可以成立。那么（3.105）中的M变为单数，并且我们回到已经讨论的二项式分布情况。在中间和现实的情况下，0 <|ε+δ| <1，（3.118）中的最后一项以k为指数衰减，并在极限

但是，尽管在可交换分布中，这些单一试验的概率会趋于稳定的值，但潜在的相关性仍然在起作用，并且取极限的分布是不可交换的。为了看到这一点，让我们考虑条件概率P（Rk|RjC）。
发现这些是通过强调，无论矢量Vk-1是什么都保持马尔可夫链关系（3.104）；即它是否是从如（3.106）中那样的V1生成的向量。因此，如果我们在第七次抓取中发现红色的话，则

并且由（3.104）我们有

利用(3.115)，得到

这接近同一极限（3.125）。关于我们预期的是前瞻性推论；稳定值（3.125）加上带距离呈指数衰减的项。但反向推论是不同的；请注意，一般的积准则如下：

因此，我们看到，然后有。

后向推论仍然是可行的，但它不再与正向推理有相同的公式，因为它将是可交换的顺序。

正如我们将在后面看到的，这个例子是一个非常常见和重要的物理问题的最简“婴儿”版本：“马可夫逼近”中的不可逆过程。另一种常见的专业术语将称之为第一阶自回归模型。可以大致推广到任意维度和多步骤或连续的矩阵，而不单是是单步骤记忆影响。但是由于前面提到的原因（统计力学文献中的推理和因果关系的混淆），解决问题的反向推理部分几乎总是被忽略。有人试图通过在时间上向后的正向推理解决来做反向推理，带来了一些相当奇怪和非物理性的结果。因此，实际上读者正以下练习中进行新的研究。

** 3.10 简化

对于任意的ε和δ，上述公式（3.100）-（3.130）满足不等式（3.119）。但是，在对它们进行调查时，我们注意到，如果满足这一要求，就会出现一个显着的简化

然后我们有

同时，我们主要的结果（3.118）及（3.128）变为


分布仍然是不可交换的，因为条件概率（3.134）仍然取决于试验的分离程度|k - j|；尽管影响因素ε，δ仅向前运行，但是正向与反向推理的对称性得到恢复。实际上，我们从（3.40）的推导中可以看出，不管分配是否可交换，这种前后对称是（3.133）的必要后果。

这个想象的条件（3.131）的意思是什么？它不会使矩阵M具有任何特别简单的形式，并且不会抹去相关性的影响。它的作用是使结果（3.133）不变；也就是说，初始向量（3.117）然后是相等的，但是为了归一化到（3.111）中的特征向量x1，因此初始向量由矩阵（3.105）来保持不变。

一般来说，这个简化条件当然不应该是这样的。然而在我们瓮的情况下，我们可以看到一种理由。假设当瓮最初有N个球时，它们是L层。然后，在抓取一个球之后，顶层中约有n =（N-1）/ L，我们预计其中约有np为红色，nq = n（1-p）为白色。现在，我们把拿出的球放回去，如果是红色的，如果我们不摇瓮，下一次抓取时得到红球的概率是

如果是白色的，在下一次抓取时获得白色的概率是大约为

与（3.93）相比，我们看到我们可以通过

来估计ε和δ，于是我们的想象的条件（3.131）令人满意。当然，刚才提出的论据太粗糙，不能称之为推导，但至少表明（3.131）没有内在的不合理之处。我们留给读者来猜测什么意义，并使用可能有的好奇事实，以及它是否概括了马尔可夫逼近。

现在，我们首先看到了标准抽样理论的一些原则和缺陷。我们发现的所有结果将更一般化，并且将是我们“工具箱”中以供应用时遵循的有用部分。

** 3.11 评论

在大多数真实的物理实验中，从字面上我们不是从任何“瓮”中抽样。无论如何，这个想法已经被证明是一个有用的概念设备，在伯努利的Ars Conjectandi以来的250年中，科学家们已经看到许多物理测量非常像“从自然的瓮里抽样”。但是对于一些字“瓮”具有可怕的内涵，而且在许多文献中，有些人会发现将此类表达为“从总体中抽样”。

在一些情况下，例如从放射源记录计数、调查抽样和工业质量控制检验，从字面上来说是来自一个真实的、有限的总体，而且类比瓮是特别适合的。那么刚刚发现的概率分布以及它们在第7章中指出的极限形式和一般化将是适当和有用的。在某些情况下，例如农业实验或测试新的医疗程序的有效性，我们的可信度可以逼近我们看到的与瓮问题模糊相似的地步。

在其他情况下，例如抛掷硬币、重复测量温度和风速、行星的位置、婴儿的重量或商品的价格，类似瓮看起来如此遥远以至于有被误导的危险。然而，在大多数文献中，有人仍然使用瓮分布来表示数据概率，并尝试通过将实验视觉化为从一些“假设的无限总体”中抽样来证明这一选择，而这完全是我们想象的一部分。在功能上，其主要后果是连续抽样的严格独立性，而不管其他任何情况。显然，这不是合理的理由，最终必在错误结论中付出代价。

这种概念化往往导致人们认为，这些分布不仅代表了我们知道数据的先前知识状态，而且代表了我们知道这些实验中数据的实际长期变化。显然，这样的信念是不合理的；任何声称提前知道未经执行实验长期结果的人，都是以生动的想象力来抽样，而不是建立在任何有关这种现象的实际信息之上。事实上，如果只有有想象力的人才，那么似乎我们可以自由地想象任何总体。

从只是想象的行为中，我们不能学到关于现实世界的任何东西。假设所得到的概率分配具有任何真实的物理意义，只是思维投射谬误的另一种形式。实际上，这将我们的注意力转移到无关紧要的事情上，而不是真正重要的事情（例如关于现实世界中那些任何抽样分布不能表达的信息，或者说，与瓮的描述不相符，但是对于我们想要做的推论还是非常有帮助的）。通常，为这种愚蠢所付出的代价是错失了机会；如果我们认识到了那些信息，更准确和/或更可靠的推论可能已经做出。

瓮型的概念化只能处理最原始的信息，真正复杂的应用要求我们研究远远超出瓮的想法。但情形相当微妙，因为正如我们在哥德尔定理以前所强调的那样，错误的论据并不一定导致错误的结论。事实上，正如我们将在第9章中发现的，高度复杂的计算有时候引导我们回到瓮式分布，因为纯粹的数学解释在概念上与瓮或总体无关。本章发现的超几何和二项式分布将继续重现，因为它们具有与我们以前在这里发现的论据完全独立的基本数学状态2。

另一方面，我们可以想象一个不同的问题，我们将有足够的信心认为瓮式推理导致二项式分布的，尽管它在现实世界中可能永远不会出现。如果我们有大量已知具有相同内容的瓮（U1，U2，...，Un），而且那些内容我们是知道提前确定的-然后我们使用一个新的瓮来进行每一次抽样-那么我们将为每次抽样赋予概率P（A）= M / N，与我们所知道的任何其他抽样严格地相互独立。此类先验信息优先于任何数据。如果我们不知道瓮里的内容（M，N）-但是我们知道他们都有相同的内容-这种严格的独立性将会丧失，因为从一个瓮里抽样来的每一个都会告诉我们一些关于其他瓮子里内容的东西，尽管它在物理上没有影响。

从这一点我们再次看到，逻辑依赖与一般的因果关系完全不同。我们非常赞同这一点，因为其在概率理论的大多数论述中根本不被认可，这导致了如所给出的练习3.6类的错误， 

在第4章中，我们会看到一个更严重的此类错误（见下面的讨论（4.29））。但是即使有人设法避免实际的错误，将概率论限于物理因果关系的问题是失去其最重要的应用。这种谬误的受害者，似乎并没有意识到这种限制的程度，以及错过机会的程度。

事实上，我们在本章中解决的大部分问题，都不被认为在概率论的范围之内，论述中并不表示将概率视为物理现象。这样的观点将一个问题的一个小问题限制在可以用概率论作为逻辑来有效处理的问题上。例如，在“物理概率”理论中，在特定试验中说出结果的概率甚至不被认为是合法的；但这正是有必要用科学推理来推导的原因。本章的计算已经说明了很多次。

总之：在下文的每个应用中，都要考虑一下这个实验是否真的像“从瓮里抽样来”；如果不是，那么我们必须回到第一条原则，并在新的上下文中应用基本的积准则与和准则。这可能或可能不会产生瓮分布。

*** 3.11.1 前瞻

本章中发现的概率分布称为抽样分布或直接概率，其表明具有以下形式：给出关于观察到现象的一些假设H（在刚刚研究的例子下，内容为（M，N）的瓮），我们将获得一些指定数据D（在这种情况下，红色和白色球的一些序列）的概率是多少？从历史上看，“直接概率”一词长期以来就具有从假定的物理原因到可观察效果推理的另外内涵。但是我们已经看到，并不是所有的抽样分布都可以这样解释。在目前的工作中，我们不会使用这个术语，而是将“抽样分配”用于一般意义上的推理，从某些具体假设到潜在可观察数据，不管假设和数据之间的联系是逻辑还是因果关系。

抽样分布对潜在观察（例如，不同r值的可能值和相对概率）进行预测，例如超几何分布（3.22）。如果正确的假设确实是已知的，那么我们预期这些预测将与观察结果密切相关。如果我们的假设不正确，它们可能会有很大的不同；那么本质的差异就给我们提供了一个寻找更好假说的线索。非常广泛地说，这是科学推理的基础。预测和观察之间的分歧有多大，必须证明了我们拒绝现在的假设和寻求新的假设之间是一个显著性检验的主观。在天文学，需要这种检验，其引导了拉普拉斯和高斯在十八世纪和十九世纪研究概率论。

虽然抽样理论在传统教学法中起着主导作用，但在现实世界中，这些问题几乎可以忽略不计。在几乎所有真正的科学推理问题中，我们处在一个截然相反的情形；数据D是已知的，但正确的假设H不是已知的。那么科学家所面临的问题就是相反的：给定数据D，一些指定假设H为真的概率是多少？以上的练习3.3简单介绍了这种问题。事实上，科学家收集数据的动机通常是为了让他以这种方式学习一些关于这种现象的东西。

因此，在目前的工作中，我们的注意力几乎全部用于解决逆问题的方法上。这并不意味着，我们不计算抽样分布；我们需要不断做这件事，而且这可能是我们计算工作的重要组成部分。但这确实意味着，对我们来说，找到抽样分布对于其本身几乎不是没有尽头的。

虽然概率论的基本规则解决这样的逆问题就如解决抽样问题一样，但是对于许多作者来说，它们在概念上已经出现了很大的不同。

一个新主题似乎要出现，因为很明显的问题是：“在看到数据D之后，你对H假设知道什么？”，除非我们考虑到以下内容：“在看到数据D之前，你对H假设知道什么？”，否则不能有任何可辩护的答案。但是以前的信息并没有在我们的任何抽样理论计算中得出。当我们问：“你知道关于瓮的内容（M，N）的数据是什么？”我们似乎没有考虑：“你知道（M，N）之前，你对数据有什么了解？”

这显然是不对称的，会变得比现实更明显；它主要产生于我们已经跌入一些符号习惯，其掩盖了所有推理的基本统一。但是，在我们可以有效地使用概率论进行假设检验及其特定情形显著性检验之前，我们需要对此了解得很充分。在下一章中，我们将介绍这个问题。


注：截图内容为原文可能存在的错误，翻译时未作改动

