* 2 定量准则

如今我们已经确切得将我们的问题阐述完毕，并且我们愿景结果的求出是一种直接的数学工作，其中的愿景可大致陈述如下︰

（Ⅰ）合情度由实数表示。

（Ⅱ）定性与常识相一致。

（Ⅲ）合情推理的一致性。

本章节整个的来分析遵循从这些愿景条件的演绎推理量化规则。所产生的规则有一个漫长、复杂和惊人的历史，充满了一般意义上科学方法论的经验教训（见几个章节末尾的评论部分）。

** 2.1 积准则


我们首先寻求逻辑乘积AB合情度与分开的A和B命题合情度相关的一致规则。特别的，让我们找到AB|C。由于推理是有点微妙，我们从几个不同的角度来审查它。

作为第一个方向，注意决定AB为真的过程可以分解成关于A和B分开的两个基本决定。机器人可以
（1）决定B为真；                             （B|C）
（2）已经接受B为真，决定A为真。            （A|BC）

或者，同样的有
（1）决定A为真；                             （A|C）
（2）已经接受A为真，决定B为真。            （B|AC）

在每种情况下，我们标记出以上对应步骤的合理度。

现在让我们第一个步骤用语句来描述。为了确定AB是真命题，必要让B是真命题。因此需要考虑B|C的合情度。此外，如果命题B为真，需要进一步确定命题A应该是真的。因此，A|BC的合情度同样需要。但如果B是假的，则AB当然是假，且独立于任何任何命题A，其用来表达。如果机器人现对命题B进行推理，则有关只有命题B为真时，命题A的合情度将与之有关。因此，如果该机器人有B|C和A|BC，则它将不需要A|C。关于AB，那将什么都没有告诉，也并不总是如此。

同样，A|B和B|A并不需要；无论A或B的合情度是否可能在信息C存在的条件下，不会与判决机器人知道C为真的例子中有关。例如，如果机器人知道地球是圆的，然后在今天判断关于宇宙学的问题，如果它不知道地球是圆的，并不需要考虑到它可能的意见（即它将需要考虑其他的可能性）。

当然，因为逻辑乘积是可交换的，AB=BA，我们可将上式中的A和B调换；即，知识A|C和B|AC将同样有助于确定AB|C=BA|C。机器人必须从任一过程得到AB|C的相同值，这是我们的一致性条件之一，愿景（Ⅲa）。

我们可以用更多定义的形式对此进行阐述。(AB|C）将B|C和BC的一些方程:
                          (2.1)
现在，如果在这里我们所经历的推理并不完全明显，让我们检查一些其他可能。例如，我们可以假设
                          (2.2)
这可能是一种允许的形式。但我们可以轻易地得出，此关系的任何关系都不能满足愿景（Ⅱ）。在给定C的情况下，A命题可能是很合情，同时给定C的情况下B命题可能是很合情的，但AB仍可能是非常合情或非常难以置信。

例如，你遇到的下一个人很有可能有蓝色的眼睛和也很有可能这人的头发是黑色的。二者都是真的，是合理可信的。另一方面，你遇到的下一个人左眼是蓝色的和你遇到的下一个人右眼是棕色，都是相当合情的。但如果你遇到的一个人左眼是蓝色的同时右眼是棕色的，是令人难以置信的。如果我们尝试使用这种公式，我们没有任何办法将这些因素考虑进来。我们的机器人不能使用这种函数关系来像人类一样推理，即使是定性的也不行。

但是我们想到其他的可能性。尝试所有的可能性的方法--一种穷尽的证明方法—介绍如下。给出实数
      (2.3)

如果u作为一个函数可被v、w、x、y中的两个或更多表示，有11中这样的可能性。你可以写出他们中的每一个，就如棕色和蓝色眼睛的例子里一样(这是抽象声明︰A蕴含着B为假)，赋予每一个不同的极端条件。在其他极端条件下的、、等。将这些繁琐分析开展的同时，Tribus (1969)发现只有其中两个合情度可以容纳和常识相左的一些极端情况。这两个合情度是和，只有这两个函数形式总是可以我们前面的推理相容。

我们现在用第一章中所讨论的定性条件。给定任意变化的先验信息，得到命题B变得更加合情而命题A不会发生变化，
                               (2.4)
                              (2.5)
常识需要AB仅能够变得更加合情，而不是变得不太合情：
                              (2.6)
仅当且当变得不可能时取等。类似的，给定先验信息，得到
                               (2.7)
                              (2.8)
我们需要
                              (2.9)

式中，给定条件C，仅当命题B不可能发生时等号可以成立（即使不被定义，给定的情况下，依然不可能为真）。进一步的，函数必须为连续的，(2.1)右边中一个合情度任意小的增加，可能会导致一个大的增加。

总之，F(x,y)必须是x、y的连续单调递增函数。如果我们假设它是可导的（这不是必须的，见（2.13）后的讨论），那么我们有
                            (2.10a)
与当且仅当y表示不可能时取等号；并且得到
                            (2.10b)
与当且仅当x代表不可能时取等。在这种表示法中，需要注意的是出于以后的目的，表示对于F的第i个元素的求导，无论它可能是什么。

接下来，我们重点转向愿景（Ⅲa）的“结构性”一致性。假设我们尝试寻找合情度（ABC|D），使得其中的三个命题同时为真。事实上，因为布尔代数是关联的：ABC=（AB）C=A（BC），我们可以用两种不同的方式做到这一点。如果规则是一致的，用两种顺序中的任何一个运算，我们都一定会得到相同的结果。我们就可以说，BC首先将被视为一个单位命题，然后应用(2.1)：
                    (2.11)
然后对于合情度BC|D，我们可以再次应用(2.1)得到
               (2.12a)

但我们同样也可以说，AB应首先被视为一个单位命题。从这我们可以推断出，用其他顺序可获得不同的表达式︰
        (2.12b)
如果此规则是代表论证的一致方式，两个表达式(2.12a)和(2.12b)必须始终是相同的。一个必要的条件是，我们的机器人在这种情况下将进行一致性推理，因此函数方程的形式为
                        (2.13)
这个方程在数学中有悠久的历史，从N.H.Abel (1826)的工作开始。Acz´el (1966)在他的巨著中对泛函方程，十分恰当地叫它‘结合律方程’，并列出参考文献共98篇来讨论它或使用它。Acz´el推导出一般的解决方案(2.27)，见下文，没有假设可微性；不幸的是，证明在他的书中占了11页(第256-267页)（同样可见于Acz´el，1987）。我们这里给出了较短的证明，该证明是由 R.T.Cox（1961）的，他假定了可微性；请参见在附录B中的讨论部分。

很明显，(2.13)拥有简单的解决方案，F(x,y)=常数。但这违反了我们的单调性要求(2.10)，并且在任何情况下，对于我们的目的是无用的。除非(2.13)有一个非平凡解，这种方法将会失败；因此，我们寻求最一般的非平凡解。用缩写
，                          (2.14)
但仍在认为为独立变量，函数方程被求解为
                              (2.15)
关于x和y求微分得到，我用(2.10)的标记法标记为


                  (2.16)
从这些方程中将消掉得到
                        (2.17)
这里我们标记。显然，(2.17)的左边必须独立于z。此时，(2.17)可以被写成
                        (2.18)
同时将(2.17)和(2.18)的左边分别用U、V来表示。我们可证。则必然与y相互独立。最一般的函数具有的性质是
                              (2.19)
这里的r是一个常数，并且函数是任意的。在此时的情况下，与F是单调的，所以我们需要让，，同时可能不会在有意的地方改变符号。用(2.19)、(2.17)和(2.18)得到
                              (2.20)
                             (2.21)
并且关系式具有形式
                          (2.22)
或者，积分的形式
                     (2.23)
这里的
                        (2.24)
积分更低下限的存在以为这w中一个任意多项式。但是通过(2.15)的函数形式和应用(2.23)，我们得到；再次应用(2.23)，我们的函数房产现在变化为
                 (2.25)
这意味着，我们得到了一个重要的解仅当r=1，同时我们的最终结果可以表示为两个形式中的任意一个：
                       (2.26)
或者 
                     (2.27)
结合律和交换律的逻辑乘积因此需要满足的关系必须采取的函数形式为
             (2.28)
今后，我们应称之为积准则。由(2.24)的构造可知，w(x)必须是正的连续单调函数，伴随着H(x)的符号变化增加或减少；在此情况下如此，它在其他情况下是任意的。

得到的结果(2.28)，作为愿景（Ⅲa）中一致性的一个必要条件。反过来，(2.28)很明显也是确保任意数量联合命题一致性的充分条件。例如，在(ABCDEFG|H）中有一个很多的不同方式，可以通过(2.12)连续分区的方式被扩大；但如果(2.28)被满足，他们会产生同样的结果。
与常识的定性要求给函数w(x)进一步施加条件。例如，在(2.28)的第一个形式中给定假设：给定C的条件下A是确定的。然后，在由知识C的所产生的逻辑环境中，在一个是真当且仅当其他是真的意义上，命题AB和B是相同。通过我们在第1章中讨论的公理，相同的真值必须有平等的合理性：
                             (2.29)
同时我们还会有
                             (2.30)
因为如果给定C下A已经确定（即C蕴含A），然后，给定的任何其他信息B且B与C并不矛盾，它是仍然确定的。在这种情况下，(2.28)化简为
                      (2.31)
同时，对于机器人来说，不管B是如何合理或令人难以置信，这必然成立。所以，我们的函数w(x)必须具有性质，确定通过下式来表示
                          (2.32)
现在，假设给定C的条件下A是不可能发生的。则给定C的条件下，命题AB也是不可能发生的：

                            (2.33)
同时，如果给定C的条件下A已经是不可能发生的，（即C蕴含着）。则进一步给出任何不违背C的信息B，A仍然会不可能发生的：
                            (2.34)
此处的(2.28)将被简化为
                     (2.35)
并且再次有，无论B合理度可能是什么，此方程必然成立。w(A│C)仅有两个可能值可以满足此条件：它可能是零或（排除选项，因为然后由的连续性必须要有可能为负值；(2.35)然后将矛盾)。

总之，与常识相一致的定性需要w(x)是正的连续单调函数。它可能会增加或减少。如果它是增加的，它的范围必须是从不可能的0增加到确定的1。如果它是降低的，其范围必须从不可能的降到确定的1。到目前为止，关于它如何在这些极限之间的变化，我们的条件什么都没有说。

然而，这两种可能性的表示在内容上是不同的。给定任一种函数，其在上述标准是可以接受并且用表示不可能，我们可以定义新的函数，这将是同样可以接受并且由0表示不可能。因此，如果我们现在通过选择0≤w(x)≤1作为规定，并不会失一般性；也就是说，就内容而言，所有与我们愿景相符合的一致性可能都被囊括在此。（正如读者可能的验证那样，我们一样可以选择相反的规定；和从这个角度上，包括其所有的应用的整个理论发展，同样会具有不太相似的函数形式，但具有完全相同的内容。）

** 2.2 和准则

因为如今考虑被认为是亚里士多德式逻辑的命题，必须是真或假，其逻辑和始终是假，逻辑积总是为真。A是假的合理度必须以某种方式依赖于为真的那个合理度。如果我们定义和，必须存在着某个的函数关系：
                                (2.36)
显然，与常识相一致的定性，需要在上是连续的单调递减函数，切具有极值，。但它不能只是具有这些属性的任意函数，因为它必须符合积规则可以被写为或的事实:
                        (2.37)
                        (2.38)
于是，利用(2.36)和(2.38)，则(2.37)变为
            (2.39)
再一次的，我们利用了交换性：在A、B是对称的，同时一致性要求
                        (2.40)
这对于所有命题A、B、C必须是成立的。特别是，(2.40)必须成立，当
                                  (2.41)
其中，D可以是任何的新命题。然后，我们得到在(1.13)之前标注的真值：
,                              (2.42)
并且，在(2.40)中我们可以写做

                     (2.43)
因此，使用缩写
,                     (2.44)
(2.40)变为函数方程
,                 (2.45)
这表示一种缩放属性，即必须符合积规则。在y=1特殊情况下，这将简化为
                            (2.46)
该式表明S(x)是一个自反身函数，。于是，从(2.36)可得到u=S(v)。但这只表示明显的有这样的实际关系：A和是互补的。不管我们用如何简单或禁止的字母所表示的命题。我们在(1.8)之前提到了这一点，如果不是在前面明显提到过，这不是容易辨认出来的。

在(2.45)中的域如下所示给出。命题D是任意的，，因此通过D的各种选择，我们在区间
                         (2.47)
可以实现的所有值，但S(y)=w(AD|C)=w(|ADC)，并且(2.47)只是(0≤S(y)≤x)，正如在(2.45)里所述。此域是关于x、y对称的;它可以写成与他们交换式同样的。几何上，它包括在单位平面（0≤x，y≤1）及以上的曲线y=S(x)在xy平面中的所有点。

事实上，该曲线的形状早已由(2.45)提到的上面的无数点所确定。如果我们设定，则当时，(2.45)中的两项趋于，但在不同的水平上。因此，当时，一切都取决于趋于零的确切方式。为了探讨这一点，我们定义一个新变量，该变量满足
                       (2.48)
则，我们可以选择，通过下式定义方程
                  (2.49)
同时当时得到的渐进线。
	现在考虑x,q作为独立变量，我们由(2.48)得到
              (2.50)
用(2.46)和它微分，可以简化为
           (2.51)
其中
                       (2.52)
用这些替代元素，我们的方程(2.45)变为
,   (2.53)

当时，后两项以指数增长的速度趋于零，所以必须为渐进线性的，
                      (2.54)
且有正的斜度
                          (2.55)
在(2.54)中，没有一个周期项的周期为，因为对于连续不同x值(2.53)必须满足，并且对于不同值也满足。但是，通过定义，J仅仅是一个关于q的方程，所以(2.55)右手边必须独立于x。用(2.52)得到
,                   (2.56)
或者，重新整理，必须满足微分方程
                    (2.57)
其中，是某一常数。满足的唯一解是
,                  (2.58)
同时，反过来，我们可以马上证明(2.58)是(2.45)的一个解。

式(2.58)首先是由R. T. Cox (1946) 通过一个不同的前提条件得到，前提中假设可二次微分。再次被证明是Acz´el (1966)，其并没有假设可导。（但对现在的应用中假设可导对于我们来说是一个无害的步骤，如果方程可以引导我们到不可导的方程，我们该拒绝整个理论，因为它与常识相违背。）在任何事件中，(2.58)是满足方程(2.45)和左边界条件S(0)=1的最一般方程，同时我们发现它自动满足右边界条件S(1)=0。

推导(2.45)式时既然用到了对命题B来说特别的式子(2.41)，我们于是尽可以得到(2.58)是满足一致性要求(2.40)的必要条件。为了检验它的重复性，把(2.58)代入(2.40)，我们得到
              (2.59)

(2.28)和(2.38)的优点略有些相同。所以，从(2.40)的意义看，(2.58)是在上一致性的必要充分条件。

至此的结果可以被总结如下。逻辑积的结合律要求合情度的一些单调方程必须遵循积准则(2.28)。结果(2.58)表明同样的方程必须也满足和准则
                      (2.60)
其中，m为正。当然，积准则自己也可以被同样的写为
=             (2.61)
但是接着我们会看到m的值确实是无关的，不管她取值为什么，我们都可以定义一个新方程
                            (2.62)
并且我们的准则可以有形式
                 (2.63)

1                         (2.64)
实际上，这没有失去一般性，因为唯一要求的是我们需要给方程增加条件：从w=0的不可能到w=1的确定之间连续单调递增的函数。但是如果满足这个条件，那么也同样要满足，。所以，为了说我们可以用m的不同值，并没有给我们任何自由，就如在任意w(x)中我们并没有的那样。愿景所允许的所有可能被包含在(2.63)和(2.64)之中，在两式中是任意一个在范围的连续单调递增方程。

是否需要其他的关系来满足合情推理的完备准则，可以从的合情度中足以决定任意逻辑方程？我们有，在积准则(2.63)和和准则(2.64)中，结合命题AB和逆命题的合情度公式。但是，我们需要注意，在讨论上式(1.23)中，结合律和逆运算是运算集的一个完备集，它可以推导出所有的逻辑方程。

因此，有人会推断我们对基本规则的搜索应该结束了。它应该是有可能由积规则与和规则的重复使用，来到达由产生的布尔代数中的任何合理度。为了验证这一点，我们寻求第一个公式逻辑和A+B。反复应用积规则与和规则，我们有


            (2.65)
最后得到
                      (2.66)
这个广义的和准则是在应用中最实用的一个。明显的，原始的和准则(2.64)是(2.66)的特殊形式，如果令。


为了拓展结果(2.66)，我们在上面的(1.17)曾指出出来矛盾之外的任意逻辑方程都可以表达为分离的一般形式，就如(1.17)中的基本命题并的逻辑和一样。如今，任意一个基本命题的合情度由积准则的反复使用来确定，然后通过(2.66)的反复使用可以得到任意逻辑和的合情度。实际上，这些基本命题并是相互独立的，所以我们可以发现（见下文(2.85)）这简化为简单和，其中最多有项。

所以，就如并和逆是演绎逻辑的运算符完备集合，上面提到的和准则与积准则是合情推理的完备集合。只要是背景信息足够充分的确定基本命题并的合情度，我们的准则就足以来确定由产生的布尔代数中的任何合理度。于是，在n=4的情形下，我们需要个基本命题并的合情度，在那里我们的准则将会确定个布尔代数中基本命题并的合情度。

但是，这几乎总是比我们实际应用中所需要的多。如果背景信息足以来确定一小部分基本命题并的合情度，这可能就足以来确定一小部分我们所关心的布尔代数。

** 2.3 定性

现在让我们来查看基于(2.63)和(2.64)的该理论，与演绎推理理论，以及第一章开始我们得到的各种定性论断的相关性。首先，很明显的有或的极限下，和准则(2.64)表示亚里士多德逻辑的原始假定：如果A为真，则A的逆必须为假，等等。

事实上，所有的逻辑都包括两个强论断(1.1)、(1.2)和他们伴随着的所有论断。现在用蕴含符号(1.14)来声明主要前提假设：
               
                          (2.68)
并且他们的结果是一连串的。如果我们让C来表示他们的主要前提假设
                                (2.69)
则这些与积准则相对应的这些论断的形式分别是：
，                     (2.70)
但由(2.68)我们得到和，并且(2.70)可以简化为
，                   (2.71)
就如(2.68)论断中所表述的那样。于是关系是简单的：亚里士多德推理逻辑是合情推理中准则的极限形式，就如机器人会变得越来越肯定它的结论。

但是我们的准则还有逻辑推理里没有包括的东西：弱论断(1.3)和(1.4)。为了展现那些总是可以从现有准则中得到的定性陈述，注意第一个弱论断

                         (2.72)
与积准则(2.63)相一致的形式
                     (2.73)
但是由(2.68)得，同时因为，(2.73)得到
                            (2.74)
就如论断中所声明的。同样的，弱论断(1.4)

                         (2.75)
与积准则相一致的形式
                      (2.76)
但是由(2.74)得到，并且(2.76)给出
                     (2.77)
就如论断中所声明的。
最后，警察的论断(1.5)，当被实际表述时，该论断看起来非常的弱，但他依然包括在了(2.73)形式所表述的积准则里。让C如今来表示背景信息（没有在(1.5)中所阐述，所以对于不明显是有必要阐述的），这个关键假设前提，“如果命题A为真，所以，命题B为真变得更加合情”，现在用形式
                    (2.78)
和(2.73)得到
                   (2.79)
就如论断中所声明的。
	如今我们不仅有了(2.79)这样的定性表述。在第一章里我们想得到但没有任何答案：是什么决定了证据B是否可以使得A几乎可以确定呢？或者是什么会对它的合情度有负面影响呢？从(2.73)得到的答案是，因为不能大于单位1，只有当很小时，A的合情度的巨增才能发生。观察那人的行为（B）可以使他的罪行（A）看起来非常确定，因为行为在背景信息下是非常不被认可的。没有一个警察曾看到过那样一个无辜的人有那样的行为。另一方面，如果知道A是真仅可以对B的合情度增加一点点，所以观察到B斤可以对A的合情度增加一点点。
	我们可以给出更多这样可以对比的典型。实际上，与尝试相一致的这些完备的定性准则早已被许多作者所注意和描述，包括Keynes (1921), Jeffreys (1939), P ´olya (1945, 1954), R. T. Cox(1961), Tribus (1969), de Finetti (1974a,b),和Rosenkrantz (1977)。P´olya的描述在第一章和前言里都已简单描述，同时我们刚刚也已将Cox的详细重述。然而，我们现在的目的是要继续进行定量的应用，所以我们回顾了理论基础的发展。

** 2.4 数值

到目前为止，我们已经找到了最一般的一致性准则，通过我们的机器人可操纵的合情度，理所当然地认为它必须与实数联系起来，这样它的大脑可以通过开展一些确定的实际操作来运行。虽然我们被刚才提到这些规则及其定性性质所熟悉的正式形式所鼓励，两个明显的迹象表明，我们设计机器人大脑的工作还没有结束。

首先，虽然准则（2.63）、（2.64）对不同命题之间必须相关的合情度进行了一定的限制，但我们还没有发现任何独特的规则，而是一个由我们的机器人可以做到合情推理的可能规则的无限数量。对应于每一个不同选择的单调函数p（x），似乎都会有一组不同的规则和不同的内容。

其次，到目前为止，还没有告诉我们，合情度的实际数值应在一个问题的开始进行如何分配，使得机器人能够开始它的计算。机器人是怎样将背景信息的初始编码变为合情度的确定数值的呢？为此，我们必须调用尚未使用的“（1.39）的接口”愿景（IIIb）、（IIIc）。

下面的分析以某种既有趣又让人意外的方式回答了这两个问题。让我们回答合理度，即回答三个命题{A1，A2，A3}中至少有一个为真的合情度。我们可以通过两次应用扩展的和规则（2.66）得到，如下所示。在第一个应用程序给出
         (2.80)
其中，我们首先将作为一个单一的命题，并且使用逻辑关系
                     (2.81)
再次应用（2.66），得到七项，他们如下：


                           (2.82)
现在假设这些命题之间是相互独立的，证据B蕴含着其中没有两个可以同时为真。
                     (2.83)
(2.82)中的最后四项消掉，然后我们得到
             (2.84)
增加更多的命题等等，可以通过归纳容易得到：如果我们有n个相互独立的命题，(2.84)一般形式为
,             (2.85)
从现在开始我们将会经常用到的一个准则。

在传统的阐述中，等式(2.85)经常被作为基本来首先提出，就如我们目前可以看到的那样，传统理论提出的任意性。目前的做法表明，这条规则是从一致性的简单定性条件推演出来。该观点认为（2.85）作为原始、基本的关系，却是我们特别以避免的关系之一（请参阅本章的最后评论部分）。

现在假设命题不仅相互排斥，也是可详尽的。即，背景信息B规定有且只有其中一个必须为真。在这种情况下，所求的和（2.85）对于m=n必须是单位1：
                            (2.86)
单独的这些不足以确定单个数值。依赖于信息B的更多细节，许多不同的选择可能是适当的，并且一般会通过对B的逻辑分析找到。事实上，它是一个开放式的问题，因为B中可能包含的各种复杂信息没有结束的时候。因此，将那些信息翻译成数值的复杂数学问题是没有尽头的。正如我们看到的，这是当前最重要的研究问题之一; 我们可以发现的，把那些信息翻译成数值的每一个新原理，将开辟一个新的该理论的有用应用。

然而，存在一种情形答案是特别简单的，其只需要已给出原理的直接应用。但是，我们现在正在进入一个非常微妙的区域，一个多世纪混乱与争议的一个原因。在这一理论的早期阶段，就如在初等几何，我们的直觉远远领先于逻辑分析，而逻辑分析往往被忽视。麻烦的是，直觉使我们更迅速地得到最终结论，但没有其有效范围的任何正确评价。结果是，该理论的发展已经滞后了大约150年，因为各种工作者都坚持在该基础上讨论这些问题，不是论证证明，但却是他们相互冲突的直觉。

因此，在这一点上，我们必须要求读者压制你可能拥有的所有直观感受，并让自己仅由下面的逻辑分析所牵引。下面我们将给出的观点不能太认真的得到;并且，除非被清楚地理解，我们会从此面临非常棘手的概念。

考虑两个不同的问题。问题构造如下：我们有一个给定的相互排斥和可穷尽的命题，而且我们设法评估。问题的不同点在于:标记放入前两个命题已被互换。当然，这些标记完全是随心所欲的，我们选择哪个其中的命题叫做和都没有区别。在问题中，因此，我们也有一组互相排斥和可穷尽的命题，由下式给出


                    (2.87)
并且我们将去估计
	在可交换的标记中，我们已经制造了一个不同且非常相关的问题。明显的有，不管机器人所具有的关于在问题Ⅰ中的知识状态如何，必然与在问题Ⅱ中的具有相同的知识状态，因为他们是相同的命题，在两个问题中给定的信息B是相同的，而且同样的整个命题是让人值得深思的。所以我们必须有
                        (2.88)
并且类似的有
                        (2.89)
我们将这些称为变换方程。他们仅描述这两个问题是如何与彼此联系的，同时他们必须保持无论信息B可能是什么，特别是，在问题Ⅰ中无论命题多么的合情或不合情，对于机器人可能都是一样的。

现在假设在命题之间的信息B是无关紧要的。即，如果对于其中一个说一些事情，则关于另一个它说的是同样的事情。所以，它不包含任何任何理由会给机器人选其中一个而不是另一个。在这种情况下，问题Ⅰ和Ⅱ不仅不是无关的，而是完全等价的。即，在问题Ⅱ中的机器人有关命题的状态信息，包括其标识，恰好与它在问题Ⅰ中有关命题的相同。

现在，我们调用在（1.39）中（Ⅲc）的一致性意义上的愿景。这表示，相同的信息状态必须用相同的合情度来表示。在方程中，可将其表示为
                  (2.90)
此式我们可以叫做对称方程。但是如今，将(2.88)、(2.89)与(2.90)连立，我们等到
                          (2.91)

换句话说，在问题Ⅰ中命题和必须被给予相同的合情度（而且，当然在问题Ⅱ中是一样的）。

在这一点上，在这个问题上取决于你的个性和背景，对于结果（2.91），你有可能会深受触动，也有可能会大失所望。我们刚才给出的论证是赋值的群不变性原理的最初形式。当我们考虑将“无信息先验”赋值的一般问题时，这将在第6章中得到很大的拓展。

更一般地，让为的任意排列，并且让问题Ⅲ来确定。如果排列是这样的，将会有n个变换方程，形式为
                       (2.92)
其显示的问题I和III是如何彼此相关的。在任何给定的信息B的情况下，这些关系将保持。

但是，如果信息B现在在所有的命题之间是无关紧要的，那么在问题Ⅲ中的机器人有关命题的状态信息，与它在问题Ⅰ中有关命题的相同。一致性愿景要求在等价知识状态下分配相等的合情度，使得n个对称条件
                       (2.93)
由（2.92）和（2.93）我们得到n个方程
                      (2.94)
现在，这些关系必须保持，无论我们用什么样的特殊排列来定义问题III。有n！种这样的排列，所以对于给定的i来说，实际上其中有n！个等价问题，其中在（2.94）的指数k范围超过其他所有的（n-1）。因此，唯一的可能是，所有的是相同的（事实上，如果它是循环n阶，已经考虑了一个单一置换，这是需要的）。由于是可穷尽的，因此，（2.86）成立，唯一的可能就是
                      (2.95)
并且我们早已得到一组确定的数值！在Keynes (1921)之后，我们将此结果称为无差异准则。

也许，没有我们的告诫，不需要任何相当我们刚才的曲折推理，读者的直觉早已得到眼前的这个结论。如果是这样，那么至少，直觉与我们的愿景是一致的。但是仅仅用直觉写下（2.95）不能够给人对该结果感到一种重要性和独特性。为了看到唯一性，需要注意如果机器人被分配不同于（2.95）的值，则通过标签的单纯排列，我们可以展现第二个问题：机器人的知识状态是一样的，但是在那里它被赋予不同的合情度。

要看到其重要性，注意（2.95）实际上回答了在本节的开头提出的两个问题。它显示-在一个特定的情况下，可以得到很大的推广-机器人给定的信息如何得到确定的数值，使得计算可以开始。但同时也说明一些更重要的事情，因为它不是完全明显得直观。机器人给定的信息合情度确定数值，并且并不是开始的合情度的数值。一般这也将被认为是真。

认识到这一点，对于在一开始提出的第一个问题，给了我们一个美丽的答案。在已经发现的积与和准则之后，仍表明我们没有发现推理的任何独特规则，因为单调函数的每一个不同的选择将导致一组不同的规则（也就是一个具有不同内容的集合）。但是现在，我们看到无论我们选择什么样的函数，我们将得到同样的结果（2.95）和相同的数值p。此外，机器人的推理过程可以完全由量P操作进行，就如积与求准则显示的那样。并且，用p的来替代x，机器人的最终结论可以同样良好加以说明。

所以，我们现在看到的函数的不同选择，对应着我们可以设计机器人内部存储电路的不同方法。对于有关它推理的每一个命题，它将需要一个存储器，在给出的所有数据基础上，来存储一些表示合情度数的数值。当然，代替储存数值它同样可以存储的任何严格单调函数。但不管它在内部使用什么功能，机器人外部观察到的行为是一样的。

很显然只要我们认识到这一点，与其说是是x的一个任意单调函数，针对这一点更确切的不如说：

合情度x≡A|B，是P的任意单调函数，在定义域（0≤p≤1）上。
是P由数据所决定，而不是x。
因此，唯一的问题是由结果（2.95）自动处置。尽管第一个出场，实际上只有一个一致的规则，以此机器人可以做出合理推理，并且对于所有的实际目的，从我们开始的合情度x≡A|B中已经完全淡出我们的视野！我们只是没有进一步的使用它们。

我们已经看到，我们的合情推理理论完全可以在数量的P的条件下使用，我们最后给出他们的术语。从现在开始，我们将将这些量叫做概率。对于这一点，“概率这个词一直刻意避免。因为，鉴于这个词确实有一个通俗的意义：众所周知的“街上的人”，而对我们来说它是一个术语，它应该有一个确切的含义。但直到它已经证明这些是唯一由问题数据确定的量，我们没有理由假定该数量p拥有任何确切含义。

如今我们看到，定量p决定了一个在合情度上可以被衡量的特定量。原则上，在所有可能的单调函数里都可能达到同样的目的，我们选择了这个特殊函数，而不是因为它是更“正确”的，而是由于它是更方便的。即，它是数量p，顺从组合、积与和准则的最简单规则。正因为如此，p的数值由我们的信息被直接决定。

这种情况与热力学中情形的类似，所有可能的经验温度t彼此是单调函数，我们最终决定使用开尔文刻度T。不是因为它是比别的更“正确”，而是因为它是更方便，即热力学定律采取最简单的形式[，，等]，用特定度量的术语。正因为如此，开尔文刻度上的温度数值是在某种意义上“刚性地固定的”在实验中，独立于像水或汞任何特定物质的性质。

曾从（2.95）顺接的另一条规则，同样吸引着我们直觉的。考虑传统概率论的“伯努利瓮”。已知瓮里含有十个相同的尺寸和重量的球，标记为{1，2，...，10}。三个球（标记数字4，6，7）是黑的，其他七个是白色的。我们要摇动瓮，并蒙着眼睛取一个球。（2.95）中的背景信息B包含最后两句中的陈述。我们拿到一个黑色球的概率是多少？

定义命题：“第i个球被取出”，。因为背景信息与另外十种可能性无差别，应用（2.95），并且机器人赋与
                      (2.96)
这表明我们取出的一个黑球就是我们取出的数4、6或7；
                   (2.97)
但是这些事相互独立的命题（即他们声明相互独立的事件），所以应用(2.85)，并且机器人的结论是
                              (2.98)
就如直觉早已告诉我们的那样。更一般的，如果有N个此类的求，且命题A在任何特定的M子集上被定义为真，，其他为假，我们有
                              (2.99)
就如James Bernoulli(1713)给出的并150年以来的被大多数写者所用，这是概率的数学原始定义。比如，Laplace的巨著Th´eorie Analytique des Probabilit´es (1812)开篇用了这样一句话：

一件事情的概率，是青睐于其发生情形的数量，与当所有可能情形数量的比，当没有任何可令我们期望此类情形会比其他情形发生更多时，此类对于我们来说将有相同的可能。

** 2.5 标记与有限集合原则

如今我们将引出文中后面将要用到的标识（更详细的说明请见附录B）。于是我们通常的概率符号将用大写字母P:
P(A|B)                                (2.100)

该式显示的论证元素是命题。论证元素中的概率是由其他方程符号所表示的数值，比如
                               (2.101)

该式表示一般的数学方程。作此区分的原因是为了避免符号意义的模糊，这在此领域已经为一个当下的问题。然而，与现有文献中的习惯性的符号使用相一致，我们有时会放松标准已达到可以使概率符号或或能够得到论证，这些论证元素可以以任意的组合作为命题或作为数值。于是，用小表达的目的仅可以由上下文来判断。
	非常需要注意的是，我们已经设定的一致性定理仅对于那些赋予有限集命题的概率适用。原则上，任何问题必须从一个如此有限集合的概率开始，仅当无限集合是良好定义和从有限集合良好趋于极限的过程时，才允许无限集合的存在。更一般的，在任何数学运算中包括无限集合，保险的过程是有限集合准则：

应用运算和分析的过程一般只用于有限个数项的表达式。然后，在计算完成后，观察所产生的有限表达作为项数无限期地增加是如何表现的。

在铺垫这一行为规则中，我们仅仅是服从了从数学家阿基米德到高斯已考虑清楚的策略，这在所有数学家中回避废话显然是必要的。但是最近，无限集理论和测度理论的普及流行，使一些人无视它，并寻求其声称直接使用测度论的快捷方式。但是请注意，该行为的这个规则是与原来Lebesgue定义的测度是一致的，同时当一个良好定义的极限存在时，它会自动使我们纠正“测度理论”的结果。事实上，这是Lebesgue如何找到他的第一个结果。

危险的是，目前测度理论符号的前提是无限极限已完成，但不包含指示哪些取给取极限的过程中使用的符号。然而，正如我们在前言指出的，不同的取极限的过程-同样良好定义的-一般导致不同的结果。当没有良好的取极限时，任何试图直接去取极限都可能会导致没有意义的结果，其原因不能只要看起来只在于极限，而不看取极限的过程。

这个小“布道”作为第15章中无限集悖论的一个介绍，在那里，我们将看到一些结果，这些结果已经被那些无视这一行为规则，并试图在不考虑从有限集合的极限而直接计算无限集合的概率。所产生的结果充其量是模糊的，在最坏的情况下是荒谬的。

** 2.6 评论

花了两章来接近（2.99），其为拉普拉斯大约180年前开始的推理。在整个目前工作的其余部分，我们将试着去了解作为历史的一个奇怪插曲的期间。这个故事是如此复杂，以致于我们可以在未来十章逐渐展开它。为了这一开始，让我们考虑一些经常提出关于使用概率论作为逻辑延伸的问题。

*** 2.6.1 ‘客观’VS.‘主观’

这些词在概率论中被太多滥用，是的我们试图澄清我们是如何利用他们的。我们正在进行的理论研究中，任何概率赋予在某种意义上必然是“主观”的，它仅描述了知识状态，并不是可以物理实验测量。不可避免的是，有人会要求知道：“知识状态是谁的?”。答案永远是：“机器人-或只要是给定相同的信息和按照本章中我们推导使用的愿景相一致的其他任何人。

任何人只要是具有相同的信息，但得到与我们的机器人结论不同的，必然违反了这些愿景之一。虽然没有人有权力禁止此类冲突，但看起来有些理性的人，会发现自己违背了其中的一个，期望改变自己思路（在任何事件中，他将很确定说服每个人来接受他的结论是很困难的，特别是那些懂得改冲突的人）

现在，这只是我们接口愿景（IIIb）、（IIIc）的功能，使这些概率赋予某种意义上的完全“客观”，因为他们独立于用者的个性。他们是描述在声明问题中给出信息（或是同一件事，事件的编码）的手段，独立于任何涉及你或我的可能个人感觉（希望、恐惧、价值判断等）。它在需要一个受人尊敬的科学推理理论这个意义上，是“客观的”。

*** 2.6.2 哥德尔命题
为了回答另一个不可避免的问题，我们来概括在本章已经被证明和还没有被证明的内容。确定我们的积与和准则的主要建设性要求，是“结构一致性”的愿景（IIIa）。当然，这并不意味着我们的准则已经被证明是一致的。它仅意味着任何其他表示实数合情度的准则，但如果其与我们的内容不同，将必然导致要么与我们的愿景不一致，要么违反我们的愿景。

Kurt Gödel (1931)的一个著名定理（1931）指出，没有任何数学系统可以提供它自己一致性的证明。这会阻止我们证明概率论的逻辑一致性吗？我们并不准备回答这个问题，但也许我们可以将此澄清一点点。

首先，让我们确信“不一致” 对于我们和一个逻辑学家意味着是一件事情。我们的头脑中所想的是，如果我们的规则是不一致的，那么它可能会从他们的有效应用中得出矛盾的结果。例如，通过在两个同样有效的方式中应用准则，你可以得到P（A|BC）=1/3和P（A|BC）=2/3。Cox的函数方程试图防止其发生。现在，当一个逻辑学家说一个公理系统是不一致的，他意味着可以从一个矛盾命题得到它们。即，一些命题及其否定都是可以推断出来的。事实上，这并不是真的，与我们的意思不同。

为了了解上述Gödel的结果，最重要的一点是初等逻辑原则：矛盾意味着一切命题为真和假。（给定任何两个命题A和B，我们有A⇒（A+B），因此⇒）然后让是一个潜在数学理论的公理系统，让T为任何命题或定理，从他们可推论出1
                                (2.102)
如今，不管T是否确定，实际上命题T可由公理得到，然而不能证明他们是没有矛盾的，如果有矛盾，T就可能从他们确定的推导得到。

作为我们的一个问题，Gödel定理有一个本质。就如Fisher(1956)所指出的那样，他给我指出为什么Gödel的结果是真的直觉原因。我们不能假设任何逻辑学家能接受Fisher的作为Gödel定理证明的简单论断。然而对于大多数的我们，这要比Gödel的又长又复杂的证明更有说服力2。

现在假设公理包括一个不一致性。则T的逆，并且得到矛盾可以同样有他们得到：
                                (2.103)

所以，如果有一个不一致，它的寻找可以通过举出任意的和他的逆被证明，二者都可以由公理推导得到。然而，在实践中，他不能简单地找到一个T，来看到如何证明和。
	明显的，如果我们可以找到一个可行的过程，该过程可以保证在存在的情况下得到不一致，我们就可以证明公理的一致性。所以，Gödel定理看上去蕴含着没有此类过程存在。实际上，它只是说没有此类的过程可由存在的可测试公理系统推导出。
	我们需要找到与此逼近的概率理论。其实一个具有分析能力的工具，能够找到一组命题，并且如果命题存在的情况下从他们中检测到矛盾。原则是，在矛盾前提之上的概率条件不存在（假设空间被缩减为空集）。所以，让我们的机器人去工作；也就是说，写一个计算机程序来计算在集合条件上的概率。即使检查中没有明显的矛盾，如果在E中隐藏有矛盾，计算程序也会崩溃。
	我们发现这个“经验”，并且在一些思考之后，意识到这不是一个令人失落的一个理由，而是一个给我们一个没有预先看到的特殊情形的有价值的警告工具，在此特殊情形下，我们对问题的构想可失败。
	如果计算机程序不崩溃，但得到一个确切数值，那么我们知道条件命题是相互对立一致的，而且我们完成了在Gödel定理看来是不可能的事情。但是当然，我们应用概率理论看起来符合准则，而不是从被测试过的命题得到的，所以并没有困难；理解Gödel定理可以证明和不可以证明的内容是重要的。
	当Gödel定理看起来有更多一般性的结论，这些结论在一些数学系统中包含着一些不能再该系统中被确定的命题，它对于逻辑学家看起来就有很大的心理吹嘘，逻辑学家第一眼视他为他们想要达到的不可逾越的障碍。然而，在顷刻思考给我们呈现出，许多特别简单的问题是不可以用演绎逻辑确定的。有很多情况可以证明确定的性质必然存在于一个有限集合，即使难以将集合的任意数字呈现出来，也是具有此类性质的。比如，两个人是一件事情的单独见证者；他们给出了相反的证言并都死了。那么我们知道其中有一个是在撒谎，但是不可能来确定是哪一个撒谎。
	在此例子中，不可确定不是命题或事件的内在性质，它只是我们自己拥有信息的不完全。但是这是抽象数学系统的等价真值。当一个命题在此类系统中是不可确定的时候，那就仅仅意味着它的公理不能提供足够的信息来判定。但是原始集合之外的新公理可能提供缺失的信息并且可以使得命题变得可判定。
	在未来，随着科学变得越来越面向信息内容方式的思考，Gödel定理的结果将被视为老生常谈而不是一个悖论。的确，从我们的观点出发，“不可判定”仅仅表示一个呼吁推断推理而非演绎推理的问题。作为逻辑扩展的概率论专为这类问题而设计。

这些考虑似乎打开了，通过调用概率论之外的原则进入更宽领域，人们可能能够证明我们规则的一致性。目前，这在我们看来是一个悬而未决的问题。

不用说，没有任何矛盾曾经从我们规则正确应用中被发现，尽管我们的一些计算将会严格测试他们。表观上早已被证明的不一致性，仔细观察却是规则的误用。在另一方面，通过考克斯定理的引导，它告诉我们看哪里，在临时给定准则下给出不一致性时我们从未有过丝毫的困难，这与我们的内容不同，其唯一基础是其发明者的直觉判断。例子在正本书中都可找到，特别是在第5、15和17章。

*** 2.6.3 Venn图表

	毫无疑问，有的读者会问，“在相当长而且看上去无心用扩展求和规则（2.66）得到后，这在我们新符号采取的形式
P（A+B|C）=P（A|C）+P（B|C）-P（AB|C）                  (2.104)
我们为什么不用Venn图来说明它？那使得它的意义更加清楚”。（这里要画两个圈标，记为A和B，具有AB的交，所有的都在圆圈C中）。

Venn图的确是一个有用的工具，描述--在一个特殊的情况下-为什么逆项出现在（2.104）中。但它同样可以误导，因为它对与我们的直觉表明比（2.104）的实际内容较多。纵观Venn图，我们被鼓励去问：“图中的点是什么意思？”如果图的目的是说明（2.104），则A的概率大概是由圆A的面积代表；则准确地对应于（2.104），对于由圆A、B所覆盖的总面积是他们各自面积之和减去重叠面积。

现在，圆A可以以多种不同的方法分解成不重叠的子区域；做这些分区域的意思是什么？因为它们的领域是可加的，如果Venn图是仍然适用的，他们必须代表A的更新是可以分为一些独立命题的并。我们可以-如果我们不对顾忌数学逼近无限的限制-想象这细分延续到图中的各个点。因此，这些点必须代表了某些最终的'基本'命题，在其中A是可以被表示的3。当然，一致性则要求我们假设B和C也可以被分解成这些相同的命题。

我们已经跃升到了结论，在一定的空间里对应的点集命题赋予概率，该逻辑和A+B代表集合的并，AB为他们的交集，并且概率是在那些集合上的可加度量。但我们正在开发的一般理论没有这样的结构；所有这些东西都仅是Venn图的属性。

在发展我们的推断理论中，我们已经用特别的痛苦来避免限制性假设，这些假设会限制其范围；对于有明确意义的任何命题，它是原则上应用的。在一些特殊情况下，这些命题恰好是关于集合的陈述，Venn图是（2.104）的适当说明。但我们推理的大多数命题，例如命题，
                               (2.105)
                               (2.106)

是事实的简单声明语句，在我们问题的范围内，这可能会或可能不会解析成更基本的命题

当然，人们总是可以通过引入不相干强硬的解；比如，尽管上述定义的B与企鹅无关，我们仍然可以将他解析为和
                              (2.107)

其中，在南极的企鹅数量为k。通过选择足够大的N，我们肯定会得到布尔代数的一个有效声明；但这是无聊的，并且它不能帮助我们推断屋顶漏水。

即使在我们的问题存在有意义的解，它对于我们可能没有任何用处。例如，命题“今天下雨”可以分解为每个雨滴可以想象的所有可以枚举的轨迹；但我们不会看到这是如何帮助气象学家来预测下雨的。在实际的问题中，对于此解析有一种自然的结束，超过此是没有用处的，并蜕变为一个空的练习。我们应该在后文（第8章）给这个一个明确的示范，在“山姆被损坏的温度计”的情景里：是否是确切的方式，其关系到山姆应该从损坏的数据中得出的结论？

在某些情况下，有一种解决方法与上下文的问题有关，它成为一个有用的测算装置；放出（2.98）是一个简单的例子。每当我们可以时，我们很乐意充分利用于此，但我们不能指望它的一般性。

在我们的问题里，甚至当A和B两者都可以在某种程度和某种意义上得到解决时，它们可分解成同一组基本的命题的情形是很少的。同时，我们始终保留权利通过引入更多的命题D、E、F来讨论，以扩大我们的背景；我们几乎不指望所有的命题将继续被表达为同一原始集合的基本命题。假定这个，将会对我们理论的普遍性起到一个完全没有必要的限制。

因此，AB的交应该被简单地视为声明A和B是真；尝试读取任何更详细的含义，如集合的交，是错误的。那么p（AB|C）在其权限中，也应被视为一个基本的量，不一定非要解析成更基本的（不过，如果其是可以解析的，这可能有益于对它的计算）。我们坚持原始的布尔记号A+B、AB，而不是常见的A∨B，A∧B，或A∪B，A∩B，人人都拥有一个集合理论背景与之相关联，以尽可能阻止这种混乱。

因此，我们宁愿说，在一种特殊情况下，（2.104）解释和矫正了Venn图，而不是说，Venn图矫正或解释了（2.104）。但在概率论的历史上，就如我们将要点到的那样，Venn图发挥了重大作用。

*** 2.6.4 ‘Kolmogorov公理’

在1933年，A. N. Kolmogorov用概率论集合论和测度论的语言表述，提出了一种方法(Kolmogorov, 1933)。这种语言就在那时变得如此流行，以致于今天很多的数学结果都被命名，而不是为发现者，而是对于谁用那样的语言第一个再次重述。例如，在连续群理论中的术语“赫尔维茨不变积分”消失了，由“哈尔测度”所取代。由于这一习俗，一些现代作品-特别是数学家-能给人一个概率论开始于Kolmogorov的印象。

Kolmogorov通过Venn图形式化和公理化我们刚才描述的图。在第一瞥，这个系统看起来与我们的完全不同，使得需要一些讨论来看看他们之间的密切关系。在附录A中，我们描述了Kolmogorov系统并给出，对于所有的实际目的，关于其概率测度的四个公理，首先任意规定（对此，Kolmogorov一直被批评），在本章都被衍生为必须满足我们的一致性要求。这样一来，我们需要找到自己为Kolmogorov辩护，反对很多技术要点的批评。谁在Kolmogorov基础上第一个了解到的概率论，强烈建议读者阅读附录A中的与这一点有关的内容。

然而，我们的概率系统，与Kolmogorov的在概念上有不同之处，我们不用集合来解释命题，但我们将概率分布解释为不完全信息的载体。部分由于这个原因，在Kolmogorov系统中，我们系统的分析资源根本不存在。这使得我们能够制定和解决很多问题-尤其是所谓的“不适定”问题和“广义逆”问题-对于Kolmogorov系统，将会被认为超出了概率论的范围。在当前应用中，这些问题只是那些最感兴趣问题中的一些。
